// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agentassist.proto
// Protobuf Java Version: 4.36.0

package code.agentassistant.flutter.flutterclient.proto;

/**
 * <pre>
 * ChatMessage represents a chat message between users
 * </pre>
 *
 * Protobuf type {@code agentassistproto.ChatMessage}
 */
@com.google.protobuf.Generated
public  final class ChatMessage extends
    com.google.protobuf.GeneratedMessageLite<
        ChatMessage, ChatMessage.Builder> implements
    // @@protoc_insertion_point(message_implements:agentassistproto.ChatMessage)
    ChatMessageOrBuilder {
  private ChatMessage() {
    messageId_ = "";
    senderClientId_ = "";
    senderNickname_ = "";
    receiverClientId_ = "";
    receiverNickname_ = "";
    content_ = "";
  }
  private int bitField0_;
  public static final int MESSAGE_ID_FIELD_NUMBER = 1;
  private java.lang.String messageId_;
  /**
   * <pre>
   * message id
   * </pre>
   *
   * <code>string message_id = 1;</code>
   * @return The messageId.
   */
  @java.lang.Override
  public java.lang.String getMessageId() {
    return messageId_;
  }
  /**
   * <pre>
   * message id
   * </pre>
   *
   * <code>string message_id = 1;</code>
   * @return The bytes for messageId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMessageIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(messageId_);
  }
  /**
   * <pre>
   * message id
   * </pre>
   *
   * <code>string message_id = 1;</code>
   * @param value The messageId to set.
   */
  private void setMessageId(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    messageId_ = value;
  }
  /**
   * <pre>
   * message id
   * </pre>
   *
   * <code>string message_id = 1;</code>
   */
  private void clearMessageId() {

    messageId_ = getDefaultInstance().getMessageId();
  }
  /**
   * <pre>
   * message id
   * </pre>
   *
   * <code>string message_id = 1;</code>
   * @param value The bytes for messageId to set.
   */
  private void setMessageIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    messageId_ = value.toStringUtf8();

  }

  public static final int SENDER_CLIENT_ID_FIELD_NUMBER = 2;
  private java.lang.String senderClientId_;
  /**
   * <pre>
   * sender client id
   * </pre>
   *
   * <code>string sender_client_id = 2;</code>
   * @return The senderClientId.
   */
  @java.lang.Override
  public java.lang.String getSenderClientId() {
    return senderClientId_;
  }
  /**
   * <pre>
   * sender client id
   * </pre>
   *
   * <code>string sender_client_id = 2;</code>
   * @return The bytes for senderClientId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSenderClientIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(senderClientId_);
  }
  /**
   * <pre>
   * sender client id
   * </pre>
   *
   * <code>string sender_client_id = 2;</code>
   * @param value The senderClientId to set.
   */
  private void setSenderClientId(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    senderClientId_ = value;
  }
  /**
   * <pre>
   * sender client id
   * </pre>
   *
   * <code>string sender_client_id = 2;</code>
   */
  private void clearSenderClientId() {

    senderClientId_ = getDefaultInstance().getSenderClientId();
  }
  /**
   * <pre>
   * sender client id
   * </pre>
   *
   * <code>string sender_client_id = 2;</code>
   * @param value The bytes for senderClientId to set.
   */
  private void setSenderClientIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    senderClientId_ = value.toStringUtf8();

  }

  public static final int SENDER_NICKNAME_FIELD_NUMBER = 3;
  private java.lang.String senderNickname_;
  /**
   * <pre>
   * sender nickname
   * </pre>
   *
   * <code>string sender_nickname = 3;</code>
   * @return The senderNickname.
   */
  @java.lang.Override
  public java.lang.String getSenderNickname() {
    return senderNickname_;
  }
  /**
   * <pre>
   * sender nickname
   * </pre>
   *
   * <code>string sender_nickname = 3;</code>
   * @return The bytes for senderNickname.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSenderNicknameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(senderNickname_);
  }
  /**
   * <pre>
   * sender nickname
   * </pre>
   *
   * <code>string sender_nickname = 3;</code>
   * @param value The senderNickname to set.
   */
  private void setSenderNickname(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    senderNickname_ = value;
  }
  /**
   * <pre>
   * sender nickname
   * </pre>
   *
   * <code>string sender_nickname = 3;</code>
   */
  private void clearSenderNickname() {

    senderNickname_ = getDefaultInstance().getSenderNickname();
  }
  /**
   * <pre>
   * sender nickname
   * </pre>
   *
   * <code>string sender_nickname = 3;</code>
   * @param value The bytes for senderNickname to set.
   */
  private void setSenderNicknameBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    senderNickname_ = value.toStringUtf8();

  }

  public static final int RECEIVER_CLIENT_ID_FIELD_NUMBER = 4;
  private java.lang.String receiverClientId_;
  /**
   * <pre>
   * receiver client id
   * </pre>
   *
   * <code>string receiver_client_id = 4;</code>
   * @return The receiverClientId.
   */
  @java.lang.Override
  public java.lang.String getReceiverClientId() {
    return receiverClientId_;
  }
  /**
   * <pre>
   * receiver client id
   * </pre>
   *
   * <code>string receiver_client_id = 4;</code>
   * @return The bytes for receiverClientId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getReceiverClientIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(receiverClientId_);
  }
  /**
   * <pre>
   * receiver client id
   * </pre>
   *
   * <code>string receiver_client_id = 4;</code>
   * @param value The receiverClientId to set.
   */
  private void setReceiverClientId(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    receiverClientId_ = value;
  }
  /**
   * <pre>
   * receiver client id
   * </pre>
   *
   * <code>string receiver_client_id = 4;</code>
   */
  private void clearReceiverClientId() {

    receiverClientId_ = getDefaultInstance().getReceiverClientId();
  }
  /**
   * <pre>
   * receiver client id
   * </pre>
   *
   * <code>string receiver_client_id = 4;</code>
   * @param value The bytes for receiverClientId to set.
   */
  private void setReceiverClientIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    receiverClientId_ = value.toStringUtf8();

  }

  public static final int RECEIVER_NICKNAME_FIELD_NUMBER = 5;
  private java.lang.String receiverNickname_;
  /**
   * <pre>
   * receiver nickname
   * </pre>
   *
   * <code>string receiver_nickname = 5;</code>
   * @return The receiverNickname.
   */
  @java.lang.Override
  public java.lang.String getReceiverNickname() {
    return receiverNickname_;
  }
  /**
   * <pre>
   * receiver nickname
   * </pre>
   *
   * <code>string receiver_nickname = 5;</code>
   * @return The bytes for receiverNickname.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getReceiverNicknameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(receiverNickname_);
  }
  /**
   * <pre>
   * receiver nickname
   * </pre>
   *
   * <code>string receiver_nickname = 5;</code>
   * @param value The receiverNickname to set.
   */
  private void setReceiverNickname(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    receiverNickname_ = value;
  }
  /**
   * <pre>
   * receiver nickname
   * </pre>
   *
   * <code>string receiver_nickname = 5;</code>
   */
  private void clearReceiverNickname() {

    receiverNickname_ = getDefaultInstance().getReceiverNickname();
  }
  /**
   * <pre>
   * receiver nickname
   * </pre>
   *
   * <code>string receiver_nickname = 5;</code>
   * @param value The bytes for receiverNickname to set.
   */
  private void setReceiverNicknameBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    receiverNickname_ = value.toStringUtf8();

  }

  public static final int CONTENT_FIELD_NUMBER = 6;
  private java.lang.String content_;
  /**
   * <pre>
   * message content
   * </pre>
   *
   * <code>string content = 6;</code>
   * @return The content.
   */
  @java.lang.Override
  public java.lang.String getContent() {
    return content_;
  }
  /**
   * <pre>
   * message content
   * </pre>
   *
   * <code>string content = 6;</code>
   * @return The bytes for content.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getContentBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(content_);
  }
  /**
   * <pre>
   * message content
   * </pre>
   *
   * <code>string content = 6;</code>
   * @param value The content to set.
   */
  private void setContent(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    content_ = value;
  }
  /**
   * <pre>
   * message content
   * </pre>
   *
   * <code>string content = 6;</code>
   */
  private void clearContent() {

    content_ = getDefaultInstance().getContent();
  }
  /**
   * <pre>
   * message content
   * </pre>
   *
   * <code>string content = 6;</code>
   * @param value The bytes for content to set.
   */
  private void setContentBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    content_ = value.toStringUtf8();

  }

  public static final int SENT_AT_FIELD_NUMBER = 7;
  private long sentAt_;
  /**
   * <pre>
   * timestamp when the message was sent
   * </pre>
   *
   * <code>int64 sent_at = 7;</code>
   * @return The sentAt.
   */
  @java.lang.Override
  public long getSentAt() {
    return sentAt_;
  }
  /**
   * <pre>
   * timestamp when the message was sent
   * </pre>
   *
   * <code>int64 sent_at = 7;</code>
   * @param value The sentAt to set.
   */
  private void setSentAt(long value) {
    
    sentAt_ = value;
  }
  /**
   * <pre>
   * timestamp when the message was sent
   * </pre>
   *
   * <code>int64 sent_at = 7;</code>
   */
  private void clearSentAt() {

    sentAt_ = 0L;
  }

  public static final int FORWARD_TARGET_FIELD_NUMBER = 8;
  private code.agentassistant.flutter.flutterclient.proto.ForwardTarget forwardTarget_;
  /**
   * <pre>
   * forward target selected by sender (optional)
   * </pre>
   *
   * <code>.agentassistproto.ForwardTarget forward_target = 8;</code>
   */
  @java.lang.Override
  public boolean hasForwardTarget() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * forward target selected by sender (optional)
   * </pre>
   *
   * <code>.agentassistproto.ForwardTarget forward_target = 8;</code>
   */
  @java.lang.Override
  public code.agentassistant.flutter.flutterclient.proto.ForwardTarget getForwardTarget() {
    return forwardTarget_ == null ? code.agentassistant.flutter.flutterclient.proto.ForwardTarget.getDefaultInstance() : forwardTarget_;
  }
  /**
   * <pre>
   * forward target selected by sender (optional)
   * </pre>
   *
   * <code>.agentassistproto.ForwardTarget forward_target = 8;</code>
   */
  private void setForwardTarget(code.agentassistant.flutter.flutterclient.proto.ForwardTarget value) {
    java.util.Objects.requireNonNull(value);
    forwardTarget_ = value;
    bitField0_ |= 0x00000001;
  }
  /**
   * <pre>
   * forward target selected by sender (optional)
   * </pre>
   *
   * <code>.agentassistproto.ForwardTarget forward_target = 8;</code>
   */
  @java.lang.SuppressWarnings("ReferenceEquality")
  private void mergeForwardTarget(code.agentassistant.flutter.flutterclient.proto.ForwardTarget value) {
    java.util.Objects.requireNonNull(value);
    if (forwardTarget_ != null &&
        forwardTarget_ != code.agentassistant.flutter.flutterclient.proto.ForwardTarget.getDefaultInstance()) {
      forwardTarget_ =
        code.agentassistant.flutter.flutterclient.proto.ForwardTarget.newBuilder(forwardTarget_).mergeFrom(value).buildPartial();
    } else {
      forwardTarget_ = value;
    }
    bitField0_ |= 0x00000001;
  }
  /**
   * <pre>
   * forward target selected by sender (optional)
   * </pre>
   *
   * <code>.agentassistproto.ForwardTarget forward_target = 8;</code>
   */
  private void clearForwardTarget() {
    forwardTarget_ = null;
    bitField0_ = (bitField0_ & ~0x00000001);
  }

  public static code.agentassistant.flutter.flutterclient.proto.ChatMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static code.agentassistant.flutter.flutterclient.proto.ChatMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static code.agentassistant.flutter.flutterclient.proto.ChatMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static code.agentassistant.flutter.flutterclient.proto.ChatMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static code.agentassistant.flutter.flutterclient.proto.ChatMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static code.agentassistant.flutter.flutterclient.proto.ChatMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static code.agentassistant.flutter.flutterclient.proto.ChatMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static code.agentassistant.flutter.flutterclient.proto.ChatMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static code.agentassistant.flutter.flutterclient.proto.ChatMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static code.agentassistant.flutter.flutterclient.proto.ChatMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static code.agentassistant.flutter.flutterclient.proto.ChatMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static code.agentassistant.flutter.flutterclient.proto.ChatMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(code.agentassistant.flutter.flutterclient.proto.ChatMessage prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * ChatMessage represents a chat message between users
   * </pre>
   *
   * Protobuf type {@code agentassistproto.ChatMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        code.agentassistant.flutter.flutterclient.proto.ChatMessage, Builder> implements
      // @@protoc_insertion_point(builder_implements:agentassistproto.ChatMessage)
      code.agentassistant.flutter.flutterclient.proto.ChatMessageOrBuilder {
    // Construct using code.agentassistant.flutter.flutterclient.proto.ChatMessage.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * message id
     * </pre>
     *
     * <code>string message_id = 1;</code>
     * @return The messageId.
     */
    @java.lang.Override
    public java.lang.String getMessageId() {
      return instance.getMessageId();
    }
    /**
     * <pre>
     * message id
     * </pre>
     *
     * <code>string message_id = 1;</code>
     * @return The bytes for messageId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageIdBytes() {
      return instance.getMessageIdBytes();
    }
    /**
     * <pre>
     * message id
     * </pre>
     *
     * <code>string message_id = 1;</code>
     * @param value The messageId to set.
     * @return This builder for chaining.
     */
    public Builder setMessageId(
        java.lang.String value) {
      copyOnWrite();
      instance.setMessageId(value);
      return this;
    }
    /**
     * <pre>
     * message id
     * </pre>
     *
     * <code>string message_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessageId() {
      copyOnWrite();
      instance.clearMessageId();
      return this;
    }
    /**
     * <pre>
     * message id
     * </pre>
     *
     * <code>string message_id = 1;</code>
     * @param value The bytes for messageId to set.
     * @return This builder for chaining.
     */
    public Builder setMessageIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setMessageIdBytes(value);
      return this;
    }

    /**
     * <pre>
     * sender client id
     * </pre>
     *
     * <code>string sender_client_id = 2;</code>
     * @return The senderClientId.
     */
    @java.lang.Override
    public java.lang.String getSenderClientId() {
      return instance.getSenderClientId();
    }
    /**
     * <pre>
     * sender client id
     * </pre>
     *
     * <code>string sender_client_id = 2;</code>
     * @return The bytes for senderClientId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSenderClientIdBytes() {
      return instance.getSenderClientIdBytes();
    }
    /**
     * <pre>
     * sender client id
     * </pre>
     *
     * <code>string sender_client_id = 2;</code>
     * @param value The senderClientId to set.
     * @return This builder for chaining.
     */
    public Builder setSenderClientId(
        java.lang.String value) {
      copyOnWrite();
      instance.setSenderClientId(value);
      return this;
    }
    /**
     * <pre>
     * sender client id
     * </pre>
     *
     * <code>string sender_client_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSenderClientId() {
      copyOnWrite();
      instance.clearSenderClientId();
      return this;
    }
    /**
     * <pre>
     * sender client id
     * </pre>
     *
     * <code>string sender_client_id = 2;</code>
     * @param value The bytes for senderClientId to set.
     * @return This builder for chaining.
     */
    public Builder setSenderClientIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setSenderClientIdBytes(value);
      return this;
    }

    /**
     * <pre>
     * sender nickname
     * </pre>
     *
     * <code>string sender_nickname = 3;</code>
     * @return The senderNickname.
     */
    @java.lang.Override
    public java.lang.String getSenderNickname() {
      return instance.getSenderNickname();
    }
    /**
     * <pre>
     * sender nickname
     * </pre>
     *
     * <code>string sender_nickname = 3;</code>
     * @return The bytes for senderNickname.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSenderNicknameBytes() {
      return instance.getSenderNicknameBytes();
    }
    /**
     * <pre>
     * sender nickname
     * </pre>
     *
     * <code>string sender_nickname = 3;</code>
     * @param value The senderNickname to set.
     * @return This builder for chaining.
     */
    public Builder setSenderNickname(
        java.lang.String value) {
      copyOnWrite();
      instance.setSenderNickname(value);
      return this;
    }
    /**
     * <pre>
     * sender nickname
     * </pre>
     *
     * <code>string sender_nickname = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSenderNickname() {
      copyOnWrite();
      instance.clearSenderNickname();
      return this;
    }
    /**
     * <pre>
     * sender nickname
     * </pre>
     *
     * <code>string sender_nickname = 3;</code>
     * @param value The bytes for senderNickname to set.
     * @return This builder for chaining.
     */
    public Builder setSenderNicknameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setSenderNicknameBytes(value);
      return this;
    }

    /**
     * <pre>
     * receiver client id
     * </pre>
     *
     * <code>string receiver_client_id = 4;</code>
     * @return The receiverClientId.
     */
    @java.lang.Override
    public java.lang.String getReceiverClientId() {
      return instance.getReceiverClientId();
    }
    /**
     * <pre>
     * receiver client id
     * </pre>
     *
     * <code>string receiver_client_id = 4;</code>
     * @return The bytes for receiverClientId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getReceiverClientIdBytes() {
      return instance.getReceiverClientIdBytes();
    }
    /**
     * <pre>
     * receiver client id
     * </pre>
     *
     * <code>string receiver_client_id = 4;</code>
     * @param value The receiverClientId to set.
     * @return This builder for chaining.
     */
    public Builder setReceiverClientId(
        java.lang.String value) {
      copyOnWrite();
      instance.setReceiverClientId(value);
      return this;
    }
    /**
     * <pre>
     * receiver client id
     * </pre>
     *
     * <code>string receiver_client_id = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearReceiverClientId() {
      copyOnWrite();
      instance.clearReceiverClientId();
      return this;
    }
    /**
     * <pre>
     * receiver client id
     * </pre>
     *
     * <code>string receiver_client_id = 4;</code>
     * @param value The bytes for receiverClientId to set.
     * @return This builder for chaining.
     */
    public Builder setReceiverClientIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setReceiverClientIdBytes(value);
      return this;
    }

    /**
     * <pre>
     * receiver nickname
     * </pre>
     *
     * <code>string receiver_nickname = 5;</code>
     * @return The receiverNickname.
     */
    @java.lang.Override
    public java.lang.String getReceiverNickname() {
      return instance.getReceiverNickname();
    }
    /**
     * <pre>
     * receiver nickname
     * </pre>
     *
     * <code>string receiver_nickname = 5;</code>
     * @return The bytes for receiverNickname.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getReceiverNicknameBytes() {
      return instance.getReceiverNicknameBytes();
    }
    /**
     * <pre>
     * receiver nickname
     * </pre>
     *
     * <code>string receiver_nickname = 5;</code>
     * @param value The receiverNickname to set.
     * @return This builder for chaining.
     */
    public Builder setReceiverNickname(
        java.lang.String value) {
      copyOnWrite();
      instance.setReceiverNickname(value);
      return this;
    }
    /**
     * <pre>
     * receiver nickname
     * </pre>
     *
     * <code>string receiver_nickname = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearReceiverNickname() {
      copyOnWrite();
      instance.clearReceiverNickname();
      return this;
    }
    /**
     * <pre>
     * receiver nickname
     * </pre>
     *
     * <code>string receiver_nickname = 5;</code>
     * @param value The bytes for receiverNickname to set.
     * @return This builder for chaining.
     */
    public Builder setReceiverNicknameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setReceiverNicknameBytes(value);
      return this;
    }

    /**
     * <pre>
     * message content
     * </pre>
     *
     * <code>string content = 6;</code>
     * @return The content.
     */
    @java.lang.Override
    public java.lang.String getContent() {
      return instance.getContent();
    }
    /**
     * <pre>
     * message content
     * </pre>
     *
     * <code>string content = 6;</code>
     * @return The bytes for content.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getContentBytes() {
      return instance.getContentBytes();
    }
    /**
     * <pre>
     * message content
     * </pre>
     *
     * <code>string content = 6;</code>
     * @param value The content to set.
     * @return This builder for chaining.
     */
    public Builder setContent(
        java.lang.String value) {
      copyOnWrite();
      instance.setContent(value);
      return this;
    }
    /**
     * <pre>
     * message content
     * </pre>
     *
     * <code>string content = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearContent() {
      copyOnWrite();
      instance.clearContent();
      return this;
    }
    /**
     * <pre>
     * message content
     * </pre>
     *
     * <code>string content = 6;</code>
     * @param value The bytes for content to set.
     * @return This builder for chaining.
     */
    public Builder setContentBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setContentBytes(value);
      return this;
    }

    /**
     * <pre>
     * timestamp when the message was sent
     * </pre>
     *
     * <code>int64 sent_at = 7;</code>
     * @return The sentAt.
     */
    @java.lang.Override
    public long getSentAt() {
      return instance.getSentAt();
    }
    /**
     * <pre>
     * timestamp when the message was sent
     * </pre>
     *
     * <code>int64 sent_at = 7;</code>
     * @param value The sentAt to set.
     * @return This builder for chaining.
     */
    public Builder setSentAt(long value) {
      copyOnWrite();
      instance.setSentAt(value);
      return this;
    }
    /**
     * <pre>
     * timestamp when the message was sent
     * </pre>
     *
     * <code>int64 sent_at = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearSentAt() {
      copyOnWrite();
      instance.clearSentAt();
      return this;
    }

    /**
     * <pre>
     * forward target selected by sender (optional)
     * </pre>
     *
     * <code>.agentassistproto.ForwardTarget forward_target = 8;</code>
     */
    @java.lang.Override
    public boolean hasForwardTarget() {
      return instance.hasForwardTarget();
    }
    /**
     * <pre>
     * forward target selected by sender (optional)
     * </pre>
     *
     * <code>.agentassistproto.ForwardTarget forward_target = 8;</code>
     */
    @java.lang.Override
    public code.agentassistant.flutter.flutterclient.proto.ForwardTarget getForwardTarget() {
      return instance.getForwardTarget();
    }
    /**
     * <pre>
     * forward target selected by sender (optional)
     * </pre>
     *
     * <code>.agentassistproto.ForwardTarget forward_target = 8;</code>
     */
    public Builder setForwardTarget(code.agentassistant.flutter.flutterclient.proto.ForwardTarget value) {
      copyOnWrite();
      instance.setForwardTarget(value);
      return this;
      }
    /**
     * <pre>
     * forward target selected by sender (optional)
     * </pre>
     *
     * <code>.agentassistproto.ForwardTarget forward_target = 8;</code>
     */
    public Builder setForwardTarget(
        code.agentassistant.flutter.flutterclient.proto.ForwardTarget.Builder builderForValue) {
      copyOnWrite();
      instance.setForwardTarget(builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * forward target selected by sender (optional)
     * </pre>
     *
     * <code>.agentassistproto.ForwardTarget forward_target = 8;</code>
     */
    public Builder mergeForwardTarget(code.agentassistant.flutter.flutterclient.proto.ForwardTarget value) {
      copyOnWrite();
      instance.mergeForwardTarget(value);
      return this;
    }
    /**
     * <pre>
     * forward target selected by sender (optional)
     * </pre>
     *
     * <code>.agentassistproto.ForwardTarget forward_target = 8;</code>
     */
    public Builder clearForwardTarget() {  copyOnWrite();
      instance.clearForwardTarget();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:agentassistproto.ChatMessage)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new code.agentassistant.flutter.flutterclient.proto.ChatMessage();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "messageId_",
            "senderClientId_",
            "senderNickname_",
            "receiverClientId_",
            "receiverNickname_",
            "content_",
            "sentAt_",
            "forwardTarget_",
          };
          java.lang.String info =
              "\u0000\b\u0000\u0001\u0001\b\b\u0000\u0000\u0000\u0001\u0208\u0002\u0208\u0003\u0208" +
              "\u0004\u0208\u0005\u0208\u0006\u0208\u0007\u0002\b\u1009\u0000";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<code.agentassistant.flutter.flutterclient.proto.ChatMessage> parser = PARSER;
        if (parser == null) {
          synchronized (code.agentassistant.flutter.flutterclient.proto.ChatMessage.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<code.agentassistant.flutter.flutterclient.proto.ChatMessage>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:agentassistproto.ChatMessage)
  private static final code.agentassistant.flutter.flutterclient.proto.ChatMessage DEFAULT_INSTANCE;
  static {
    ChatMessage defaultInstance = new ChatMessage();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      ChatMessage.class, defaultInstance);
  }

  public static code.agentassistant.flutter.flutterclient.proto.ChatMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ChatMessage> PARSER;

  public static com.google.protobuf.Parser<ChatMessage> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

