// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agentassist.proto
// Protobuf Java Version: 4.36.0

package code.agentassistant.flutter.flutterclient.proto;

/**
 * <pre>
 * ChatMessageNotification represents a notification of a new chat message
 * </pre>
 *
 * Protobuf type {@code agentassistproto.ChatMessageNotification}
 */
@com.google.protobuf.Generated
public  final class ChatMessageNotification extends
    com.google.protobuf.GeneratedMessageLite<
        ChatMessageNotification, ChatMessageNotification.Builder> implements
    // @@protoc_insertion_point(message_implements:agentassistproto.ChatMessageNotification)
    ChatMessageNotificationOrBuilder {
  private ChatMessageNotification() {
  }
  private int bitField0_;
  public static final int CHAT_MESSAGE_FIELD_NUMBER = 1;
  private code.agentassistant.flutter.flutterclient.proto.ChatMessage chatMessage_;
  /**
   * <pre>
   * the chat message
   * </pre>
   *
   * <code>.agentassistproto.ChatMessage chat_message = 1;</code>
   */
  @java.lang.Override
  public boolean hasChatMessage() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * the chat message
   * </pre>
   *
   * <code>.agentassistproto.ChatMessage chat_message = 1;</code>
   */
  @java.lang.Override
  public code.agentassistant.flutter.flutterclient.proto.ChatMessage getChatMessage() {
    return chatMessage_ == null ? code.agentassistant.flutter.flutterclient.proto.ChatMessage.getDefaultInstance() : chatMessage_;
  }
  /**
   * <pre>
   * the chat message
   * </pre>
   *
   * <code>.agentassistproto.ChatMessage chat_message = 1;</code>
   */
  private void setChatMessage(code.agentassistant.flutter.flutterclient.proto.ChatMessage value) {
    java.util.Objects.requireNonNull(value);
    chatMessage_ = value;
    bitField0_ |= 0x00000001;
  }
  /**
   * <pre>
   * the chat message
   * </pre>
   *
   * <code>.agentassistproto.ChatMessage chat_message = 1;</code>
   */
  @java.lang.SuppressWarnings("ReferenceEquality")
  private void mergeChatMessage(code.agentassistant.flutter.flutterclient.proto.ChatMessage value) {
    java.util.Objects.requireNonNull(value);
    if (chatMessage_ != null &&
        chatMessage_ != code.agentassistant.flutter.flutterclient.proto.ChatMessage.getDefaultInstance()) {
      chatMessage_ =
        code.agentassistant.flutter.flutterclient.proto.ChatMessage.newBuilder(chatMessage_).mergeFrom(value).buildPartial();
    } else {
      chatMessage_ = value;
    }
    bitField0_ |= 0x00000001;
  }
  /**
   * <pre>
   * the chat message
   * </pre>
   *
   * <code>.agentassistproto.ChatMessage chat_message = 1;</code>
   */
  private void clearChatMessage() {
    chatMessage_ = null;
    bitField0_ = (bitField0_ & ~0x00000001);
  }

  public static code.agentassistant.flutter.flutterclient.proto.ChatMessageNotification parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static code.agentassistant.flutter.flutterclient.proto.ChatMessageNotification parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static code.agentassistant.flutter.flutterclient.proto.ChatMessageNotification parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static code.agentassistant.flutter.flutterclient.proto.ChatMessageNotification parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static code.agentassistant.flutter.flutterclient.proto.ChatMessageNotification parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static code.agentassistant.flutter.flutterclient.proto.ChatMessageNotification parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static code.agentassistant.flutter.flutterclient.proto.ChatMessageNotification parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static code.agentassistant.flutter.flutterclient.proto.ChatMessageNotification parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static code.agentassistant.flutter.flutterclient.proto.ChatMessageNotification parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static code.agentassistant.flutter.flutterclient.proto.ChatMessageNotification parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static code.agentassistant.flutter.flutterclient.proto.ChatMessageNotification parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static code.agentassistant.flutter.flutterclient.proto.ChatMessageNotification parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(code.agentassistant.flutter.flutterclient.proto.ChatMessageNotification prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * ChatMessageNotification represents a notification of a new chat message
   * </pre>
   *
   * Protobuf type {@code agentassistproto.ChatMessageNotification}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        code.agentassistant.flutter.flutterclient.proto.ChatMessageNotification, Builder> implements
      // @@protoc_insertion_point(builder_implements:agentassistproto.ChatMessageNotification)
      code.agentassistant.flutter.flutterclient.proto.ChatMessageNotificationOrBuilder {
    // Construct using code.agentassistant.flutter.flutterclient.proto.ChatMessageNotification.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * the chat message
     * </pre>
     *
     * <code>.agentassistproto.ChatMessage chat_message = 1;</code>
     */
    @java.lang.Override
    public boolean hasChatMessage() {
      return instance.hasChatMessage();
    }
    /**
     * <pre>
     * the chat message
     * </pre>
     *
     * <code>.agentassistproto.ChatMessage chat_message = 1;</code>
     */
    @java.lang.Override
    public code.agentassistant.flutter.flutterclient.proto.ChatMessage getChatMessage() {
      return instance.getChatMessage();
    }
    /**
     * <pre>
     * the chat message
     * </pre>
     *
     * <code>.agentassistproto.ChatMessage chat_message = 1;</code>
     */
    public Builder setChatMessage(code.agentassistant.flutter.flutterclient.proto.ChatMessage value) {
      copyOnWrite();
      instance.setChatMessage(value);
      return this;
      }
    /**
     * <pre>
     * the chat message
     * </pre>
     *
     * <code>.agentassistproto.ChatMessage chat_message = 1;</code>
     */
    public Builder setChatMessage(
        code.agentassistant.flutter.flutterclient.proto.ChatMessage.Builder builderForValue) {
      copyOnWrite();
      instance.setChatMessage(builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * the chat message
     * </pre>
     *
     * <code>.agentassistproto.ChatMessage chat_message = 1;</code>
     */
    public Builder mergeChatMessage(code.agentassistant.flutter.flutterclient.proto.ChatMessage value) {
      copyOnWrite();
      instance.mergeChatMessage(value);
      return this;
    }
    /**
     * <pre>
     * the chat message
     * </pre>
     *
     * <code>.agentassistproto.ChatMessage chat_message = 1;</code>
     */
    public Builder clearChatMessage() {  copyOnWrite();
      instance.clearChatMessage();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:agentassistproto.ChatMessageNotification)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new code.agentassistant.flutter.flutterclient.proto.ChatMessageNotification();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "chatMessage_",
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0001\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u1009\u0000";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<code.agentassistant.flutter.flutterclient.proto.ChatMessageNotification> parser = PARSER;
        if (parser == null) {
          synchronized (code.agentassistant.flutter.flutterclient.proto.ChatMessageNotification.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<code.agentassistant.flutter.flutterclient.proto.ChatMessageNotification>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:agentassistproto.ChatMessageNotification)
  private static final code.agentassistant.flutter.flutterclient.proto.ChatMessageNotification DEFAULT_INSTANCE;
  static {
    ChatMessageNotification defaultInstance = new ChatMessageNotification();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      ChatMessageNotification.class, defaultInstance);
  }

  public static code.agentassistant.flutter.flutterclient.proto.ChatMessageNotification getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ChatMessageNotification> PARSER;

  public static com.google.protobuf.Parser<ChatMessageNotification> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

