// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agentassist.proto
// Protobuf Java Version: 4.36.0

package code.agentassistant.flutter.flutterclient.proto;

/**
 * Protobuf type {@code agentassistproto.CheckMessageValidityResponse}
 */
@com.google.protobuf.Generated
public  final class CheckMessageValidityResponse extends
    com.google.protobuf.GeneratedMessageLite<
        CheckMessageValidityResponse, CheckMessageValidityResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:agentassistproto.CheckMessageValidityResponse)
    CheckMessageValidityResponseOrBuilder {
  private CheckMessageValidityResponse() {
  }
  public static final int VALIDITY_FIELD_NUMBER = 1;
  private static final class ValidityDefaultEntryHolder {
    static final com.google.protobuf.MapEntryLite<
        java.lang.String, java.lang.Boolean> defaultEntry =
            com.google.protobuf.MapEntryLite
            .<java.lang.String, java.lang.Boolean>newDefaultInstance(
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.BOOL,
                false);
  }
  private com.google.protobuf.MapFieldLite<
      java.lang.String, java.lang.Boolean> validity_ =
          com.google.protobuf.MapFieldLite.emptyMapField();
  private com.google.protobuf.MapFieldLite<java.lang.String, java.lang.Boolean>
  internalGetValidity() {
    return validity_;
  }
  private com.google.protobuf.MapFieldLite<java.lang.String, java.lang.Boolean>
  internalGetMutableValidity() {
    if (!validity_.isMutable()) {
      validity_ = validity_.mutableCopy();
    }
    return validity_;
  }
  @java.lang.Override

  public int getValidityCount() {
    return internalGetValidity().size();
  }
  /**
   * <pre>
   * map of request ID to validity status
   * </pre>
   *
   * <code>map&lt;string, bool&gt; validity = 1;</code>
   */
  @java.lang.Override

  public boolean containsValidity(
      java.lang.String key) {
    java.util.Objects.requireNonNull(key);
    return internalGetValidity().containsKey(key);
  }
  /**
   * Use {@link #getValidityMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.Boolean> getValidity() {
    return getValidityMap();
  }
  /**
   * <pre>
   * map of request ID to validity status
   * </pre>
   *
   * <code>map&lt;string, bool&gt; validity = 1;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.String, java.lang.Boolean> getValidityMap() {
    return java.util.Collections.unmodifiableMap(
        internalGetValidity());
  }
  /**
   * <pre>
   * map of request ID to validity status
   * </pre>
   *
   * <code>map&lt;string, bool&gt; validity = 1;</code>
   */
  @java.lang.Override

  public boolean getValidityOrDefault(
      java.lang.String key,
      boolean defaultValue) {
    java.util.Objects.requireNonNull(key);
    java.util.Map<java.lang.String, java.lang.Boolean> map =
        internalGetValidity();
    java.lang.Boolean v = map.get(key);
    return v != null ? v : defaultValue;
  }
  /**
   * <pre>
   * map of request ID to validity status
   * </pre>
   *
   * <code>map&lt;string, bool&gt; validity = 1;</code>
   */
  @java.lang.Override

  public boolean getValidityOrThrow(
      java.lang.String key) {
    java.util.Objects.requireNonNull(key);
    java.util.Map<java.lang.String, java.lang.Boolean> map =
        internalGetValidity();
    java.lang.Boolean v = map.get(key);
    if (v == null) {
      throw new java.lang.IllegalArgumentException();
    }
    return v;
  }
  /**
   * <pre>
   * map of request ID to validity status
   * </pre>
   *
   * <code>map&lt;string, bool&gt; validity = 1;</code>
   */
  private java.util.Map<java.lang.String, java.lang.Boolean>
  getMutableValidityMap() {
    return internalGetMutableValidity();
  }

  public static code.agentassistant.flutter.flutterclient.proto.CheckMessageValidityResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static code.agentassistant.flutter.flutterclient.proto.CheckMessageValidityResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static code.agentassistant.flutter.flutterclient.proto.CheckMessageValidityResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static code.agentassistant.flutter.flutterclient.proto.CheckMessageValidityResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static code.agentassistant.flutter.flutterclient.proto.CheckMessageValidityResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static code.agentassistant.flutter.flutterclient.proto.CheckMessageValidityResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static code.agentassistant.flutter.flutterclient.proto.CheckMessageValidityResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static code.agentassistant.flutter.flutterclient.proto.CheckMessageValidityResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static code.agentassistant.flutter.flutterclient.proto.CheckMessageValidityResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static code.agentassistant.flutter.flutterclient.proto.CheckMessageValidityResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static code.agentassistant.flutter.flutterclient.proto.CheckMessageValidityResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static code.agentassistant.flutter.flutterclient.proto.CheckMessageValidityResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(code.agentassistant.flutter.flutterclient.proto.CheckMessageValidityResponse prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code agentassistproto.CheckMessageValidityResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        code.agentassistant.flutter.flutterclient.proto.CheckMessageValidityResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:agentassistproto.CheckMessageValidityResponse)
      code.agentassistant.flutter.flutterclient.proto.CheckMessageValidityResponseOrBuilder {
    // Construct using code.agentassistant.flutter.flutterclient.proto.CheckMessageValidityResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    @java.lang.Override

    public int getValidityCount() {
      return instance.getValidityMap().size();
    }
    /**
     * <pre>
     * map of request ID to validity status
     * </pre>
     *
     * <code>map&lt;string, bool&gt; validity = 1;</code>
     */
    @java.lang.Override

    public boolean containsValidity(
        java.lang.String key) {
      java.util.Objects.requireNonNull(key);
      return instance.getValidityMap().containsKey(key);
    }

    public Builder clearValidity() {
      copyOnWrite();
      instance.getMutableValidityMap().clear();
      return this;
    }
    /**
     * <pre>
     * map of request ID to validity status
     * </pre>
     *
     * <code>map&lt;string, bool&gt; validity = 1;</code>
     */

    public Builder removeValidity(
        java.lang.String key) {
      java.util.Objects.requireNonNull(key);
      copyOnWrite();
      instance.getMutableValidityMap().remove(key);
      return this;
    }
    /**
     * Use {@link #getValidityMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Boolean> getValidity() {
      return getValidityMap();
    }
    /**
     * <pre>
     * map of request ID to validity status
     * </pre>
     *
     * <code>map&lt;string, bool&gt; validity = 1;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.Boolean> getValidityMap() {
      return java.util.Collections.unmodifiableMap(
          instance.getValidityMap());
    }
    /**
     * <pre>
     * map of request ID to validity status
     * </pre>
     *
     * <code>map&lt;string, bool&gt; validity = 1;</code>
     */
    @java.lang.Override

    public boolean getValidityOrDefault(
        java.lang.String key,
        boolean defaultValue) {
      java.util.Objects.requireNonNull(key);
      java.util.Map<java.lang.String, java.lang.Boolean> map =
          instance.getValidityMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * map of request ID to validity status
     * </pre>
     *
     * <code>map&lt;string, bool&gt; validity = 1;</code>
     */
    @java.lang.Override

    public boolean getValidityOrThrow(
        java.lang.String key) {
      java.util.Objects.requireNonNull(key);
      java.util.Map<java.lang.String, java.lang.Boolean> map =
          instance.getValidityMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    /**
     * <pre>
     * map of request ID to validity status
     * </pre>
     *
     * <code>map&lt;string, bool&gt; validity = 1;</code>
     */
    public Builder putValidity(
        java.lang.String key,
        boolean value) {
      java.util.Objects.requireNonNull(key);

      copyOnWrite();
      instance.getMutableValidityMap().put(key, value);
      return this;
    }
    /**
     * <pre>
     * map of request ID to validity status
     * </pre>
     *
     * <code>map&lt;string, bool&gt; validity = 1;</code>
     */
    public Builder putAllValidity(
        java.util.Map<java.lang.String, java.lang.Boolean> values) {
      copyOnWrite();
      instance.getMutableValidityMap().putAll(values);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:agentassistproto.CheckMessageValidityResponse)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new code.agentassistant.flutter.flutterclient.proto.CheckMessageValidityResponse();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "validity_",
            ValidityDefaultEntryHolder.defaultEntry,
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0001\u0000\u0000\u00012";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<code.agentassistant.flutter.flutterclient.proto.CheckMessageValidityResponse> parser = PARSER;
        if (parser == null) {
          synchronized (code.agentassistant.flutter.flutterclient.proto.CheckMessageValidityResponse.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<code.agentassistant.flutter.flutterclient.proto.CheckMessageValidityResponse>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:agentassistproto.CheckMessageValidityResponse)
  private static final code.agentassistant.flutter.flutterclient.proto.CheckMessageValidityResponse DEFAULT_INSTANCE;
  static {
    CheckMessageValidityResponse defaultInstance = new CheckMessageValidityResponse();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      CheckMessageValidityResponse.class, defaultInstance);
  }

  public static code.agentassistant.flutter.flutterclient.proto.CheckMessageValidityResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<CheckMessageValidityResponse> PARSER;

  public static com.google.protobuf.Parser<CheckMessageValidityResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

