// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agentassist.proto
// Protobuf Java Version: 4.36.0

package code.agentassistant.flutter.flutterclient.proto;

/**
 * Protobuf type {@code agentassistproto.CheckMessageValidityRequest}
 */
@com.google.protobuf.Generated
public  final class CheckMessageValidityRequest extends
    com.google.protobuf.GeneratedMessageLite<
        CheckMessageValidityRequest, CheckMessageValidityRequest.Builder> implements
    // @@protoc_insertion_point(message_implements:agentassistproto.CheckMessageValidityRequest)
    CheckMessageValidityRequestOrBuilder {
  private CheckMessageValidityRequest() {
    requestIds_ = emptyProtobufList();
  }
  public static final int REQUEST_IDS_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.ProtobufList<java.lang.String> requestIds_;
  /**
   * <pre>
   * list of request IDs to check
   * </pre>
   *
   * <code>repeated string request_ids = 1;</code>
   * @return A list containing the requestIds.
   */
  @java.lang.Override
  public java.util.List<java.lang.String> getRequestIdsList() {
    return requestIds_;
  }
  /**
   * <pre>
   * list of request IDs to check
   * </pre>
   *
   * <code>repeated string request_ids = 1;</code>
   * @return The count of requestIds.
   */
  @java.lang.Override
  public int getRequestIdsCount() {
    return requestIds_.size();
  }
  /**
   * <pre>
   * list of request IDs to check
   * </pre>
   *
   * <code>repeated string request_ids = 1;</code>
   * @param index The index of the element to return.
   * @return The requestIds at the given index.
   */
  @java.lang.Override
  public java.lang.String getRequestIds(int index) {
    return requestIds_.get(index);
  }
  /**
   * <pre>
   * list of request IDs to check
   * </pre>
   *
   * <code>repeated string request_ids = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the requestIds at the given index.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRequestIdsBytes(int index) {
    return com.google.protobuf.ByteString.copyFromUtf8(
        requestIds_.get(index));
  }
  private void ensureRequestIdsIsMutable() {
    com.google.protobuf.Internal.ProtobufList<java.lang.String> tmp =
        requestIds_;  if (!tmp.isModifiable()) {
      requestIds_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }
  /**
   * <pre>
   * list of request IDs to check
   * </pre>
   *
   * <code>repeated string request_ids = 1;</code>
   * @param index The index to set the value at.
   * @param value The requestIds to set.
   */
  private void setRequestIds(
      int index, java.lang.String value) {
    java.util.Objects.requireNonNull(value);
    ensureRequestIdsIsMutable();
    requestIds_.set(index, value);
  }
  /**
   * <pre>
   * list of request IDs to check
   * </pre>
   *
   * <code>repeated string request_ids = 1;</code>
   * @param value The requestIds to add.
   */
  private void addRequestIds(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);
    ensureRequestIdsIsMutable();
    requestIds_.add(value);
  }
  /**
   * <pre>
   * list of request IDs to check
   * </pre>
   *
   * <code>repeated string request_ids = 1;</code>
   * @param values The requestIds to add.
   */
  private void addAllRequestIds(
      java.lang.Iterable<java.lang.String> values) {
    ensureRequestIdsIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, requestIds_);
  }
  /**
   * <pre>
   * list of request IDs to check
   * </pre>
   *
   * <code>repeated string request_ids = 1;</code>
   */
  private void clearRequestIds() {
    requestIds_ = emptyProtobufList();
  }
  /**
   * <pre>
   * list of request IDs to check
   * </pre>
   *
   * <code>repeated string request_ids = 1;</code>
   * @param value The bytes of the requestIds to add.
   */
  private void addRequestIdsBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    ensureRequestIdsIsMutable();
    requestIds_.add(value.toStringUtf8());
  }

  public static code.agentassistant.flutter.flutterclient.proto.CheckMessageValidityRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static code.agentassistant.flutter.flutterclient.proto.CheckMessageValidityRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static code.agentassistant.flutter.flutterclient.proto.CheckMessageValidityRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static code.agentassistant.flutter.flutterclient.proto.CheckMessageValidityRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static code.agentassistant.flutter.flutterclient.proto.CheckMessageValidityRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static code.agentassistant.flutter.flutterclient.proto.CheckMessageValidityRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static code.agentassistant.flutter.flutterclient.proto.CheckMessageValidityRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static code.agentassistant.flutter.flutterclient.proto.CheckMessageValidityRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static code.agentassistant.flutter.flutterclient.proto.CheckMessageValidityRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static code.agentassistant.flutter.flutterclient.proto.CheckMessageValidityRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static code.agentassistant.flutter.flutterclient.proto.CheckMessageValidityRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static code.agentassistant.flutter.flutterclient.proto.CheckMessageValidityRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(code.agentassistant.flutter.flutterclient.proto.CheckMessageValidityRequest prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code agentassistproto.CheckMessageValidityRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        code.agentassistant.flutter.flutterclient.proto.CheckMessageValidityRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:agentassistproto.CheckMessageValidityRequest)
      code.agentassistant.flutter.flutterclient.proto.CheckMessageValidityRequestOrBuilder {
    // Construct using code.agentassistant.flutter.flutterclient.proto.CheckMessageValidityRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * list of request IDs to check
     * </pre>
     *
     * <code>repeated string request_ids = 1;</code>
     * @return A list containing the requestIds.
     */
    @java.lang.Override
    public java.util.List<java.lang.String>
        getRequestIdsList() {
      return java.util.Collections.unmodifiableList(
          instance.getRequestIdsList());
    }
    /**
     * <pre>
     * list of request IDs to check
     * </pre>
     *
     * <code>repeated string request_ids = 1;</code>
     * @return The count of requestIds.
     */
    @java.lang.Override
    public int getRequestIdsCount() {
      return instance.getRequestIdsCount();
    }
    /**
     * <pre>
     * list of request IDs to check
     * </pre>
     *
     * <code>repeated string request_ids = 1;</code>
     * @param index The index of the element to return.
     * @return The requestIds at the given index.
     */
    @java.lang.Override
    public java.lang.String getRequestIds(int index) {
      return instance.getRequestIds(index);
    }
    /**
     * <pre>
     * list of request IDs to check
     * </pre>
     *
     * <code>repeated string request_ids = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the requestIds at the given index.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRequestIdsBytes(int index) {
      return instance.getRequestIdsBytes(index);
    }
    /**
     * <pre>
     * list of request IDs to check
     * </pre>
     *
     * <code>repeated string request_ids = 1;</code>
     * @param index The index to set the value at.
     * @param value The requestIds to set.
     * @return This builder for chaining.
     */
    public Builder setRequestIds(
        int index, java.lang.String value) {
      copyOnWrite();
      instance.setRequestIds(index, value);
      return this;
    }
    /**
     * <pre>
     * list of request IDs to check
     * </pre>
     *
     * <code>repeated string request_ids = 1;</code>
     * @param value The requestIds to add.
     * @return This builder for chaining.
     */
    public Builder addRequestIds(
        java.lang.String value) {
      copyOnWrite();
      instance.addRequestIds(value);
      return this;
    }
    /**
     * <pre>
     * list of request IDs to check
     * </pre>
     *
     * <code>repeated string request_ids = 1;</code>
     * @param values The requestIds to add.
     * @return This builder for chaining.
     */
    public Builder addAllRequestIds(
        java.lang.Iterable<java.lang.String> values) {
      copyOnWrite();
      instance.addAllRequestIds(values);
      return this;
    }
    /**
     * <pre>
     * list of request IDs to check
     * </pre>
     *
     * <code>repeated string request_ids = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRequestIds() {
      copyOnWrite();
      instance.clearRequestIds();
      return this;
    }
    /**
     * <pre>
     * list of request IDs to check
     * </pre>
     *
     * <code>repeated string request_ids = 1;</code>
     * @param value The bytes of the requestIds to add.
     * @return This builder for chaining.
     */
    public Builder addRequestIdsBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.addRequestIdsBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:agentassistproto.CheckMessageValidityRequest)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new code.agentassistant.flutter.flutterclient.proto.CheckMessageValidityRequest();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "requestIds_",
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0001\u0000\u0001\u021a";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<code.agentassistant.flutter.flutterclient.proto.CheckMessageValidityRequest> parser = PARSER;
        if (parser == null) {
          synchronized (code.agentassistant.flutter.flutterclient.proto.CheckMessageValidityRequest.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<code.agentassistant.flutter.flutterclient.proto.CheckMessageValidityRequest>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:agentassistproto.CheckMessageValidityRequest)
  private static final code.agentassistant.flutter.flutterclient.proto.CheckMessageValidityRequest DEFAULT_INSTANCE;
  static {
    CheckMessageValidityRequest defaultInstance = new CheckMessageValidityRequest();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      CheckMessageValidityRequest.class, defaultInstance);
  }

  public static code.agentassistant.flutter.flutterclient.proto.CheckMessageValidityRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<CheckMessageValidityRequest> PARSER;

  public static com.google.protobuf.Parser<CheckMessageValidityRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

