// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agentassist.proto
// Protobuf Java Version: 4.36.0

package code.agentassistant.flutter.flutterclient.proto;

/**
 * <pre>
 * EmbeddedResource represents a resource embedded into a prompt or tool call
 * result. It must have Type set to "embedded_resource".
 * </pre>
 *
 * Protobuf type {@code agentassistproto.EmbeddedResource}
 */
@com.google.protobuf.Generated
public  final class EmbeddedResource extends
    com.google.protobuf.GeneratedMessageLite<
        EmbeddedResource, EmbeddedResource.Builder> implements
    // @@protoc_insertion_point(message_implements:agentassistproto.EmbeddedResource)
    EmbeddedResourceOrBuilder {
  private EmbeddedResource() {
    type_ = "";
    uri_ = "";
    mimeType_ = "";
    data_ = com.google.protobuf.ByteString.EMPTY;
  }
  public static final int TYPE_FIELD_NUMBER = 1;
  private java.lang.String type_;
  /**
   * <pre>
   * Must be "embedded_resource"
   * </pre>
   *
   * <code>string type = 1;</code>
   * @return The type.
   */
  @java.lang.Override
  public java.lang.String getType() {
    return type_;
  }
  /**
   * <pre>
   * Must be "embedded_resource"
   * </pre>
   *
   * <code>string type = 1;</code>
   * @return The bytes for type.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTypeBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(type_);
  }
  /**
   * <pre>
   * Must be "embedded_resource"
   * </pre>
   *
   * <code>string type = 1;</code>
   * @param value The type to set.
   */
  private void setType(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    type_ = value;
  }
  /**
   * <pre>
   * Must be "embedded_resource"
   * </pre>
   *
   * <code>string type = 1;</code>
   */
  private void clearType() {

    type_ = getDefaultInstance().getType();
  }
  /**
   * <pre>
   * Must be "embedded_resource"
   * </pre>
   *
   * <code>string type = 1;</code>
   * @param value The bytes for type to set.
   */
  private void setTypeBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    type_ = value.toStringUtf8();

  }

  public static final int URI_FIELD_NUMBER = 2;
  private java.lang.String uri_;
  /**
   * <pre>
   * URI of the embedded resource
   * </pre>
   *
   * <code>string uri = 2;</code>
   * @return The uri.
   */
  @java.lang.Override
  public java.lang.String getUri() {
    return uri_;
  }
  /**
   * <pre>
   * URI of the embedded resource
   * </pre>
   *
   * <code>string uri = 2;</code>
   * @return The bytes for uri.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUriBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(uri_);
  }
  /**
   * <pre>
   * URI of the embedded resource
   * </pre>
   *
   * <code>string uri = 2;</code>
   * @param value The uri to set.
   */
  private void setUri(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    uri_ = value;
  }
  /**
   * <pre>
   * URI of the embedded resource
   * </pre>
   *
   * <code>string uri = 2;</code>
   */
  private void clearUri() {

    uri_ = getDefaultInstance().getUri();
  }
  /**
   * <pre>
   * URI of the embedded resource
   * </pre>
   *
   * <code>string uri = 2;</code>
   * @param value The bytes for uri to set.
   */
  private void setUriBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    uri_ = value.toStringUtf8();

  }

  public static final int MIME_TYPE_FIELD_NUMBER = 3;
  private java.lang.String mimeType_;
  /**
   * <pre>
   * MIME type of the resource
   * </pre>
   *
   * <code>string mime_type = 3;</code>
   * @return The mimeType.
   */
  @java.lang.Override
  public java.lang.String getMimeType() {
    return mimeType_;
  }
  /**
   * <pre>
   * MIME type of the resource
   * </pre>
   *
   * <code>string mime_type = 3;</code>
   * @return The bytes for mimeType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMimeTypeBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(mimeType_);
  }
  /**
   * <pre>
   * MIME type of the resource
   * </pre>
   *
   * <code>string mime_type = 3;</code>
   * @param value The mimeType to set.
   */
  private void setMimeType(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    mimeType_ = value;
  }
  /**
   * <pre>
   * MIME type of the resource
   * </pre>
   *
   * <code>string mime_type = 3;</code>
   */
  private void clearMimeType() {

    mimeType_ = getDefaultInstance().getMimeType();
  }
  /**
   * <pre>
   * MIME type of the resource
   * </pre>
   *
   * <code>string mime_type = 3;</code>
   * @param value The bytes for mimeType to set.
   */
  private void setMimeTypeBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    mimeType_ = value.toStringUtf8();

  }

  public static final int DATA_FIELD_NUMBER = 4;
  private com.google.protobuf.ByteString data_;
  /**
   * <pre>
   * Optional: The actual resource data
   * </pre>
   *
   * <code>bytes data = 4;</code>
   * @return The data.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getData() {
    return data_;
  }
  /**
   * <pre>
   * Optional: The actual resource data
   * </pre>
   *
   * <code>bytes data = 4;</code>
   * @param value The data to set.
   */
  private void setData(com.google.protobuf.ByteString value) {
    java.util.Objects.requireNonNull(value);
  
    data_ = value;
  }
  /**
   * <pre>
   * Optional: The actual resource data
   * </pre>
   *
   * <code>bytes data = 4;</code>
   */
  private void clearData() {

    data_ = getDefaultInstance().getData();
  }

  public static code.agentassistant.flutter.flutterclient.proto.EmbeddedResource parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static code.agentassistant.flutter.flutterclient.proto.EmbeddedResource parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static code.agentassistant.flutter.flutterclient.proto.EmbeddedResource parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static code.agentassistant.flutter.flutterclient.proto.EmbeddedResource parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static code.agentassistant.flutter.flutterclient.proto.EmbeddedResource parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static code.agentassistant.flutter.flutterclient.proto.EmbeddedResource parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static code.agentassistant.flutter.flutterclient.proto.EmbeddedResource parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static code.agentassistant.flutter.flutterclient.proto.EmbeddedResource parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static code.agentassistant.flutter.flutterclient.proto.EmbeddedResource parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static code.agentassistant.flutter.flutterclient.proto.EmbeddedResource parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static code.agentassistant.flutter.flutterclient.proto.EmbeddedResource parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static code.agentassistant.flutter.flutterclient.proto.EmbeddedResource parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(code.agentassistant.flutter.flutterclient.proto.EmbeddedResource prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * EmbeddedResource represents a resource embedded into a prompt or tool call
   * result. It must have Type set to "embedded_resource".
   * </pre>
   *
   * Protobuf type {@code agentassistproto.EmbeddedResource}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        code.agentassistant.flutter.flutterclient.proto.EmbeddedResource, Builder> implements
      // @@protoc_insertion_point(builder_implements:agentassistproto.EmbeddedResource)
      code.agentassistant.flutter.flutterclient.proto.EmbeddedResourceOrBuilder {
    // Construct using code.agentassistant.flutter.flutterclient.proto.EmbeddedResource.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * Must be "embedded_resource"
     * </pre>
     *
     * <code>string type = 1;</code>
     * @return The type.
     */
    @java.lang.Override
    public java.lang.String getType() {
      return instance.getType();
    }
    /**
     * <pre>
     * Must be "embedded_resource"
     * </pre>
     *
     * <code>string type = 1;</code>
     * @return The bytes for type.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTypeBytes() {
      return instance.getTypeBytes();
    }
    /**
     * <pre>
     * Must be "embedded_resource"
     * </pre>
     *
     * <code>string type = 1;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(
        java.lang.String value) {
      copyOnWrite();
      instance.setType(value);
      return this;
    }
    /**
     * <pre>
     * Must be "embedded_resource"
     * </pre>
     *
     * <code>string type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      copyOnWrite();
      instance.clearType();
      return this;
    }
    /**
     * <pre>
     * Must be "embedded_resource"
     * </pre>
     *
     * <code>string type = 1;</code>
     * @param value The bytes for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setTypeBytes(value);
      return this;
    }

    /**
     * <pre>
     * URI of the embedded resource
     * </pre>
     *
     * <code>string uri = 2;</code>
     * @return The uri.
     */
    @java.lang.Override
    public java.lang.String getUri() {
      return instance.getUri();
    }
    /**
     * <pre>
     * URI of the embedded resource
     * </pre>
     *
     * <code>string uri = 2;</code>
     * @return The bytes for uri.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUriBytes() {
      return instance.getUriBytes();
    }
    /**
     * <pre>
     * URI of the embedded resource
     * </pre>
     *
     * <code>string uri = 2;</code>
     * @param value The uri to set.
     * @return This builder for chaining.
     */
    public Builder setUri(
        java.lang.String value) {
      copyOnWrite();
      instance.setUri(value);
      return this;
    }
    /**
     * <pre>
     * URI of the embedded resource
     * </pre>
     *
     * <code>string uri = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearUri() {
      copyOnWrite();
      instance.clearUri();
      return this;
    }
    /**
     * <pre>
     * URI of the embedded resource
     * </pre>
     *
     * <code>string uri = 2;</code>
     * @param value The bytes for uri to set.
     * @return This builder for chaining.
     */
    public Builder setUriBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setUriBytes(value);
      return this;
    }

    /**
     * <pre>
     * MIME type of the resource
     * </pre>
     *
     * <code>string mime_type = 3;</code>
     * @return The mimeType.
     */
    @java.lang.Override
    public java.lang.String getMimeType() {
      return instance.getMimeType();
    }
    /**
     * <pre>
     * MIME type of the resource
     * </pre>
     *
     * <code>string mime_type = 3;</code>
     * @return The bytes for mimeType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMimeTypeBytes() {
      return instance.getMimeTypeBytes();
    }
    /**
     * <pre>
     * MIME type of the resource
     * </pre>
     *
     * <code>string mime_type = 3;</code>
     * @param value The mimeType to set.
     * @return This builder for chaining.
     */
    public Builder setMimeType(
        java.lang.String value) {
      copyOnWrite();
      instance.setMimeType(value);
      return this;
    }
    /**
     * <pre>
     * MIME type of the resource
     * </pre>
     *
     * <code>string mime_type = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearMimeType() {
      copyOnWrite();
      instance.clearMimeType();
      return this;
    }
    /**
     * <pre>
     * MIME type of the resource
     * </pre>
     *
     * <code>string mime_type = 3;</code>
     * @param value The bytes for mimeType to set.
     * @return This builder for chaining.
     */
    public Builder setMimeTypeBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setMimeTypeBytes(value);
      return this;
    }

    /**
     * <pre>
     * Optional: The actual resource data
     * </pre>
     *
     * <code>bytes data = 4;</code>
     * @return The data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getData() {
      return instance.getData();
    }
    /**
     * <pre>
     * Optional: The actual resource data
     * </pre>
     *
     * <code>bytes data = 4;</code>
     * @param value The data to set.
     * @return This builder for chaining.
     */
    public Builder setData(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setData(value);
      return this;
    }
    /**
     * <pre>
     * Optional: The actual resource data
     * </pre>
     *
     * <code>bytes data = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearData() {
      copyOnWrite();
      instance.clearData();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:agentassistproto.EmbeddedResource)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new code.agentassistant.flutter.flutterclient.proto.EmbeddedResource();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "type_",
            "uri_",
            "mimeType_",
            "data_",
          };
          java.lang.String info =
              "\u0000\u0004\u0000\u0000\u0001\u0004\u0004\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
              "\u0003\u0208\u0004\n";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<code.agentassistant.flutter.flutterclient.proto.EmbeddedResource> parser = PARSER;
        if (parser == null) {
          synchronized (code.agentassistant.flutter.flutterclient.proto.EmbeddedResource.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<code.agentassistant.flutter.flutterclient.proto.EmbeddedResource>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:agentassistproto.EmbeddedResource)
  private static final code.agentassistant.flutter.flutterclient.proto.EmbeddedResource DEFAULT_INSTANCE;
  static {
    EmbeddedResource defaultInstance = new EmbeddedResource();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      EmbeddedResource.class, defaultInstance);
  }

  public static code.agentassistant.flutter.flutterclient.proto.EmbeddedResource getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<EmbeddedResource> PARSER;

  public static com.google.protobuf.Parser<EmbeddedResource> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

