// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agentassist.proto
// Protobuf Java Version: 4.36.0

package code.agentassistant.flutter.flutterclient.proto;

@com.google.protobuf.Generated
public interface ForwardStateQueryResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:agentassistproto.ForwardStateQueryResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * request id from ForwardStateQueryRequest
   * </pre>
   *
   * <code>string request_id = 1;</code>
   * @return The requestId.
   */
  java.lang.String getRequestId();
  /**
   * <pre>
   * request id from ForwardStateQueryRequest
   * </pre>
   *
   * <code>string request_id = 1;</code>
   * @return The bytes for requestId.
   */
  com.google.protobuf.ByteString
      getRequestIdBytes();

  /**
   * <pre>
   * response target client id (who should receive this response)
   * </pre>
   *
   * <code>string target_client_id = 2;</code>
   * @return The targetClientId.
   */
  java.lang.String getTargetClientId();
  /**
   * <pre>
   * response target client id (who should receive this response)
   * </pre>
   *
   * <code>string target_client_id = 2;</code>
   * @return The bytes for targetClientId.
   */
  com.google.protobuf.ByteString
      getTargetClientIdBytes();

  /**
   * <pre>
   * responder client id
   * </pre>
   *
   * <code>string responder_client_id = 3;</code>
   * @return The responderClientId.
   */
  java.lang.String getResponderClientId();
  /**
   * <pre>
   * responder client id
   * </pre>
   *
   * <code>string responder_client_id = 3;</code>
   * @return The bytes for responderClientId.
   */
  com.google.protobuf.ByteString
      getResponderClientIdBytes();

  /**
   * <pre>
   * whether responder has enabled auto forward to system input
   * </pre>
   *
   * <code>bool forward_enabled = 4;</code>
   * @return The forwardEnabled.
   */
  boolean getForwardEnabled();

  /**
   * <pre>
   * current forwardable windows
   * </pre>
   *
   * <code>repeated .agentassistproto.ForwardWindowItem windows = 5;</code>
   */
  java.util.List<code.agentassistant.flutter.flutterclient.proto.ForwardWindowItem> 
      getWindowsList();
  /**
   * <pre>
   * current forwardable windows
   * </pre>
   *
   * <code>repeated .agentassistproto.ForwardWindowItem windows = 5;</code>
   */
  code.agentassistant.flutter.flutterclient.proto.ForwardWindowItem getWindows(int index);
  /**
   * <pre>
   * current forwardable windows
   * </pre>
   *
   * <code>repeated .agentassistproto.ForwardWindowItem windows = 5;</code>
   */
  int getWindowsCount();
}
