// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agentassist.proto
// Protobuf Java Version: 4.36.0

package code.agentassistant.flutter.flutterclient.proto;

@com.google.protobuf.Generated
public interface ForwardTargetOrBuilder extends
    // @@protoc_insertion_point(interface_extends:agentassistproto.ForwardTarget)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * forwarding mode
   * </pre>
   *
   * <code>.agentassistproto.ForwardTarget.Mode mode = 1;</code>
   * @return The enum numeric value on the wire for mode.
   */
  int getModeValue();
  /**
   * <pre>
   * forwarding mode
   * </pre>
   *
   * <code>.agentassistproto.ForwardTarget.Mode mode = 1;</code>
   * @return The mode.
   */
  code.agentassistant.flutter.flutterclient.proto.ForwardTarget.Mode getMode();

  /**
   * <pre>
   * target window id when mode is SPECIFIC_WINDOW
   * </pre>
   *
   * <code>string window_id = 2;</code>
   * @return The windowId.
   */
  java.lang.String getWindowId();
  /**
   * <pre>
   * target window id when mode is SPECIFIC_WINDOW
   * </pre>
   *
   * <code>string window_id = 2;</code>
   * @return The bytes for windowId.
   */
  com.google.protobuf.ByteString
      getWindowIdBytes();
}
