// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agentassist.proto
// Protobuf Java Version: 4.36.0

package code.agentassistant.flutter.flutterclient.proto;

/**
 * <pre>
 * ForwardWindowItem describes one forwardable system window
 * </pre>
 *
 * Protobuf type {@code agentassistproto.ForwardWindowItem}
 */
@com.google.protobuf.Generated
public  final class ForwardWindowItem extends
    com.google.protobuf.GeneratedMessageLite<
        ForwardWindowItem, ForwardWindowItem.Builder> implements
    // @@protoc_insertion_point(message_implements:agentassistproto.ForwardWindowItem)
    ForwardWindowItemOrBuilder {
  private ForwardWindowItem() {
    windowId_ = "";
    title_ = "";
  }
  public static final int WINDOW_ID_FIELD_NUMBER = 1;
  private java.lang.String windowId_;
  /**
   * <pre>
   * stable window id
   * </pre>
   *
   * <code>string window_id = 1;</code>
   * @return The windowId.
   */
  @java.lang.Override
  public java.lang.String getWindowId() {
    return windowId_;
  }
  /**
   * <pre>
   * stable window id
   * </pre>
   *
   * <code>string window_id = 1;</code>
   * @return The bytes for windowId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getWindowIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(windowId_);
  }
  /**
   * <pre>
   * stable window id
   * </pre>
   *
   * <code>string window_id = 1;</code>
   * @param value The windowId to set.
   */
  private void setWindowId(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    windowId_ = value;
  }
  /**
   * <pre>
   * stable window id
   * </pre>
   *
   * <code>string window_id = 1;</code>
   */
  private void clearWindowId() {

    windowId_ = getDefaultInstance().getWindowId();
  }
  /**
   * <pre>
   * stable window id
   * </pre>
   *
   * <code>string window_id = 1;</code>
   * @param value The bytes for windowId to set.
   */
  private void setWindowIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    windowId_ = value.toStringUtf8();

  }

  public static final int TITLE_FIELD_NUMBER = 2;
  private java.lang.String title_;
  /**
   * <pre>
   * display title
   * </pre>
   *
   * <code>string title = 2;</code>
   * @return The title.
   */
  @java.lang.Override
  public java.lang.String getTitle() {
    return title_;
  }
  /**
   * <pre>
   * display title
   * </pre>
   *
   * <code>string title = 2;</code>
   * @return The bytes for title.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTitleBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(title_);
  }
  /**
   * <pre>
   * display title
   * </pre>
   *
   * <code>string title = 2;</code>
   * @param value The title to set.
   */
  private void setTitle(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    title_ = value;
  }
  /**
   * <pre>
   * display title
   * </pre>
   *
   * <code>string title = 2;</code>
   */
  private void clearTitle() {

    title_ = getDefaultInstance().getTitle();
  }
  /**
   * <pre>
   * display title
   * </pre>
   *
   * <code>string title = 2;</code>
   * @param value The bytes for title to set.
   */
  private void setTitleBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    title_ = value.toStringUtf8();

  }

  public static code.agentassistant.flutter.flutterclient.proto.ForwardWindowItem parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static code.agentassistant.flutter.flutterclient.proto.ForwardWindowItem parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static code.agentassistant.flutter.flutterclient.proto.ForwardWindowItem parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static code.agentassistant.flutter.flutterclient.proto.ForwardWindowItem parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static code.agentassistant.flutter.flutterclient.proto.ForwardWindowItem parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static code.agentassistant.flutter.flutterclient.proto.ForwardWindowItem parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static code.agentassistant.flutter.flutterclient.proto.ForwardWindowItem parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static code.agentassistant.flutter.flutterclient.proto.ForwardWindowItem parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static code.agentassistant.flutter.flutterclient.proto.ForwardWindowItem parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static code.agentassistant.flutter.flutterclient.proto.ForwardWindowItem parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static code.agentassistant.flutter.flutterclient.proto.ForwardWindowItem parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static code.agentassistant.flutter.flutterclient.proto.ForwardWindowItem parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(code.agentassistant.flutter.flutterclient.proto.ForwardWindowItem prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * ForwardWindowItem describes one forwardable system window
   * </pre>
   *
   * Protobuf type {@code agentassistproto.ForwardWindowItem}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        code.agentassistant.flutter.flutterclient.proto.ForwardWindowItem, Builder> implements
      // @@protoc_insertion_point(builder_implements:agentassistproto.ForwardWindowItem)
      code.agentassistant.flutter.flutterclient.proto.ForwardWindowItemOrBuilder {
    // Construct using code.agentassistant.flutter.flutterclient.proto.ForwardWindowItem.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * stable window id
     * </pre>
     *
     * <code>string window_id = 1;</code>
     * @return The windowId.
     */
    @java.lang.Override
    public java.lang.String getWindowId() {
      return instance.getWindowId();
    }
    /**
     * <pre>
     * stable window id
     * </pre>
     *
     * <code>string window_id = 1;</code>
     * @return The bytes for windowId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getWindowIdBytes() {
      return instance.getWindowIdBytes();
    }
    /**
     * <pre>
     * stable window id
     * </pre>
     *
     * <code>string window_id = 1;</code>
     * @param value The windowId to set.
     * @return This builder for chaining.
     */
    public Builder setWindowId(
        java.lang.String value) {
      copyOnWrite();
      instance.setWindowId(value);
      return this;
    }
    /**
     * <pre>
     * stable window id
     * </pre>
     *
     * <code>string window_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearWindowId() {
      copyOnWrite();
      instance.clearWindowId();
      return this;
    }
    /**
     * <pre>
     * stable window id
     * </pre>
     *
     * <code>string window_id = 1;</code>
     * @param value The bytes for windowId to set.
     * @return This builder for chaining.
     */
    public Builder setWindowIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setWindowIdBytes(value);
      return this;
    }

    /**
     * <pre>
     * display title
     * </pre>
     *
     * <code>string title = 2;</code>
     * @return The title.
     */
    @java.lang.Override
    public java.lang.String getTitle() {
      return instance.getTitle();
    }
    /**
     * <pre>
     * display title
     * </pre>
     *
     * <code>string title = 2;</code>
     * @return The bytes for title.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTitleBytes() {
      return instance.getTitleBytes();
    }
    /**
     * <pre>
     * display title
     * </pre>
     *
     * <code>string title = 2;</code>
     * @param value The title to set.
     * @return This builder for chaining.
     */
    public Builder setTitle(
        java.lang.String value) {
      copyOnWrite();
      instance.setTitle(value);
      return this;
    }
    /**
     * <pre>
     * display title
     * </pre>
     *
     * <code>string title = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTitle() {
      copyOnWrite();
      instance.clearTitle();
      return this;
    }
    /**
     * <pre>
     * display title
     * </pre>
     *
     * <code>string title = 2;</code>
     * @param value The bytes for title to set.
     * @return This builder for chaining.
     */
    public Builder setTitleBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setTitleBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:agentassistproto.ForwardWindowItem)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new code.agentassistant.flutter.flutterclient.proto.ForwardWindowItem();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "windowId_",
            "title_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<code.agentassistant.flutter.flutterclient.proto.ForwardWindowItem> parser = PARSER;
        if (parser == null) {
          synchronized (code.agentassistant.flutter.flutterclient.proto.ForwardWindowItem.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<code.agentassistant.flutter.flutterclient.proto.ForwardWindowItem>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:agentassistproto.ForwardWindowItem)
  private static final code.agentassistant.flutter.flutterclient.proto.ForwardWindowItem DEFAULT_INSTANCE;
  static {
    ForwardWindowItem defaultInstance = new ForwardWindowItem();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      ForwardWindowItem.class, defaultInstance);
  }

  public static code.agentassistant.flutter.flutterclient.proto.ForwardWindowItem getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ForwardWindowItem> PARSER;

  public static com.google.protobuf.Parser<ForwardWindowItem> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

