// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agentassist.proto
// Protobuf Java Version: 4.36.0

package code.agentassistant.flutter.flutterclient.proto;

/**
 * <pre>
 * ForwardStateChangedNotification notifies peers that sender's forward state changed
 * </pre>
 *
 * Protobuf type {@code agentassistproto.ForwardStateChangedNotification}
 */
@com.google.protobuf.Generated
public  final class ForwardStateChangedNotification extends
    com.google.protobuf.GeneratedMessageLite<
        ForwardStateChangedNotification, ForwardStateChangedNotification.Builder> implements
    // @@protoc_insertion_point(message_implements:agentassistproto.ForwardStateChangedNotification)
    ForwardStateChangedNotificationOrBuilder {
  private ForwardStateChangedNotification() {
    sourceClientId_ = "";
    windows_ = emptyProtobufList();
  }
  public static final int SOURCE_CLIENT_ID_FIELD_NUMBER = 1;
  private java.lang.String sourceClientId_;
  /**
   * <pre>
   * source client id whose state changed
   * </pre>
   *
   * <code>string source_client_id = 1;</code>
   * @return The sourceClientId.
   */
  @java.lang.Override
  public java.lang.String getSourceClientId() {
    return sourceClientId_;
  }
  /**
   * <pre>
   * source client id whose state changed
   * </pre>
   *
   * <code>string source_client_id = 1;</code>
   * @return The bytes for sourceClientId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSourceClientIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(sourceClientId_);
  }
  /**
   * <pre>
   * source client id whose state changed
   * </pre>
   *
   * <code>string source_client_id = 1;</code>
   * @param value The sourceClientId to set.
   */
  private void setSourceClientId(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    sourceClientId_ = value;
  }
  /**
   * <pre>
   * source client id whose state changed
   * </pre>
   *
   * <code>string source_client_id = 1;</code>
   */
  private void clearSourceClientId() {

    sourceClientId_ = getDefaultInstance().getSourceClientId();
  }
  /**
   * <pre>
   * source client id whose state changed
   * </pre>
   *
   * <code>string source_client_id = 1;</code>
   * @param value The bytes for sourceClientId to set.
   */
  private void setSourceClientIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    sourceClientId_ = value.toStringUtf8();

  }

  public static final int FORWARD_ENABLED_FIELD_NUMBER = 2;
  private boolean forwardEnabled_;
  /**
   * <pre>
   * whether source has enabled auto forward
   * </pre>
   *
   * <code>bool forward_enabled = 2;</code>
   * @return The forwardEnabled.
   */
  @java.lang.Override
  public boolean getForwardEnabled() {
    return forwardEnabled_;
  }
  /**
   * <pre>
   * whether source has enabled auto forward
   * </pre>
   *
   * <code>bool forward_enabled = 2;</code>
   * @param value The forwardEnabled to set.
   */
  private void setForwardEnabled(boolean value) {
    
    forwardEnabled_ = value;
  }
  /**
   * <pre>
   * whether source has enabled auto forward
   * </pre>
   *
   * <code>bool forward_enabled = 2;</code>
   */
  private void clearForwardEnabled() {

    forwardEnabled_ = false;
  }

  public static final int WINDOWS_FIELD_NUMBER = 3;
  private com.google.protobuf.Internal.ProtobufList<code.agentassistant.flutter.flutterclient.proto.ForwardWindowItem> windows_;
  /**
   * <pre>
   * current forwardable windows snapshot
   * </pre>
   *
   * <code>repeated .agentassistproto.ForwardWindowItem windows = 3;</code>
   */
  @java.lang.Override
  public java.util.List<code.agentassistant.flutter.flutterclient.proto.ForwardWindowItem> getWindowsList() {
    return windows_;
  }
  /**
   * <pre>
   * current forwardable windows snapshot
   * </pre>
   *
   * <code>repeated .agentassistproto.ForwardWindowItem windows = 3;</code>
   */
  public java.util.List<? extends code.agentassistant.flutter.flutterclient.proto.ForwardWindowItemOrBuilder> 
      getWindowsOrBuilderList() {
    return windows_;
  }
  /**
   * <pre>
   * current forwardable windows snapshot
   * </pre>
   *
   * <code>repeated .agentassistproto.ForwardWindowItem windows = 3;</code>
   */
  @java.lang.Override
  public int getWindowsCount() {
    return windows_.size();
  }
  /**
   * <pre>
   * current forwardable windows snapshot
   * </pre>
   *
   * <code>repeated .agentassistproto.ForwardWindowItem windows = 3;</code>
   */
  @java.lang.Override
  public code.agentassistant.flutter.flutterclient.proto.ForwardWindowItem getWindows(int index) {
    return windows_.get(index);
  }
  /**
   * <pre>
   * current forwardable windows snapshot
   * </pre>
   *
   * <code>repeated .agentassistproto.ForwardWindowItem windows = 3;</code>
   */
  public code.agentassistant.flutter.flutterclient.proto.ForwardWindowItemOrBuilder getWindowsOrBuilder(
      int index) {
    return windows_.get(index);
  }
  private void ensureWindowsIsMutable() {
    com.google.protobuf.Internal.ProtobufList<code.agentassistant.flutter.flutterclient.proto.ForwardWindowItem> tmp = windows_;
    if (!tmp.isModifiable()) {
      windows_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <pre>
   * current forwardable windows snapshot
   * </pre>
   *
   * <code>repeated .agentassistproto.ForwardWindowItem windows = 3;</code>
   */
  private void setWindows(
      int index, code.agentassistant.flutter.flutterclient.proto.ForwardWindowItem value) {
    java.util.Objects.requireNonNull(value);
    ensureWindowsIsMutable();
    windows_.set(index, value);
  }
  /**
   * <pre>
   * current forwardable windows snapshot
   * </pre>
   *
   * <code>repeated .agentassistproto.ForwardWindowItem windows = 3;</code>
   */
  private void addWindows(code.agentassistant.flutter.flutterclient.proto.ForwardWindowItem value) {
    java.util.Objects.requireNonNull(value);
    ensureWindowsIsMutable();
    windows_.add(value);
  }
  /**
   * <pre>
   * current forwardable windows snapshot
   * </pre>
   *
   * <code>repeated .agentassistproto.ForwardWindowItem windows = 3;</code>
   */
  private void addWindows(
      int index, code.agentassistant.flutter.flutterclient.proto.ForwardWindowItem value) {
    java.util.Objects.requireNonNull(value);
    ensureWindowsIsMutable();
    windows_.add(index, value);
  }
  /**
   * <pre>
   * current forwardable windows snapshot
   * </pre>
   *
   * <code>repeated .agentassistproto.ForwardWindowItem windows = 3;</code>
   */
  private void addAllWindows(
      java.lang.Iterable<? extends code.agentassistant.flutter.flutterclient.proto.ForwardWindowItem> values) {
    ensureWindowsIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, windows_);
  }
  /**
   * <pre>
   * current forwardable windows snapshot
   * </pre>
   *
   * <code>repeated .agentassistproto.ForwardWindowItem windows = 3;</code>
   */
  private void clearWindows() {
    windows_ = emptyProtobufList();
  }
  /**
   * <pre>
   * current forwardable windows snapshot
   * </pre>
   *
   * <code>repeated .agentassistproto.ForwardWindowItem windows = 3;</code>
   */
  private void removeWindows(int index) {
    ensureWindowsIsMutable();
    windows_.remove(index);
  }

  public static code.agentassistant.flutter.flutterclient.proto.ForwardStateChangedNotification parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static code.agentassistant.flutter.flutterclient.proto.ForwardStateChangedNotification parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static code.agentassistant.flutter.flutterclient.proto.ForwardStateChangedNotification parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static code.agentassistant.flutter.flutterclient.proto.ForwardStateChangedNotification parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static code.agentassistant.flutter.flutterclient.proto.ForwardStateChangedNotification parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static code.agentassistant.flutter.flutterclient.proto.ForwardStateChangedNotification parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static code.agentassistant.flutter.flutterclient.proto.ForwardStateChangedNotification parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static code.agentassistant.flutter.flutterclient.proto.ForwardStateChangedNotification parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static code.agentassistant.flutter.flutterclient.proto.ForwardStateChangedNotification parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static code.agentassistant.flutter.flutterclient.proto.ForwardStateChangedNotification parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static code.agentassistant.flutter.flutterclient.proto.ForwardStateChangedNotification parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static code.agentassistant.flutter.flutterclient.proto.ForwardStateChangedNotification parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(code.agentassistant.flutter.flutterclient.proto.ForwardStateChangedNotification prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * ForwardStateChangedNotification notifies peers that sender's forward state changed
   * </pre>
   *
   * Protobuf type {@code agentassistproto.ForwardStateChangedNotification}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        code.agentassistant.flutter.flutterclient.proto.ForwardStateChangedNotification, Builder> implements
      // @@protoc_insertion_point(builder_implements:agentassistproto.ForwardStateChangedNotification)
      code.agentassistant.flutter.flutterclient.proto.ForwardStateChangedNotificationOrBuilder {
    // Construct using code.agentassistant.flutter.flutterclient.proto.ForwardStateChangedNotification.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * source client id whose state changed
     * </pre>
     *
     * <code>string source_client_id = 1;</code>
     * @return The sourceClientId.
     */
    @java.lang.Override
    public java.lang.String getSourceClientId() {
      return instance.getSourceClientId();
    }
    /**
     * <pre>
     * source client id whose state changed
     * </pre>
     *
     * <code>string source_client_id = 1;</code>
     * @return The bytes for sourceClientId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSourceClientIdBytes() {
      return instance.getSourceClientIdBytes();
    }
    /**
     * <pre>
     * source client id whose state changed
     * </pre>
     *
     * <code>string source_client_id = 1;</code>
     * @param value The sourceClientId to set.
     * @return This builder for chaining.
     */
    public Builder setSourceClientId(
        java.lang.String value) {
      copyOnWrite();
      instance.setSourceClientId(value);
      return this;
    }
    /**
     * <pre>
     * source client id whose state changed
     * </pre>
     *
     * <code>string source_client_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSourceClientId() {
      copyOnWrite();
      instance.clearSourceClientId();
      return this;
    }
    /**
     * <pre>
     * source client id whose state changed
     * </pre>
     *
     * <code>string source_client_id = 1;</code>
     * @param value The bytes for sourceClientId to set.
     * @return This builder for chaining.
     */
    public Builder setSourceClientIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setSourceClientIdBytes(value);
      return this;
    }

    /**
     * <pre>
     * whether source has enabled auto forward
     * </pre>
     *
     * <code>bool forward_enabled = 2;</code>
     * @return The forwardEnabled.
     */
    @java.lang.Override
    public boolean getForwardEnabled() {
      return instance.getForwardEnabled();
    }
    /**
     * <pre>
     * whether source has enabled auto forward
     * </pre>
     *
     * <code>bool forward_enabled = 2;</code>
     * @param value The forwardEnabled to set.
     * @return This builder for chaining.
     */
    public Builder setForwardEnabled(boolean value) {
      copyOnWrite();
      instance.setForwardEnabled(value);
      return this;
    }
    /**
     * <pre>
     * whether source has enabled auto forward
     * </pre>
     *
     * <code>bool forward_enabled = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearForwardEnabled() {
      copyOnWrite();
      instance.clearForwardEnabled();
      return this;
    }

    /**
     * <pre>
     * current forwardable windows snapshot
     * </pre>
     *
     * <code>repeated .agentassistproto.ForwardWindowItem windows = 3;</code>
     */
    @java.lang.Override
    public java.util.List<code.agentassistant.flutter.flutterclient.proto.ForwardWindowItem> getWindowsList() {
      return java.util.Collections.unmodifiableList(
          instance.getWindowsList());
    }
    /**
     * <pre>
     * current forwardable windows snapshot
     * </pre>
     *
     * <code>repeated .agentassistproto.ForwardWindowItem windows = 3;</code>
     */
    @java.lang.Override
    public int getWindowsCount() {
      return instance.getWindowsCount();
    }/**
     * <pre>
     * current forwardable windows snapshot
     * </pre>
     *
     * <code>repeated .agentassistproto.ForwardWindowItem windows = 3;</code>
     */
    @java.lang.Override
    public code.agentassistant.flutter.flutterclient.proto.ForwardWindowItem getWindows(int index) {
      return instance.getWindows(index);
    }
    /**
     * <pre>
     * current forwardable windows snapshot
     * </pre>
     *
     * <code>repeated .agentassistproto.ForwardWindowItem windows = 3;</code>
     */
    public Builder setWindows(
        int index, code.agentassistant.flutter.flutterclient.proto.ForwardWindowItem value) {
      copyOnWrite();
      instance.setWindows(index, value);
      return this;
    }
    /**
     * <pre>
     * current forwardable windows snapshot
     * </pre>
     *
     * <code>repeated .agentassistproto.ForwardWindowItem windows = 3;</code>
     */
    public Builder setWindows(
        int index, code.agentassistant.flutter.flutterclient.proto.ForwardWindowItem.Builder builderForValue) {
      copyOnWrite();
      instance.setWindows(index,
          builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * current forwardable windows snapshot
     * </pre>
     *
     * <code>repeated .agentassistproto.ForwardWindowItem windows = 3;</code>
     */
    public Builder addWindows(code.agentassistant.flutter.flutterclient.proto.ForwardWindowItem value) {
      copyOnWrite();
      instance.addWindows(value);
      return this;
    }
    /**
     * <pre>
     * current forwardable windows snapshot
     * </pre>
     *
     * <code>repeated .agentassistproto.ForwardWindowItem windows = 3;</code>
     */
    public Builder addWindows(
        int index, code.agentassistant.flutter.flutterclient.proto.ForwardWindowItem value) {
      copyOnWrite();
      instance.addWindows(index, value);
      return this;
    }
    /**
     * <pre>
     * current forwardable windows snapshot
     * </pre>
     *
     * <code>repeated .agentassistproto.ForwardWindowItem windows = 3;</code>
     */
    public Builder addWindows(
        code.agentassistant.flutter.flutterclient.proto.ForwardWindowItem.Builder builderForValue) {
      copyOnWrite();
      instance.addWindows(builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * current forwardable windows snapshot
     * </pre>
     *
     * <code>repeated .agentassistproto.ForwardWindowItem windows = 3;</code>
     */
    public Builder addWindows(
        int index, code.agentassistant.flutter.flutterclient.proto.ForwardWindowItem.Builder builderForValue) {
      copyOnWrite();
      instance.addWindows(index,
          builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * current forwardable windows snapshot
     * </pre>
     *
     * <code>repeated .agentassistproto.ForwardWindowItem windows = 3;</code>
     */
    public Builder addAllWindows(
        java.lang.Iterable<? extends code.agentassistant.flutter.flutterclient.proto.ForwardWindowItem> values) {
      copyOnWrite();
      instance.addAllWindows(values);
      return this;
    }
    /**
     * <pre>
     * current forwardable windows snapshot
     * </pre>
     *
     * <code>repeated .agentassistproto.ForwardWindowItem windows = 3;</code>
     */
    public Builder clearWindows() {
      copyOnWrite();
      instance.clearWindows();
      return this;
    }
    /**
     * <pre>
     * current forwardable windows snapshot
     * </pre>
     *
     * <code>repeated .agentassistproto.ForwardWindowItem windows = 3;</code>
     */
    public Builder removeWindows(int index) {
      copyOnWrite();
      instance.removeWindows(index);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:agentassistproto.ForwardStateChangedNotification)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new code.agentassistant.flutter.flutterclient.proto.ForwardStateChangedNotification();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "sourceClientId_",
            "forwardEnabled_",
            "windows_",
            code.agentassistant.flutter.flutterclient.proto.ForwardWindowItem.class,
          };
          java.lang.String info =
              "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0001\u0000\u0001\u0208\u0002\u0007" +
              "\u0003\u001b";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<code.agentassistant.flutter.flutterclient.proto.ForwardStateChangedNotification> parser = PARSER;
        if (parser == null) {
          synchronized (code.agentassistant.flutter.flutterclient.proto.ForwardStateChangedNotification.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<code.agentassistant.flutter.flutterclient.proto.ForwardStateChangedNotification>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:agentassistproto.ForwardStateChangedNotification)
  private static final code.agentassistant.flutter.flutterclient.proto.ForwardStateChangedNotification DEFAULT_INSTANCE;
  static {
    ForwardStateChangedNotification defaultInstance = new ForwardStateChangedNotification();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      ForwardStateChangedNotification.class, defaultInstance);
  }

  public static code.agentassistant.flutter.flutterclient.proto.ForwardStateChangedNotification getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ForwardStateChangedNotification> PARSER;

  public static com.google.protobuf.Parser<ForwardStateChangedNotification> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

