// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agentassist.proto
// Protobuf Java Version: 4.36.0

package code.agentassistant.flutter.flutterclient.proto;

@com.google.protobuf.Generated
public interface ForwardStateQueryRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:agentassistproto.ForwardStateQueryRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * request id for matching response
   * </pre>
   *
   * <code>string request_id = 1;</code>
   * @return The requestId.
   */
  java.lang.String getRequestId();
  /**
   * <pre>
   * request id for matching response
   * </pre>
   *
   * <code>string request_id = 1;</code>
   * @return The bytes for requestId.
   */
  com.google.protobuf.ByteString
      getRequestIdBytes();

  /**
   * <pre>
   * query target client id
   * </pre>
   *
   * <code>string target_client_id = 2;</code>
   * @return The targetClientId.
   */
  java.lang.String getTargetClientId();
  /**
   * <pre>
   * query target client id
   * </pre>
   *
   * <code>string target_client_id = 2;</code>
   * @return The bytes for targetClientId.
   */
  com.google.protobuf.ByteString
      getTargetClientIdBytes();

  /**
   * <pre>
   * requester client id (filled by server)
   * </pre>
   *
   * <code>string requester_client_id = 3;</code>
   * @return The requesterClientId.
   */
  java.lang.String getRequesterClientId();
  /**
   * <pre>
   * requester client id (filled by server)
   * </pre>
   *
   * <code>string requester_client_id = 3;</code>
   * @return The bytes for requesterClientId.
   */
  com.google.protobuf.ByteString
      getRequesterClientIdBytes();
}
