// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agentassist.proto
// Protobuf Java Version: 4.36.0

package code.agentassistant.flutter.flutterclient.proto;

@com.google.protobuf.Generated
public interface ForwardStateChangedNotificationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:agentassistproto.ForwardStateChangedNotification)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * source client id whose state changed
   * </pre>
   *
   * <code>string source_client_id = 1;</code>
   * @return The sourceClientId.
   */
  java.lang.String getSourceClientId();
  /**
   * <pre>
   * source client id whose state changed
   * </pre>
   *
   * <code>string source_client_id = 1;</code>
   * @return The bytes for sourceClientId.
   */
  com.google.protobuf.ByteString
      getSourceClientIdBytes();

  /**
   * <pre>
   * whether source has enabled auto forward
   * </pre>
   *
   * <code>bool forward_enabled = 2;</code>
   * @return The forwardEnabled.
   */
  boolean getForwardEnabled();

  /**
   * <pre>
   * current forwardable windows snapshot
   * </pre>
   *
   * <code>repeated .agentassistproto.ForwardWindowItem windows = 3;</code>
   */
  java.util.List<code.agentassistant.flutter.flutterclient.proto.ForwardWindowItem> 
      getWindowsList();
  /**
   * <pre>
   * current forwardable windows snapshot
   * </pre>
   *
   * <code>repeated .agentassistproto.ForwardWindowItem windows = 3;</code>
   */
  code.agentassistant.flutter.flutterclient.proto.ForwardWindowItem getWindows(int index);
  /**
   * <pre>
   * current forwardable windows snapshot
   * </pre>
   *
   * <code>repeated .agentassistproto.ForwardWindowItem windows = 3;</code>
   */
  int getWindowsCount();
}
