// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agentassist.proto
// Protobuf Java Version: 4.36.0

package code.agentassistant.flutter.flutterclient.proto;

/**
 * <pre>
 * GetOnlineUsersResponse represents the response containing online users
 * </pre>
 *
 * Protobuf type {@code agentassistproto.GetOnlineUsersResponse}
 */
@com.google.protobuf.Generated
public  final class GetOnlineUsersResponse extends
    com.google.protobuf.GeneratedMessageLite<
        GetOnlineUsersResponse, GetOnlineUsersResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:agentassistproto.GetOnlineUsersResponse)
    GetOnlineUsersResponseOrBuilder {
  private GetOnlineUsersResponse() {
    onlineUsers_ = emptyProtobufList();
  }
  public static final int ONLINE_USERS_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.ProtobufList<code.agentassistant.flutter.flutterclient.proto.OnlineUser> onlineUsers_;
  /**
   * <pre>
   * list of online users
   * </pre>
   *
   * <code>repeated .agentassistproto.OnlineUser online_users = 1;</code>
   */
  @java.lang.Override
  public java.util.List<code.agentassistant.flutter.flutterclient.proto.OnlineUser> getOnlineUsersList() {
    return onlineUsers_;
  }
  /**
   * <pre>
   * list of online users
   * </pre>
   *
   * <code>repeated .agentassistproto.OnlineUser online_users = 1;</code>
   */
  public java.util.List<? extends code.agentassistant.flutter.flutterclient.proto.OnlineUserOrBuilder> 
      getOnlineUsersOrBuilderList() {
    return onlineUsers_;
  }
  /**
   * <pre>
   * list of online users
   * </pre>
   *
   * <code>repeated .agentassistproto.OnlineUser online_users = 1;</code>
   */
  @java.lang.Override
  public int getOnlineUsersCount() {
    return onlineUsers_.size();
  }
  /**
   * <pre>
   * list of online users
   * </pre>
   *
   * <code>repeated .agentassistproto.OnlineUser online_users = 1;</code>
   */
  @java.lang.Override
  public code.agentassistant.flutter.flutterclient.proto.OnlineUser getOnlineUsers(int index) {
    return onlineUsers_.get(index);
  }
  /**
   * <pre>
   * list of online users
   * </pre>
   *
   * <code>repeated .agentassistproto.OnlineUser online_users = 1;</code>
   */
  public code.agentassistant.flutter.flutterclient.proto.OnlineUserOrBuilder getOnlineUsersOrBuilder(
      int index) {
    return onlineUsers_.get(index);
  }
  private void ensureOnlineUsersIsMutable() {
    com.google.protobuf.Internal.ProtobufList<code.agentassistant.flutter.flutterclient.proto.OnlineUser> tmp = onlineUsers_;
    if (!tmp.isModifiable()) {
      onlineUsers_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <pre>
   * list of online users
   * </pre>
   *
   * <code>repeated .agentassistproto.OnlineUser online_users = 1;</code>
   */
  private void setOnlineUsers(
      int index, code.agentassistant.flutter.flutterclient.proto.OnlineUser value) {
    java.util.Objects.requireNonNull(value);
    ensureOnlineUsersIsMutable();
    onlineUsers_.set(index, value);
  }
  /**
   * <pre>
   * list of online users
   * </pre>
   *
   * <code>repeated .agentassistproto.OnlineUser online_users = 1;</code>
   */
  private void addOnlineUsers(code.agentassistant.flutter.flutterclient.proto.OnlineUser value) {
    java.util.Objects.requireNonNull(value);
    ensureOnlineUsersIsMutable();
    onlineUsers_.add(value);
  }
  /**
   * <pre>
   * list of online users
   * </pre>
   *
   * <code>repeated .agentassistproto.OnlineUser online_users = 1;</code>
   */
  private void addOnlineUsers(
      int index, code.agentassistant.flutter.flutterclient.proto.OnlineUser value) {
    java.util.Objects.requireNonNull(value);
    ensureOnlineUsersIsMutable();
    onlineUsers_.add(index, value);
  }
  /**
   * <pre>
   * list of online users
   * </pre>
   *
   * <code>repeated .agentassistproto.OnlineUser online_users = 1;</code>
   */
  private void addAllOnlineUsers(
      java.lang.Iterable<? extends code.agentassistant.flutter.flutterclient.proto.OnlineUser> values) {
    ensureOnlineUsersIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, onlineUsers_);
  }
  /**
   * <pre>
   * list of online users
   * </pre>
   *
   * <code>repeated .agentassistproto.OnlineUser online_users = 1;</code>
   */
  private void clearOnlineUsers() {
    onlineUsers_ = emptyProtobufList();
  }
  /**
   * <pre>
   * list of online users
   * </pre>
   *
   * <code>repeated .agentassistproto.OnlineUser online_users = 1;</code>
   */
  private void removeOnlineUsers(int index) {
    ensureOnlineUsersIsMutable();
    onlineUsers_.remove(index);
  }

  public static final int TOTAL_COUNT_FIELD_NUMBER = 2;
  private int totalCount_;
  /**
   * <pre>
   * total count of online users
   * </pre>
   *
   * <code>int32 total_count = 2;</code>
   * @return The totalCount.
   */
  @java.lang.Override
  public int getTotalCount() {
    return totalCount_;
  }
  /**
   * <pre>
   * total count of online users
   * </pre>
   *
   * <code>int32 total_count = 2;</code>
   * @param value The totalCount to set.
   */
  private void setTotalCount(int value) {
    
    totalCount_ = value;
  }
  /**
   * <pre>
   * total count of online users
   * </pre>
   *
   * <code>int32 total_count = 2;</code>
   */
  private void clearTotalCount() {

    totalCount_ = 0;
  }

  public static code.agentassistant.flutter.flutterclient.proto.GetOnlineUsersResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static code.agentassistant.flutter.flutterclient.proto.GetOnlineUsersResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static code.agentassistant.flutter.flutterclient.proto.GetOnlineUsersResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static code.agentassistant.flutter.flutterclient.proto.GetOnlineUsersResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static code.agentassistant.flutter.flutterclient.proto.GetOnlineUsersResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static code.agentassistant.flutter.flutterclient.proto.GetOnlineUsersResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static code.agentassistant.flutter.flutterclient.proto.GetOnlineUsersResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static code.agentassistant.flutter.flutterclient.proto.GetOnlineUsersResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static code.agentassistant.flutter.flutterclient.proto.GetOnlineUsersResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static code.agentassistant.flutter.flutterclient.proto.GetOnlineUsersResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static code.agentassistant.flutter.flutterclient.proto.GetOnlineUsersResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static code.agentassistant.flutter.flutterclient.proto.GetOnlineUsersResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(code.agentassistant.flutter.flutterclient.proto.GetOnlineUsersResponse prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * GetOnlineUsersResponse represents the response containing online users
   * </pre>
   *
   * Protobuf type {@code agentassistproto.GetOnlineUsersResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        code.agentassistant.flutter.flutterclient.proto.GetOnlineUsersResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:agentassistproto.GetOnlineUsersResponse)
      code.agentassistant.flutter.flutterclient.proto.GetOnlineUsersResponseOrBuilder {
    // Construct using code.agentassistant.flutter.flutterclient.proto.GetOnlineUsersResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * list of online users
     * </pre>
     *
     * <code>repeated .agentassistproto.OnlineUser online_users = 1;</code>
     */
    @java.lang.Override
    public java.util.List<code.agentassistant.flutter.flutterclient.proto.OnlineUser> getOnlineUsersList() {
      return java.util.Collections.unmodifiableList(
          instance.getOnlineUsersList());
    }
    /**
     * <pre>
     * list of online users
     * </pre>
     *
     * <code>repeated .agentassistproto.OnlineUser online_users = 1;</code>
     */
    @java.lang.Override
    public int getOnlineUsersCount() {
      return instance.getOnlineUsersCount();
    }/**
     * <pre>
     * list of online users
     * </pre>
     *
     * <code>repeated .agentassistproto.OnlineUser online_users = 1;</code>
     */
    @java.lang.Override
    public code.agentassistant.flutter.flutterclient.proto.OnlineUser getOnlineUsers(int index) {
      return instance.getOnlineUsers(index);
    }
    /**
     * <pre>
     * list of online users
     * </pre>
     *
     * <code>repeated .agentassistproto.OnlineUser online_users = 1;</code>
     */
    public Builder setOnlineUsers(
        int index, code.agentassistant.flutter.flutterclient.proto.OnlineUser value) {
      copyOnWrite();
      instance.setOnlineUsers(index, value);
      return this;
    }
    /**
     * <pre>
     * list of online users
     * </pre>
     *
     * <code>repeated .agentassistproto.OnlineUser online_users = 1;</code>
     */
    public Builder setOnlineUsers(
        int index, code.agentassistant.flutter.flutterclient.proto.OnlineUser.Builder builderForValue) {
      copyOnWrite();
      instance.setOnlineUsers(index,
          builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * list of online users
     * </pre>
     *
     * <code>repeated .agentassistproto.OnlineUser online_users = 1;</code>
     */
    public Builder addOnlineUsers(code.agentassistant.flutter.flutterclient.proto.OnlineUser value) {
      copyOnWrite();
      instance.addOnlineUsers(value);
      return this;
    }
    /**
     * <pre>
     * list of online users
     * </pre>
     *
     * <code>repeated .agentassistproto.OnlineUser online_users = 1;</code>
     */
    public Builder addOnlineUsers(
        int index, code.agentassistant.flutter.flutterclient.proto.OnlineUser value) {
      copyOnWrite();
      instance.addOnlineUsers(index, value);
      return this;
    }
    /**
     * <pre>
     * list of online users
     * </pre>
     *
     * <code>repeated .agentassistproto.OnlineUser online_users = 1;</code>
     */
    public Builder addOnlineUsers(
        code.agentassistant.flutter.flutterclient.proto.OnlineUser.Builder builderForValue) {
      copyOnWrite();
      instance.addOnlineUsers(builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * list of online users
     * </pre>
     *
     * <code>repeated .agentassistproto.OnlineUser online_users = 1;</code>
     */
    public Builder addOnlineUsers(
        int index, code.agentassistant.flutter.flutterclient.proto.OnlineUser.Builder builderForValue) {
      copyOnWrite();
      instance.addOnlineUsers(index,
          builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * list of online users
     * </pre>
     *
     * <code>repeated .agentassistproto.OnlineUser online_users = 1;</code>
     */
    public Builder addAllOnlineUsers(
        java.lang.Iterable<? extends code.agentassistant.flutter.flutterclient.proto.OnlineUser> values) {
      copyOnWrite();
      instance.addAllOnlineUsers(values);
      return this;
    }
    /**
     * <pre>
     * list of online users
     * </pre>
     *
     * <code>repeated .agentassistproto.OnlineUser online_users = 1;</code>
     */
    public Builder clearOnlineUsers() {
      copyOnWrite();
      instance.clearOnlineUsers();
      return this;
    }
    /**
     * <pre>
     * list of online users
     * </pre>
     *
     * <code>repeated .agentassistproto.OnlineUser online_users = 1;</code>
     */
    public Builder removeOnlineUsers(int index) {
      copyOnWrite();
      instance.removeOnlineUsers(index);
      return this;
    }

    /**
     * <pre>
     * total count of online users
     * </pre>
     *
     * <code>int32 total_count = 2;</code>
     * @return The totalCount.
     */
    @java.lang.Override
    public int getTotalCount() {
      return instance.getTotalCount();
    }
    /**
     * <pre>
     * total count of online users
     * </pre>
     *
     * <code>int32 total_count = 2;</code>
     * @param value The totalCount to set.
     * @return This builder for chaining.
     */
    public Builder setTotalCount(int value) {
      copyOnWrite();
      instance.setTotalCount(value);
      return this;
    }
    /**
     * <pre>
     * total count of online users
     * </pre>
     *
     * <code>int32 total_count = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalCount() {
      copyOnWrite();
      instance.clearTotalCount();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:agentassistproto.GetOnlineUsersResponse)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new code.agentassistant.flutter.flutterclient.proto.GetOnlineUsersResponse();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "onlineUsers_",
            code.agentassistant.flutter.flutterclient.proto.OnlineUser.class,
            "totalCount_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0001\u0000\u0001\u001b\u0002\u0004" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<code.agentassistant.flutter.flutterclient.proto.GetOnlineUsersResponse> parser = PARSER;
        if (parser == null) {
          synchronized (code.agentassistant.flutter.flutterclient.proto.GetOnlineUsersResponse.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<code.agentassistant.flutter.flutterclient.proto.GetOnlineUsersResponse>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:agentassistproto.GetOnlineUsersResponse)
  private static final code.agentassistant.flutter.flutterclient.proto.GetOnlineUsersResponse DEFAULT_INSTANCE;
  static {
    GetOnlineUsersResponse defaultInstance = new GetOnlineUsersResponse();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      GetOnlineUsersResponse.class, defaultInstance);
  }

  public static code.agentassistant.flutter.flutterclient.proto.GetOnlineUsersResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<GetOnlineUsersResponse> PARSER;

  public static com.google.protobuf.Parser<GetOnlineUsersResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

