// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agentassist.proto
// Protobuf Java Version: 4.36.0

package code.agentassistant.flutter.flutterclient.proto;

@com.google.protobuf.Generated
public interface GetOnlineUsersResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:agentassistproto.GetOnlineUsersResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * list of online users
   * </pre>
   *
   * <code>repeated .agentassistproto.OnlineUser online_users = 1;</code>
   */
  java.util.List<code.agentassistant.flutter.flutterclient.proto.OnlineUser> 
      getOnlineUsersList();
  /**
   * <pre>
   * list of online users
   * </pre>
   *
   * <code>repeated .agentassistproto.OnlineUser online_users = 1;</code>
   */
  code.agentassistant.flutter.flutterclient.proto.OnlineUser getOnlineUsers(int index);
  /**
   * <pre>
   * list of online users
   * </pre>
   *
   * <code>repeated .agentassistproto.OnlineUser online_users = 1;</code>
   */
  int getOnlineUsersCount();

  /**
   * <pre>
   * total count of online users
   * </pre>
   *
   * <code>int32 total_count = 2;</code>
   * @return The totalCount.
   */
  int getTotalCount();
}
