// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agentassist.proto
// Protobuf Java Version: 4.36.0

package code.agentassistant.flutter.flutterclient.proto;

/**
 * <pre>
 * GetPendingMessagesResponse represents the response containing all pending
 * messages
 * </pre>
 *
 * Protobuf type {@code agentassistproto.GetPendingMessagesResponse}
 */
@com.google.protobuf.Generated
public  final class GetPendingMessagesResponse extends
    com.google.protobuf.GeneratedMessageLite<
        GetPendingMessagesResponse, GetPendingMessagesResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:agentassistproto.GetPendingMessagesResponse)
    GetPendingMessagesResponseOrBuilder {
  private GetPendingMessagesResponse() {
    pendingMessages_ = emptyProtobufList();
  }
  public static final int PENDING_MESSAGES_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.ProtobufList<code.agentassistant.flutter.flutterclient.proto.PendingMessage> pendingMessages_;
  /**
   * <pre>
   * list of pending messages
   * </pre>
   *
   * <code>repeated .agentassistproto.PendingMessage pending_messages = 1;</code>
   */
  @java.lang.Override
  public java.util.List<code.agentassistant.flutter.flutterclient.proto.PendingMessage> getPendingMessagesList() {
    return pendingMessages_;
  }
  /**
   * <pre>
   * list of pending messages
   * </pre>
   *
   * <code>repeated .agentassistproto.PendingMessage pending_messages = 1;</code>
   */
  public java.util.List<? extends code.agentassistant.flutter.flutterclient.proto.PendingMessageOrBuilder> 
      getPendingMessagesOrBuilderList() {
    return pendingMessages_;
  }
  /**
   * <pre>
   * list of pending messages
   * </pre>
   *
   * <code>repeated .agentassistproto.PendingMessage pending_messages = 1;</code>
   */
  @java.lang.Override
  public int getPendingMessagesCount() {
    return pendingMessages_.size();
  }
  /**
   * <pre>
   * list of pending messages
   * </pre>
   *
   * <code>repeated .agentassistproto.PendingMessage pending_messages = 1;</code>
   */
  @java.lang.Override
  public code.agentassistant.flutter.flutterclient.proto.PendingMessage getPendingMessages(int index) {
    return pendingMessages_.get(index);
  }
  /**
   * <pre>
   * list of pending messages
   * </pre>
   *
   * <code>repeated .agentassistproto.PendingMessage pending_messages = 1;</code>
   */
  public code.agentassistant.flutter.flutterclient.proto.PendingMessageOrBuilder getPendingMessagesOrBuilder(
      int index) {
    return pendingMessages_.get(index);
  }
  private void ensurePendingMessagesIsMutable() {
    com.google.protobuf.Internal.ProtobufList<code.agentassistant.flutter.flutterclient.proto.PendingMessage> tmp = pendingMessages_;
    if (!tmp.isModifiable()) {
      pendingMessages_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <pre>
   * list of pending messages
   * </pre>
   *
   * <code>repeated .agentassistproto.PendingMessage pending_messages = 1;</code>
   */
  private void setPendingMessages(
      int index, code.agentassistant.flutter.flutterclient.proto.PendingMessage value) {
    java.util.Objects.requireNonNull(value);
    ensurePendingMessagesIsMutable();
    pendingMessages_.set(index, value);
  }
  /**
   * <pre>
   * list of pending messages
   * </pre>
   *
   * <code>repeated .agentassistproto.PendingMessage pending_messages = 1;</code>
   */
  private void addPendingMessages(code.agentassistant.flutter.flutterclient.proto.PendingMessage value) {
    java.util.Objects.requireNonNull(value);
    ensurePendingMessagesIsMutable();
    pendingMessages_.add(value);
  }
  /**
   * <pre>
   * list of pending messages
   * </pre>
   *
   * <code>repeated .agentassistproto.PendingMessage pending_messages = 1;</code>
   */
  private void addPendingMessages(
      int index, code.agentassistant.flutter.flutterclient.proto.PendingMessage value) {
    java.util.Objects.requireNonNull(value);
    ensurePendingMessagesIsMutable();
    pendingMessages_.add(index, value);
  }
  /**
   * <pre>
   * list of pending messages
   * </pre>
   *
   * <code>repeated .agentassistproto.PendingMessage pending_messages = 1;</code>
   */
  private void addAllPendingMessages(
      java.lang.Iterable<? extends code.agentassistant.flutter.flutterclient.proto.PendingMessage> values) {
    ensurePendingMessagesIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, pendingMessages_);
  }
  /**
   * <pre>
   * list of pending messages
   * </pre>
   *
   * <code>repeated .agentassistproto.PendingMessage pending_messages = 1;</code>
   */
  private void clearPendingMessages() {
    pendingMessages_ = emptyProtobufList();
  }
  /**
   * <pre>
   * list of pending messages
   * </pre>
   *
   * <code>repeated .agentassistproto.PendingMessage pending_messages = 1;</code>
   */
  private void removePendingMessages(int index) {
    ensurePendingMessagesIsMutable();
    pendingMessages_.remove(index);
  }

  public static final int TOTAL_COUNT_FIELD_NUMBER = 2;
  private int totalCount_;
  /**
   * <pre>
   * total count of pending messages
   * </pre>
   *
   * <code>int32 total_count = 2;</code>
   * @return The totalCount.
   */
  @java.lang.Override
  public int getTotalCount() {
    return totalCount_;
  }
  /**
   * <pre>
   * total count of pending messages
   * </pre>
   *
   * <code>int32 total_count = 2;</code>
   * @param value The totalCount to set.
   */
  private void setTotalCount(int value) {
    
    totalCount_ = value;
  }
  /**
   * <pre>
   * total count of pending messages
   * </pre>
   *
   * <code>int32 total_count = 2;</code>
   */
  private void clearTotalCount() {

    totalCount_ = 0;
  }

  public static code.agentassistant.flutter.flutterclient.proto.GetPendingMessagesResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static code.agentassistant.flutter.flutterclient.proto.GetPendingMessagesResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static code.agentassistant.flutter.flutterclient.proto.GetPendingMessagesResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static code.agentassistant.flutter.flutterclient.proto.GetPendingMessagesResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static code.agentassistant.flutter.flutterclient.proto.GetPendingMessagesResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static code.agentassistant.flutter.flutterclient.proto.GetPendingMessagesResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static code.agentassistant.flutter.flutterclient.proto.GetPendingMessagesResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static code.agentassistant.flutter.flutterclient.proto.GetPendingMessagesResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static code.agentassistant.flutter.flutterclient.proto.GetPendingMessagesResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static code.agentassistant.flutter.flutterclient.proto.GetPendingMessagesResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static code.agentassistant.flutter.flutterclient.proto.GetPendingMessagesResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static code.agentassistant.flutter.flutterclient.proto.GetPendingMessagesResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(code.agentassistant.flutter.flutterclient.proto.GetPendingMessagesResponse prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * GetPendingMessagesResponse represents the response containing all pending
   * messages
   * </pre>
   *
   * Protobuf type {@code agentassistproto.GetPendingMessagesResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        code.agentassistant.flutter.flutterclient.proto.GetPendingMessagesResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:agentassistproto.GetPendingMessagesResponse)
      code.agentassistant.flutter.flutterclient.proto.GetPendingMessagesResponseOrBuilder {
    // Construct using code.agentassistant.flutter.flutterclient.proto.GetPendingMessagesResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * list of pending messages
     * </pre>
     *
     * <code>repeated .agentassistproto.PendingMessage pending_messages = 1;</code>
     */
    @java.lang.Override
    public java.util.List<code.agentassistant.flutter.flutterclient.proto.PendingMessage> getPendingMessagesList() {
      return java.util.Collections.unmodifiableList(
          instance.getPendingMessagesList());
    }
    /**
     * <pre>
     * list of pending messages
     * </pre>
     *
     * <code>repeated .agentassistproto.PendingMessage pending_messages = 1;</code>
     */
    @java.lang.Override
    public int getPendingMessagesCount() {
      return instance.getPendingMessagesCount();
    }/**
     * <pre>
     * list of pending messages
     * </pre>
     *
     * <code>repeated .agentassistproto.PendingMessage pending_messages = 1;</code>
     */
    @java.lang.Override
    public code.agentassistant.flutter.flutterclient.proto.PendingMessage getPendingMessages(int index) {
      return instance.getPendingMessages(index);
    }
    /**
     * <pre>
     * list of pending messages
     * </pre>
     *
     * <code>repeated .agentassistproto.PendingMessage pending_messages = 1;</code>
     */
    public Builder setPendingMessages(
        int index, code.agentassistant.flutter.flutterclient.proto.PendingMessage value) {
      copyOnWrite();
      instance.setPendingMessages(index, value);
      return this;
    }
    /**
     * <pre>
     * list of pending messages
     * </pre>
     *
     * <code>repeated .agentassistproto.PendingMessage pending_messages = 1;</code>
     */
    public Builder setPendingMessages(
        int index, code.agentassistant.flutter.flutterclient.proto.PendingMessage.Builder builderForValue) {
      copyOnWrite();
      instance.setPendingMessages(index,
          builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * list of pending messages
     * </pre>
     *
     * <code>repeated .agentassistproto.PendingMessage pending_messages = 1;</code>
     */
    public Builder addPendingMessages(code.agentassistant.flutter.flutterclient.proto.PendingMessage value) {
      copyOnWrite();
      instance.addPendingMessages(value);
      return this;
    }
    /**
     * <pre>
     * list of pending messages
     * </pre>
     *
     * <code>repeated .agentassistproto.PendingMessage pending_messages = 1;</code>
     */
    public Builder addPendingMessages(
        int index, code.agentassistant.flutter.flutterclient.proto.PendingMessage value) {
      copyOnWrite();
      instance.addPendingMessages(index, value);
      return this;
    }
    /**
     * <pre>
     * list of pending messages
     * </pre>
     *
     * <code>repeated .agentassistproto.PendingMessage pending_messages = 1;</code>
     */
    public Builder addPendingMessages(
        code.agentassistant.flutter.flutterclient.proto.PendingMessage.Builder builderForValue) {
      copyOnWrite();
      instance.addPendingMessages(builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * list of pending messages
     * </pre>
     *
     * <code>repeated .agentassistproto.PendingMessage pending_messages = 1;</code>
     */
    public Builder addPendingMessages(
        int index, code.agentassistant.flutter.flutterclient.proto.PendingMessage.Builder builderForValue) {
      copyOnWrite();
      instance.addPendingMessages(index,
          builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * list of pending messages
     * </pre>
     *
     * <code>repeated .agentassistproto.PendingMessage pending_messages = 1;</code>
     */
    public Builder addAllPendingMessages(
        java.lang.Iterable<? extends code.agentassistant.flutter.flutterclient.proto.PendingMessage> values) {
      copyOnWrite();
      instance.addAllPendingMessages(values);
      return this;
    }
    /**
     * <pre>
     * list of pending messages
     * </pre>
     *
     * <code>repeated .agentassistproto.PendingMessage pending_messages = 1;</code>
     */
    public Builder clearPendingMessages() {
      copyOnWrite();
      instance.clearPendingMessages();
      return this;
    }
    /**
     * <pre>
     * list of pending messages
     * </pre>
     *
     * <code>repeated .agentassistproto.PendingMessage pending_messages = 1;</code>
     */
    public Builder removePendingMessages(int index) {
      copyOnWrite();
      instance.removePendingMessages(index);
      return this;
    }

    /**
     * <pre>
     * total count of pending messages
     * </pre>
     *
     * <code>int32 total_count = 2;</code>
     * @return The totalCount.
     */
    @java.lang.Override
    public int getTotalCount() {
      return instance.getTotalCount();
    }
    /**
     * <pre>
     * total count of pending messages
     * </pre>
     *
     * <code>int32 total_count = 2;</code>
     * @param value The totalCount to set.
     * @return This builder for chaining.
     */
    public Builder setTotalCount(int value) {
      copyOnWrite();
      instance.setTotalCount(value);
      return this;
    }
    /**
     * <pre>
     * total count of pending messages
     * </pre>
     *
     * <code>int32 total_count = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalCount() {
      copyOnWrite();
      instance.clearTotalCount();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:agentassistproto.GetPendingMessagesResponse)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new code.agentassistant.flutter.flutterclient.proto.GetPendingMessagesResponse();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "pendingMessages_",
            code.agentassistant.flutter.flutterclient.proto.PendingMessage.class,
            "totalCount_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0001\u0000\u0001\u001b\u0002\u0004" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<code.agentassistant.flutter.flutterclient.proto.GetPendingMessagesResponse> parser = PARSER;
        if (parser == null) {
          synchronized (code.agentassistant.flutter.flutterclient.proto.GetPendingMessagesResponse.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<code.agentassistant.flutter.flutterclient.proto.GetPendingMessagesResponse>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:agentassistproto.GetPendingMessagesResponse)
  private static final code.agentassistant.flutter.flutterclient.proto.GetPendingMessagesResponse DEFAULT_INSTANCE;
  static {
    GetPendingMessagesResponse defaultInstance = new GetPendingMessagesResponse();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      GetPendingMessagesResponse.class, defaultInstance);
  }

  public static code.agentassistant.flutter.flutterclient.proto.GetPendingMessagesResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<GetPendingMessagesResponse> PARSER;

  public static com.google.protobuf.Parser<GetPendingMessagesResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

