// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agentassist.proto
// Protobuf Java Version: 4.36.0

package code.agentassistant.flutter.flutterclient.proto;

@com.google.protobuf.Generated
public interface ImageContentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:agentassistproto.ImageContent)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * Must be "image"
   * </pre>
   *
   * <code>string type = 1;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <pre>
   * Must be "image"
   * </pre>
   *
   * <code>string type = 1;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <pre>
   * Base64-encoded image data
   * </pre>
   *
   * <code>string data = 2;</code>
   * @return The data.
   */
  java.lang.String getData();
  /**
   * <pre>
   * Base64-encoded image data
   * </pre>
   *
   * <code>string data = 2;</code>
   * @return The bytes for data.
   */
  com.google.protobuf.ByteString
      getDataBytes();

  /**
   * <pre>
   * MIME type of the image
   * </pre>
   *
   * <code>string mime_type = 3;</code>
   * @return The mimeType.
   */
  java.lang.String getMimeType();
  /**
   * <pre>
   * MIME type of the image
   * </pre>
   *
   * <code>string mime_type = 3;</code>
   * @return The bytes for mimeType.
   */
  com.google.protobuf.ByteString
      getMimeTypeBytes();
}
