// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agentassist.proto
// Protobuf Java Version: 4.36.0

package code.agentassistant.flutter.flutterclient.proto;

@com.google.protobuf.Generated
public interface McpClientInfoDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:agentassistproto.McpClientInfoData)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * MCP protocol version requested by client
   * </pre>
   *
   * <code>string ProtocolVersion = 1;</code>
   * @return The protocolVersion.
   */
  java.lang.String getProtocolVersion();
  /**
   * <pre>
   * MCP protocol version requested by client
   * </pre>
   *
   * <code>string ProtocolVersion = 1;</code>
   * @return The bytes for protocolVersion.
   */
  com.google.protobuf.ByteString
      getProtocolVersionBytes();

  /**
   * <pre>
   * Raw JSON describing client capabilities (mcp.InitializeParams.capabilities)
   * </pre>
   *
   * <code>string CapabilitiesJson = 2;</code>
   * @return The capabilitiesJson.
   */
  java.lang.String getCapabilitiesJson();
  /**
   * <pre>
   * Raw JSON describing client capabilities (mcp.InitializeParams.capabilities)
   * </pre>
   *
   * <code>string CapabilitiesJson = 2;</code>
   * @return The bytes for capabilitiesJson.
   */
  com.google.protobuf.ByteString
      getCapabilitiesJsonBytes();

  /**
   * <pre>
   * MCP client implementation name
   * </pre>
   *
   * <code>string ClientName = 3;</code>
   * @return The clientName.
   */
  java.lang.String getClientName();
  /**
   * <pre>
   * MCP client implementation name
   * </pre>
   *
   * <code>string ClientName = 3;</code>
   * @return The bytes for clientName.
   */
  com.google.protobuf.ByteString
      getClientNameBytes();

  /**
   * <pre>
   * MCP client implementation version
   * </pre>
   *
   * <code>string ClientVersion = 4;</code>
   * @return The clientVersion.
   */
  java.lang.String getClientVersion();
  /**
   * <pre>
   * MCP client implementation version
   * </pre>
   *
   * <code>string ClientVersion = 4;</code>
   * @return The bytes for clientVersion.
   */
  com.google.protobuf.ByteString
      getClientVersionBytes();
}
