// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agentassist.proto
// Protobuf Java Version: 4.36.0

package code.agentassistant.flutter.flutterclient.proto;

/**
 * Protobuf type {@code agentassistproto.McpHeartbeatResponse}
 */
@com.google.protobuf.Generated
public  final class McpHeartbeatResponse extends
    com.google.protobuf.GeneratedMessageLite<
        McpHeartbeatResponse, McpHeartbeatResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:agentassistproto.McpHeartbeatResponse)
    McpHeartbeatResponseOrBuilder {
  private McpHeartbeatResponse() {
  }
  public static final int SUCCESS_FIELD_NUMBER = 1;
  private boolean success_;
  /**
   * <code>bool Success = 1;</code>
   * @return The success.
   */
  @java.lang.Override
  public boolean getSuccess() {
    return success_;
  }
  /**
   * <code>bool Success = 1;</code>
   * @param value The success to set.
   */
  private void setSuccess(boolean value) {
    
    success_ = value;
  }
  /**
   * <code>bool Success = 1;</code>
   */
  private void clearSuccess() {

    success_ = false;
  }

  public static code.agentassistant.flutter.flutterclient.proto.McpHeartbeatResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static code.agentassistant.flutter.flutterclient.proto.McpHeartbeatResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static code.agentassistant.flutter.flutterclient.proto.McpHeartbeatResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static code.agentassistant.flutter.flutterclient.proto.McpHeartbeatResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static code.agentassistant.flutter.flutterclient.proto.McpHeartbeatResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static code.agentassistant.flutter.flutterclient.proto.McpHeartbeatResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static code.agentassistant.flutter.flutterclient.proto.McpHeartbeatResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static code.agentassistant.flutter.flutterclient.proto.McpHeartbeatResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static code.agentassistant.flutter.flutterclient.proto.McpHeartbeatResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static code.agentassistant.flutter.flutterclient.proto.McpHeartbeatResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static code.agentassistant.flutter.flutterclient.proto.McpHeartbeatResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static code.agentassistant.flutter.flutterclient.proto.McpHeartbeatResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(code.agentassistant.flutter.flutterclient.proto.McpHeartbeatResponse prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code agentassistproto.McpHeartbeatResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        code.agentassistant.flutter.flutterclient.proto.McpHeartbeatResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:agentassistproto.McpHeartbeatResponse)
      code.agentassistant.flutter.flutterclient.proto.McpHeartbeatResponseOrBuilder {
    // Construct using code.agentassistant.flutter.flutterclient.proto.McpHeartbeatResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>bool Success = 1;</code>
     * @return The success.
     */
    @java.lang.Override
    public boolean getSuccess() {
      return instance.getSuccess();
    }
    /**
     * <code>bool Success = 1;</code>
     * @param value The success to set.
     * @return This builder for chaining.
     */
    public Builder setSuccess(boolean value) {
      copyOnWrite();
      instance.setSuccess(value);
      return this;
    }
    /**
     * <code>bool Success = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSuccess() {
      copyOnWrite();
      instance.clearSuccess();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:agentassistproto.McpHeartbeatResponse)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new code.agentassistant.flutter.flutterclient.proto.McpHeartbeatResponse();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "success_",
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0007";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<code.agentassistant.flutter.flutterclient.proto.McpHeartbeatResponse> parser = PARSER;
        if (parser == null) {
          synchronized (code.agentassistant.flutter.flutterclient.proto.McpHeartbeatResponse.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<code.agentassistant.flutter.flutterclient.proto.McpHeartbeatResponse>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:agentassistproto.McpHeartbeatResponse)
  private static final code.agentassistant.flutter.flutterclient.proto.McpHeartbeatResponse DEFAULT_INSTANCE;
  static {
    McpHeartbeatResponse defaultInstance = new McpHeartbeatResponse();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      McpHeartbeatResponse.class, defaultInstance);
  }

  public static code.agentassistant.flutter.flutterclient.proto.McpHeartbeatResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<McpHeartbeatResponse> PARSER;

  public static com.google.protobuf.Parser<McpHeartbeatResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

