// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agentassist.proto
// Protobuf Java Version: 4.36.0

package code.agentassistant.flutter.flutterclient.proto;

@com.google.protobuf.Generated
public interface McpResultContentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:agentassistproto.McpResultContent)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * content type
   * 1: text
   * 2: image
   * 3: audio
   * 4: embedded resource
   * </pre>
   *
   * <code>int32 type = 1;</code>
   * @return The type.
   */
  int getType();

  /**
   * <pre>
   * text
   * </pre>
   *
   * <code>.agentassistproto.TextContent text = 2;</code>
   * @return Whether the text field is set.
   */
  boolean hasText();
  /**
   * <pre>
   * text
   * </pre>
   *
   * <code>.agentassistproto.TextContent text = 2;</code>
   * @return The text.
   */
  code.agentassistant.flutter.flutterclient.proto.TextContent getText();

  /**
   * <pre>
   * image
   * </pre>
   *
   * <code>.agentassistproto.ImageContent image = 3;</code>
   * @return Whether the image field is set.
   */
  boolean hasImage();
  /**
   * <pre>
   * image
   * </pre>
   *
   * <code>.agentassistproto.ImageContent image = 3;</code>
   * @return The image.
   */
  code.agentassistant.flutter.flutterclient.proto.ImageContent getImage();

  /**
   * <pre>
   * audio
   * </pre>
   *
   * <code>.agentassistproto.AudioContent audio = 4;</code>
   * @return Whether the audio field is set.
   */
  boolean hasAudio();
  /**
   * <pre>
   * audio
   * </pre>
   *
   * <code>.agentassistproto.AudioContent audio = 4;</code>
   * @return The audio.
   */
  code.agentassistant.flutter.flutterclient.proto.AudioContent getAudio();

  /**
   * <pre>
   * embedded resource
   * </pre>
   *
   * <code>.agentassistproto.EmbeddedResource embedded_resource = 5;</code>
   * @return Whether the embeddedResource field is set.
   */
  boolean hasEmbeddedResource();
  /**
   * <pre>
   * embedded resource
   * </pre>
   *
   * <code>.agentassistproto.EmbeddedResource embedded_resource = 5;</code>
   * @return The embeddedResource.
   */
  code.agentassistant.flutter.flutterclient.proto.EmbeddedResource getEmbeddedResource();
}
