// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agentassist.proto
// Protobuf Java Version: 4.36.0

package code.agentassistant.flutter.flutterclient.proto;

@com.google.protobuf.Generated
public interface McpWorkReportRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:agentassistproto.McpWorkReportRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * current project directory
   * </pre>
   *
   * <code>string ProjectDirectory = 1;</code>
   * @return The projectDirectory.
   */
  java.lang.String getProjectDirectory();
  /**
   * <pre>
   * current project directory
   * </pre>
   *
   * <code>string ProjectDirectory = 1;</code>
   * @return The bytes for projectDirectory.
   */
  com.google.protobuf.ByteString
      getProjectDirectoryBytes();

  /**
   * <pre>
   * ai agent's work report summary
   * </pre>
   *
   * <code>string Summary = 2;</code>
   * @return The summary.
   */
  java.lang.String getSummary();
  /**
   * <pre>
   * ai agent's work report summary
   * </pre>
   *
   * <code>string Summary = 2;</code>
   * @return The bytes for summary.
   */
  com.google.protobuf.ByteString
      getSummaryBytes();

  /**
   * <pre>
   * timeout in seconds, default is 600s
   * </pre>
   *
   * <code>int32 Timeout = 3;</code>
   * @return The timeout.
   */
  int getTimeout();

  /**
   * <pre>
   * the AI agent/client name that is calling this tool (e.g., Antigravity,
   * Cascade)
   * </pre>
   *
   * <code>string AgentName = 4;</code>
   * @return The agentName.
   */
  java.lang.String getAgentName();
  /**
   * <pre>
   * the AI agent/client name that is calling this tool (e.g., Antigravity,
   * Cascade)
   * </pre>
   *
   * <code>string AgentName = 4;</code>
   * @return The bytes for agentName.
   */
  com.google.protobuf.ByteString
      getAgentNameBytes();

  /**
   * <pre>
   * the actual LLM/inference model name being used for this task (e.g., GPT-4,
   * Gemini 3 Pro)
   * </pre>
   *
   * <code>string ReasoningModelName = 5;</code>
   * @return The reasoningModelName.
   */
  java.lang.String getReasoningModelName();
  /**
   * <pre>
   * the actual LLM/inference model name being used for this task (e.g., GPT-4,
   * Gemini 3 Pro)
   * </pre>
   *
   * <code>string ReasoningModelName = 5;</code>
   * @return The bytes for reasoningModelName.
   */
  com.google.protobuf.ByteString
      getReasoningModelNameBytes();

  /**
   * <pre>
   * MCP client name from initialize.clientInfo.name (e.g., windsurf)
   * </pre>
   *
   * <code>string McpClientName = 6;</code>
   * @return The mcpClientName.
   */
  java.lang.String getMcpClientName();
  /**
   * <pre>
   * MCP client name from initialize.clientInfo.name (e.g., windsurf)
   * </pre>
   *
   * <code>string McpClientName = 6;</code>
   * @return The bytes for mcpClientName.
   */
  com.google.protobuf.ByteString
      getMcpClientNameBytes();
}
