// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agentassist.proto
// Protobuf Java Version: 4.36.0

package code.agentassistant.flutter.flutterclient.proto;

/**
 * Protobuf type {@code agentassistproto.McpWorkReportRequest}
 */
@com.google.protobuf.Generated
public  final class McpWorkReportRequest extends
    com.google.protobuf.GeneratedMessageLite<
        McpWorkReportRequest, McpWorkReportRequest.Builder> implements
    // @@protoc_insertion_point(message_implements:agentassistproto.McpWorkReportRequest)
    McpWorkReportRequestOrBuilder {
  private McpWorkReportRequest() {
    projectDirectory_ = "";
    summary_ = "";
    agentName_ = "";
    reasoningModelName_ = "";
    mcpClientName_ = "";
  }
  public static final int PROJECTDIRECTORY_FIELD_NUMBER = 1;
  private java.lang.String projectDirectory_;
  /**
   * <pre>
   * current project directory
   * </pre>
   *
   * <code>string ProjectDirectory = 1;</code>
   * @return The projectDirectory.
   */
  @java.lang.Override
  public java.lang.String getProjectDirectory() {
    return projectDirectory_;
  }
  /**
   * <pre>
   * current project directory
   * </pre>
   *
   * <code>string ProjectDirectory = 1;</code>
   * @return The bytes for projectDirectory.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getProjectDirectoryBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(projectDirectory_);
  }
  /**
   * <pre>
   * current project directory
   * </pre>
   *
   * <code>string ProjectDirectory = 1;</code>
   * @param value The projectDirectory to set.
   */
  private void setProjectDirectory(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    projectDirectory_ = value;
  }
  /**
   * <pre>
   * current project directory
   * </pre>
   *
   * <code>string ProjectDirectory = 1;</code>
   */
  private void clearProjectDirectory() {

    projectDirectory_ = getDefaultInstance().getProjectDirectory();
  }
  /**
   * <pre>
   * current project directory
   * </pre>
   *
   * <code>string ProjectDirectory = 1;</code>
   * @param value The bytes for projectDirectory to set.
   */
  private void setProjectDirectoryBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    projectDirectory_ = value.toStringUtf8();

  }

  public static final int SUMMARY_FIELD_NUMBER = 2;
  private java.lang.String summary_;
  /**
   * <pre>
   * ai agent's work report summary
   * </pre>
   *
   * <code>string Summary = 2;</code>
   * @return The summary.
   */
  @java.lang.Override
  public java.lang.String getSummary() {
    return summary_;
  }
  /**
   * <pre>
   * ai agent's work report summary
   * </pre>
   *
   * <code>string Summary = 2;</code>
   * @return The bytes for summary.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSummaryBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(summary_);
  }
  /**
   * <pre>
   * ai agent's work report summary
   * </pre>
   *
   * <code>string Summary = 2;</code>
   * @param value The summary to set.
   */
  private void setSummary(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    summary_ = value;
  }
  /**
   * <pre>
   * ai agent's work report summary
   * </pre>
   *
   * <code>string Summary = 2;</code>
   */
  private void clearSummary() {

    summary_ = getDefaultInstance().getSummary();
  }
  /**
   * <pre>
   * ai agent's work report summary
   * </pre>
   *
   * <code>string Summary = 2;</code>
   * @param value The bytes for summary to set.
   */
  private void setSummaryBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    summary_ = value.toStringUtf8();

  }

  public static final int TIMEOUT_FIELD_NUMBER = 3;
  private int timeout_;
  /**
   * <pre>
   * timeout in seconds, default is 600s
   * </pre>
   *
   * <code>int32 Timeout = 3;</code>
   * @return The timeout.
   */
  @java.lang.Override
  public int getTimeout() {
    return timeout_;
  }
  /**
   * <pre>
   * timeout in seconds, default is 600s
   * </pre>
   *
   * <code>int32 Timeout = 3;</code>
   * @param value The timeout to set.
   */
  private void setTimeout(int value) {
    
    timeout_ = value;
  }
  /**
   * <pre>
   * timeout in seconds, default is 600s
   * </pre>
   *
   * <code>int32 Timeout = 3;</code>
   */
  private void clearTimeout() {

    timeout_ = 0;
  }

  public static final int AGENTNAME_FIELD_NUMBER = 4;
  private java.lang.String agentName_;
  /**
   * <pre>
   * the AI agent/client name that is calling this tool (e.g., Antigravity,
   * Cascade)
   * </pre>
   *
   * <code>string AgentName = 4;</code>
   * @return The agentName.
   */
  @java.lang.Override
  public java.lang.String getAgentName() {
    return agentName_;
  }
  /**
   * <pre>
   * the AI agent/client name that is calling this tool (e.g., Antigravity,
   * Cascade)
   * </pre>
   *
   * <code>string AgentName = 4;</code>
   * @return The bytes for agentName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAgentNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(agentName_);
  }
  /**
   * <pre>
   * the AI agent/client name that is calling this tool (e.g., Antigravity,
   * Cascade)
   * </pre>
   *
   * <code>string AgentName = 4;</code>
   * @param value The agentName to set.
   */
  private void setAgentName(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    agentName_ = value;
  }
  /**
   * <pre>
   * the AI agent/client name that is calling this tool (e.g., Antigravity,
   * Cascade)
   * </pre>
   *
   * <code>string AgentName = 4;</code>
   */
  private void clearAgentName() {

    agentName_ = getDefaultInstance().getAgentName();
  }
  /**
   * <pre>
   * the AI agent/client name that is calling this tool (e.g., Antigravity,
   * Cascade)
   * </pre>
   *
   * <code>string AgentName = 4;</code>
   * @param value The bytes for agentName to set.
   */
  private void setAgentNameBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    agentName_ = value.toStringUtf8();

  }

  public static final int REASONINGMODELNAME_FIELD_NUMBER = 5;
  private java.lang.String reasoningModelName_;
  /**
   * <pre>
   * the actual LLM/inference model name being used for this task (e.g., GPT-4,
   * Gemini 3 Pro)
   * </pre>
   *
   * <code>string ReasoningModelName = 5;</code>
   * @return The reasoningModelName.
   */
  @java.lang.Override
  public java.lang.String getReasoningModelName() {
    return reasoningModelName_;
  }
  /**
   * <pre>
   * the actual LLM/inference model name being used for this task (e.g., GPT-4,
   * Gemini 3 Pro)
   * </pre>
   *
   * <code>string ReasoningModelName = 5;</code>
   * @return The bytes for reasoningModelName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getReasoningModelNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(reasoningModelName_);
  }
  /**
   * <pre>
   * the actual LLM/inference model name being used for this task (e.g., GPT-4,
   * Gemini 3 Pro)
   * </pre>
   *
   * <code>string ReasoningModelName = 5;</code>
   * @param value The reasoningModelName to set.
   */
  private void setReasoningModelName(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    reasoningModelName_ = value;
  }
  /**
   * <pre>
   * the actual LLM/inference model name being used for this task (e.g., GPT-4,
   * Gemini 3 Pro)
   * </pre>
   *
   * <code>string ReasoningModelName = 5;</code>
   */
  private void clearReasoningModelName() {

    reasoningModelName_ = getDefaultInstance().getReasoningModelName();
  }
  /**
   * <pre>
   * the actual LLM/inference model name being used for this task (e.g., GPT-4,
   * Gemini 3 Pro)
   * </pre>
   *
   * <code>string ReasoningModelName = 5;</code>
   * @param value The bytes for reasoningModelName to set.
   */
  private void setReasoningModelNameBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    reasoningModelName_ = value.toStringUtf8();

  }

  public static final int MCPCLIENTNAME_FIELD_NUMBER = 6;
  private java.lang.String mcpClientName_;
  /**
   * <pre>
   * MCP client name from initialize.clientInfo.name (e.g., windsurf)
   * </pre>
   *
   * <code>string McpClientName = 6;</code>
   * @return The mcpClientName.
   */
  @java.lang.Override
  public java.lang.String getMcpClientName() {
    return mcpClientName_;
  }
  /**
   * <pre>
   * MCP client name from initialize.clientInfo.name (e.g., windsurf)
   * </pre>
   *
   * <code>string McpClientName = 6;</code>
   * @return The bytes for mcpClientName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMcpClientNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(mcpClientName_);
  }
  /**
   * <pre>
   * MCP client name from initialize.clientInfo.name (e.g., windsurf)
   * </pre>
   *
   * <code>string McpClientName = 6;</code>
   * @param value The mcpClientName to set.
   */
  private void setMcpClientName(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    mcpClientName_ = value;
  }
  /**
   * <pre>
   * MCP client name from initialize.clientInfo.name (e.g., windsurf)
   * </pre>
   *
   * <code>string McpClientName = 6;</code>
   */
  private void clearMcpClientName() {

    mcpClientName_ = getDefaultInstance().getMcpClientName();
  }
  /**
   * <pre>
   * MCP client name from initialize.clientInfo.name (e.g., windsurf)
   * </pre>
   *
   * <code>string McpClientName = 6;</code>
   * @param value The bytes for mcpClientName to set.
   */
  private void setMcpClientNameBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    mcpClientName_ = value.toStringUtf8();

  }

  public static code.agentassistant.flutter.flutterclient.proto.McpWorkReportRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static code.agentassistant.flutter.flutterclient.proto.McpWorkReportRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static code.agentassistant.flutter.flutterclient.proto.McpWorkReportRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static code.agentassistant.flutter.flutterclient.proto.McpWorkReportRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static code.agentassistant.flutter.flutterclient.proto.McpWorkReportRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static code.agentassistant.flutter.flutterclient.proto.McpWorkReportRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static code.agentassistant.flutter.flutterclient.proto.McpWorkReportRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static code.agentassistant.flutter.flutterclient.proto.McpWorkReportRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static code.agentassistant.flutter.flutterclient.proto.McpWorkReportRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static code.agentassistant.flutter.flutterclient.proto.McpWorkReportRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static code.agentassistant.flutter.flutterclient.proto.McpWorkReportRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static code.agentassistant.flutter.flutterclient.proto.McpWorkReportRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(code.agentassistant.flutter.flutterclient.proto.McpWorkReportRequest prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code agentassistproto.McpWorkReportRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        code.agentassistant.flutter.flutterclient.proto.McpWorkReportRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:agentassistproto.McpWorkReportRequest)
      code.agentassistant.flutter.flutterclient.proto.McpWorkReportRequestOrBuilder {
    // Construct using code.agentassistant.flutter.flutterclient.proto.McpWorkReportRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * current project directory
     * </pre>
     *
     * <code>string ProjectDirectory = 1;</code>
     * @return The projectDirectory.
     */
    @java.lang.Override
    public java.lang.String getProjectDirectory() {
      return instance.getProjectDirectory();
    }
    /**
     * <pre>
     * current project directory
     * </pre>
     *
     * <code>string ProjectDirectory = 1;</code>
     * @return The bytes for projectDirectory.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getProjectDirectoryBytes() {
      return instance.getProjectDirectoryBytes();
    }
    /**
     * <pre>
     * current project directory
     * </pre>
     *
     * <code>string ProjectDirectory = 1;</code>
     * @param value The projectDirectory to set.
     * @return This builder for chaining.
     */
    public Builder setProjectDirectory(
        java.lang.String value) {
      copyOnWrite();
      instance.setProjectDirectory(value);
      return this;
    }
    /**
     * <pre>
     * current project directory
     * </pre>
     *
     * <code>string ProjectDirectory = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearProjectDirectory() {
      copyOnWrite();
      instance.clearProjectDirectory();
      return this;
    }
    /**
     * <pre>
     * current project directory
     * </pre>
     *
     * <code>string ProjectDirectory = 1;</code>
     * @param value The bytes for projectDirectory to set.
     * @return This builder for chaining.
     */
    public Builder setProjectDirectoryBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setProjectDirectoryBytes(value);
      return this;
    }

    /**
     * <pre>
     * ai agent's work report summary
     * </pre>
     *
     * <code>string Summary = 2;</code>
     * @return The summary.
     */
    @java.lang.Override
    public java.lang.String getSummary() {
      return instance.getSummary();
    }
    /**
     * <pre>
     * ai agent's work report summary
     * </pre>
     *
     * <code>string Summary = 2;</code>
     * @return The bytes for summary.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSummaryBytes() {
      return instance.getSummaryBytes();
    }
    /**
     * <pre>
     * ai agent's work report summary
     * </pre>
     *
     * <code>string Summary = 2;</code>
     * @param value The summary to set.
     * @return This builder for chaining.
     */
    public Builder setSummary(
        java.lang.String value) {
      copyOnWrite();
      instance.setSummary(value);
      return this;
    }
    /**
     * <pre>
     * ai agent's work report summary
     * </pre>
     *
     * <code>string Summary = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSummary() {
      copyOnWrite();
      instance.clearSummary();
      return this;
    }
    /**
     * <pre>
     * ai agent's work report summary
     * </pre>
     *
     * <code>string Summary = 2;</code>
     * @param value The bytes for summary to set.
     * @return This builder for chaining.
     */
    public Builder setSummaryBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setSummaryBytes(value);
      return this;
    }

    /**
     * <pre>
     * timeout in seconds, default is 600s
     * </pre>
     *
     * <code>int32 Timeout = 3;</code>
     * @return The timeout.
     */
    @java.lang.Override
    public int getTimeout() {
      return instance.getTimeout();
    }
    /**
     * <pre>
     * timeout in seconds, default is 600s
     * </pre>
     *
     * <code>int32 Timeout = 3;</code>
     * @param value The timeout to set.
     * @return This builder for chaining.
     */
    public Builder setTimeout(int value) {
      copyOnWrite();
      instance.setTimeout(value);
      return this;
    }
    /**
     * <pre>
     * timeout in seconds, default is 600s
     * </pre>
     *
     * <code>int32 Timeout = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimeout() {
      copyOnWrite();
      instance.clearTimeout();
      return this;
    }

    /**
     * <pre>
     * the AI agent/client name that is calling this tool (e.g., Antigravity,
     * Cascade)
     * </pre>
     *
     * <code>string AgentName = 4;</code>
     * @return The agentName.
     */
    @java.lang.Override
    public java.lang.String getAgentName() {
      return instance.getAgentName();
    }
    /**
     * <pre>
     * the AI agent/client name that is calling this tool (e.g., Antigravity,
     * Cascade)
     * </pre>
     *
     * <code>string AgentName = 4;</code>
     * @return The bytes for agentName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAgentNameBytes() {
      return instance.getAgentNameBytes();
    }
    /**
     * <pre>
     * the AI agent/client name that is calling this tool (e.g., Antigravity,
     * Cascade)
     * </pre>
     *
     * <code>string AgentName = 4;</code>
     * @param value The agentName to set.
     * @return This builder for chaining.
     */
    public Builder setAgentName(
        java.lang.String value) {
      copyOnWrite();
      instance.setAgentName(value);
      return this;
    }
    /**
     * <pre>
     * the AI agent/client name that is calling this tool (e.g., Antigravity,
     * Cascade)
     * </pre>
     *
     * <code>string AgentName = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearAgentName() {
      copyOnWrite();
      instance.clearAgentName();
      return this;
    }
    /**
     * <pre>
     * the AI agent/client name that is calling this tool (e.g., Antigravity,
     * Cascade)
     * </pre>
     *
     * <code>string AgentName = 4;</code>
     * @param value The bytes for agentName to set.
     * @return This builder for chaining.
     */
    public Builder setAgentNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setAgentNameBytes(value);
      return this;
    }

    /**
     * <pre>
     * the actual LLM/inference model name being used for this task (e.g., GPT-4,
     * Gemini 3 Pro)
     * </pre>
     *
     * <code>string ReasoningModelName = 5;</code>
     * @return The reasoningModelName.
     */
    @java.lang.Override
    public java.lang.String getReasoningModelName() {
      return instance.getReasoningModelName();
    }
    /**
     * <pre>
     * the actual LLM/inference model name being used for this task (e.g., GPT-4,
     * Gemini 3 Pro)
     * </pre>
     *
     * <code>string ReasoningModelName = 5;</code>
     * @return The bytes for reasoningModelName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getReasoningModelNameBytes() {
      return instance.getReasoningModelNameBytes();
    }
    /**
     * <pre>
     * the actual LLM/inference model name being used for this task (e.g., GPT-4,
     * Gemini 3 Pro)
     * </pre>
     *
     * <code>string ReasoningModelName = 5;</code>
     * @param value The reasoningModelName to set.
     * @return This builder for chaining.
     */
    public Builder setReasoningModelName(
        java.lang.String value) {
      copyOnWrite();
      instance.setReasoningModelName(value);
      return this;
    }
    /**
     * <pre>
     * the actual LLM/inference model name being used for this task (e.g., GPT-4,
     * Gemini 3 Pro)
     * </pre>
     *
     * <code>string ReasoningModelName = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearReasoningModelName() {
      copyOnWrite();
      instance.clearReasoningModelName();
      return this;
    }
    /**
     * <pre>
     * the actual LLM/inference model name being used for this task (e.g., GPT-4,
     * Gemini 3 Pro)
     * </pre>
     *
     * <code>string ReasoningModelName = 5;</code>
     * @param value The bytes for reasoningModelName to set.
     * @return This builder for chaining.
     */
    public Builder setReasoningModelNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setReasoningModelNameBytes(value);
      return this;
    }

    /**
     * <pre>
     * MCP client name from initialize.clientInfo.name (e.g., windsurf)
     * </pre>
     *
     * <code>string McpClientName = 6;</code>
     * @return The mcpClientName.
     */
    @java.lang.Override
    public java.lang.String getMcpClientName() {
      return instance.getMcpClientName();
    }
    /**
     * <pre>
     * MCP client name from initialize.clientInfo.name (e.g., windsurf)
     * </pre>
     *
     * <code>string McpClientName = 6;</code>
     * @return The bytes for mcpClientName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMcpClientNameBytes() {
      return instance.getMcpClientNameBytes();
    }
    /**
     * <pre>
     * MCP client name from initialize.clientInfo.name (e.g., windsurf)
     * </pre>
     *
     * <code>string McpClientName = 6;</code>
     * @param value The mcpClientName to set.
     * @return This builder for chaining.
     */
    public Builder setMcpClientName(
        java.lang.String value) {
      copyOnWrite();
      instance.setMcpClientName(value);
      return this;
    }
    /**
     * <pre>
     * MCP client name from initialize.clientInfo.name (e.g., windsurf)
     * </pre>
     *
     * <code>string McpClientName = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearMcpClientName() {
      copyOnWrite();
      instance.clearMcpClientName();
      return this;
    }
    /**
     * <pre>
     * MCP client name from initialize.clientInfo.name (e.g., windsurf)
     * </pre>
     *
     * <code>string McpClientName = 6;</code>
     * @param value The bytes for mcpClientName to set.
     * @return This builder for chaining.
     */
    public Builder setMcpClientNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setMcpClientNameBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:agentassistproto.McpWorkReportRequest)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new code.agentassistant.flutter.flutterclient.proto.McpWorkReportRequest();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "projectDirectory_",
            "summary_",
            "timeout_",
            "agentName_",
            "reasoningModelName_",
            "mcpClientName_",
          };
          java.lang.String info =
              "\u0000\u0006\u0000\u0000\u0001\u0006\u0006\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
              "\u0003\u0004\u0004\u0208\u0005\u0208\u0006\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<code.agentassistant.flutter.flutterclient.proto.McpWorkReportRequest> parser = PARSER;
        if (parser == null) {
          synchronized (code.agentassistant.flutter.flutterclient.proto.McpWorkReportRequest.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<code.agentassistant.flutter.flutterclient.proto.McpWorkReportRequest>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:agentassistproto.McpWorkReportRequest)
  private static final code.agentassistant.flutter.flutterclient.proto.McpWorkReportRequest DEFAULT_INSTANCE;
  static {
    McpWorkReportRequest defaultInstance = new McpWorkReportRequest();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      McpWorkReportRequest.class, defaultInstance);
  }

  public static code.agentassistant.flutter.flutterclient.proto.McpWorkReportRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<McpWorkReportRequest> PARSER;

  public static com.google.protobuf.Parser<McpWorkReportRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

