// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agentassist.proto
// Protobuf Java Version: 4.36.0

package code.agentassistant.flutter.flutterclient.proto;

/**
 * Protobuf type {@code agentassistproto.MsgEmpty}
 */
@com.google.protobuf.Generated
public  final class MsgEmpty extends
    com.google.protobuf.GeneratedMessageLite<
        MsgEmpty, MsgEmpty.Builder> implements
    // @@protoc_insertion_point(message_implements:agentassistproto.MsgEmpty)
    MsgEmptyOrBuilder {
  private MsgEmpty() {
  }
  public static code.agentassistant.flutter.flutterclient.proto.MsgEmpty parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static code.agentassistant.flutter.flutterclient.proto.MsgEmpty parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static code.agentassistant.flutter.flutterclient.proto.MsgEmpty parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static code.agentassistant.flutter.flutterclient.proto.MsgEmpty parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static code.agentassistant.flutter.flutterclient.proto.MsgEmpty parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static code.agentassistant.flutter.flutterclient.proto.MsgEmpty parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static code.agentassistant.flutter.flutterclient.proto.MsgEmpty parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static code.agentassistant.flutter.flutterclient.proto.MsgEmpty parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static code.agentassistant.flutter.flutterclient.proto.MsgEmpty parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static code.agentassistant.flutter.flutterclient.proto.MsgEmpty parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static code.agentassistant.flutter.flutterclient.proto.MsgEmpty parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static code.agentassistant.flutter.flutterclient.proto.MsgEmpty parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(code.agentassistant.flutter.flutterclient.proto.MsgEmpty prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code agentassistproto.MsgEmpty}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        code.agentassistant.flutter.flutterclient.proto.MsgEmpty, Builder> implements
      // @@protoc_insertion_point(builder_implements:agentassistproto.MsgEmpty)
      code.agentassistant.flutter.flutterclient.proto.MsgEmptyOrBuilder {
    // Construct using code.agentassistant.flutter.flutterclient.proto.MsgEmpty.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    // @@protoc_insertion_point(builder_scope:agentassistproto.MsgEmpty)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new code.agentassistant.flutter.flutterclient.proto.MsgEmpty();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = null;
          java.lang.String info =
              "\u0000\u0000";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<code.agentassistant.flutter.flutterclient.proto.MsgEmpty> parser = PARSER;
        if (parser == null) {
          synchronized (code.agentassistant.flutter.flutterclient.proto.MsgEmpty.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<code.agentassistant.flutter.flutterclient.proto.MsgEmpty>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:agentassistproto.MsgEmpty)
  private static final code.agentassistant.flutter.flutterclient.proto.MsgEmpty DEFAULT_INSTANCE;
  static {
    MsgEmpty defaultInstance = new MsgEmpty();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      MsgEmpty.class, defaultInstance);
  }

  public static code.agentassistant.flutter.flutterclient.proto.MsgEmpty getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<MsgEmpty> PARSER;

  public static com.google.protobuf.Parser<MsgEmpty> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

