// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agentassist.proto
// Protobuf Java Version: 4.36.0

package code.agentassistant.flutter.flutterclient.proto;

@com.google.protobuf.Generated
public interface MsgEmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:agentassistproto.MsgEmpty)
    com.google.protobuf.MessageLiteOrBuilder {
}
