// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agentassist.proto
// Protobuf Java Version: 4.36.0

package code.agentassistant.flutter.flutterclient.proto;

@com.google.protobuf.Generated
public interface OnlineUserOrBuilder extends
    // @@protoc_insertion_point(interface_extends:agentassistproto.OnlineUser)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * client id
   * </pre>
   *
   * <code>string client_id = 1;</code>
   * @return The clientId.
   */
  java.lang.String getClientId();
  /**
   * <pre>
   * client id
   * </pre>
   *
   * <code>string client_id = 1;</code>
   * @return The bytes for clientId.
   */
  com.google.protobuf.ByteString
      getClientIdBytes();

  /**
   * <pre>
   * user nickname
   * </pre>
   *
   * <code>string nickname = 2;</code>
   * @return The nickname.
   */
  java.lang.String getNickname();
  /**
   * <pre>
   * user nickname
   * </pre>
   *
   * <code>string nickname = 2;</code>
   * @return The bytes for nickname.
   */
  com.google.protobuf.ByteString
      getNicknameBytes();

  /**
   * <pre>
   * connection timestamp
   * </pre>
   *
   * <code>int64 connected_at = 3;</code>
   * @return The connectedAt.
   */
  long getConnectedAt();
}
