// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agentassist.proto
// Protobuf Java Version: 4.36.0

package code.agentassistant.flutter.flutterclient.proto;

/**
 * <pre>
 * PendingMessage represents a single pending message
 * </pre>
 *
 * Protobuf type {@code agentassistproto.PendingMessage}
 */
@com.google.protobuf.Generated
public  final class PendingMessage extends
    com.google.protobuf.GeneratedMessageLite<
        PendingMessage, PendingMessage.Builder> implements
    // @@protoc_insertion_point(message_implements:agentassistproto.PendingMessage)
    PendingMessageOrBuilder {
  private PendingMessage() {
    messageType_ = "";
  }
  private int bitField0_;
  public static final int MESSAGE_TYPE_FIELD_NUMBER = 1;
  private java.lang.String messageType_;
  /**
   * <pre>
   * message type: "AskQuestion" or "WorkReport"
   * </pre>
   *
   * <code>string message_type = 1;</code>
   * @return The messageType.
   */
  @java.lang.Override
  public java.lang.String getMessageType() {
    return messageType_;
  }
  /**
   * <pre>
   * message type: "AskQuestion" or "WorkReport"
   * </pre>
   *
   * <code>string message_type = 1;</code>
   * @return The bytes for messageType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMessageTypeBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(messageType_);
  }
  /**
   * <pre>
   * message type: "AskQuestion" or "WorkReport"
   * </pre>
   *
   * <code>string message_type = 1;</code>
   * @param value The messageType to set.
   */
  private void setMessageType(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    messageType_ = value;
  }
  /**
   * <pre>
   * message type: "AskQuestion" or "WorkReport"
   * </pre>
   *
   * <code>string message_type = 1;</code>
   */
  private void clearMessageType() {

    messageType_ = getDefaultInstance().getMessageType();
  }
  /**
   * <pre>
   * message type: "AskQuestion" or "WorkReport"
   * </pre>
   *
   * <code>string message_type = 1;</code>
   * @param value The bytes for messageType to set.
   */
  private void setMessageTypeBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    messageType_ = value.toStringUtf8();

  }

  public static final int ASK_QUESTION_REQUEST_FIELD_NUMBER = 2;
  private code.agentassistant.flutter.flutterclient.proto.AskQuestionRequest askQuestionRequest_;
  /**
   * <pre>
   * ask question request (if message_type is "AskQuestion")
   * </pre>
   *
   * <code>.agentassistproto.AskQuestionRequest ask_question_request = 2;</code>
   */
  @java.lang.Override
  public boolean hasAskQuestionRequest() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * ask question request (if message_type is "AskQuestion")
   * </pre>
   *
   * <code>.agentassistproto.AskQuestionRequest ask_question_request = 2;</code>
   */
  @java.lang.Override
  public code.agentassistant.flutter.flutterclient.proto.AskQuestionRequest getAskQuestionRequest() {
    return askQuestionRequest_ == null ? code.agentassistant.flutter.flutterclient.proto.AskQuestionRequest.getDefaultInstance() : askQuestionRequest_;
  }
  /**
   * <pre>
   * ask question request (if message_type is "AskQuestion")
   * </pre>
   *
   * <code>.agentassistproto.AskQuestionRequest ask_question_request = 2;</code>
   */
  private void setAskQuestionRequest(code.agentassistant.flutter.flutterclient.proto.AskQuestionRequest value) {
    java.util.Objects.requireNonNull(value);
    askQuestionRequest_ = value;
    bitField0_ |= 0x00000001;
  }
  /**
   * <pre>
   * ask question request (if message_type is "AskQuestion")
   * </pre>
   *
   * <code>.agentassistproto.AskQuestionRequest ask_question_request = 2;</code>
   */
  @java.lang.SuppressWarnings("ReferenceEquality")
  private void mergeAskQuestionRequest(code.agentassistant.flutter.flutterclient.proto.AskQuestionRequest value) {
    java.util.Objects.requireNonNull(value);
    if (askQuestionRequest_ != null &&
        askQuestionRequest_ != code.agentassistant.flutter.flutterclient.proto.AskQuestionRequest.getDefaultInstance()) {
      askQuestionRequest_ =
        code.agentassistant.flutter.flutterclient.proto.AskQuestionRequest.newBuilder(askQuestionRequest_).mergeFrom(value).buildPartial();
    } else {
      askQuestionRequest_ = value;
    }
    bitField0_ |= 0x00000001;
  }
  /**
   * <pre>
   * ask question request (if message_type is "AskQuestion")
   * </pre>
   *
   * <code>.agentassistproto.AskQuestionRequest ask_question_request = 2;</code>
   */
  private void clearAskQuestionRequest() {
    askQuestionRequest_ = null;
    bitField0_ = (bitField0_ & ~0x00000001);
  }

  public static final int WORK_REPORT_REQUEST_FIELD_NUMBER = 3;
  private code.agentassistant.flutter.flutterclient.proto.WorkReportRequest workReportRequest_;
  /**
   * <pre>
   * work report request (if message_type is "WorkReport")
   * </pre>
   *
   * <code>.agentassistproto.WorkReportRequest work_report_request = 3;</code>
   */
  @java.lang.Override
  public boolean hasWorkReportRequest() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * work report request (if message_type is "WorkReport")
   * </pre>
   *
   * <code>.agentassistproto.WorkReportRequest work_report_request = 3;</code>
   */
  @java.lang.Override
  public code.agentassistant.flutter.flutterclient.proto.WorkReportRequest getWorkReportRequest() {
    return workReportRequest_ == null ? code.agentassistant.flutter.flutterclient.proto.WorkReportRequest.getDefaultInstance() : workReportRequest_;
  }
  /**
   * <pre>
   * work report request (if message_type is "WorkReport")
   * </pre>
   *
   * <code>.agentassistproto.WorkReportRequest work_report_request = 3;</code>
   */
  private void setWorkReportRequest(code.agentassistant.flutter.flutterclient.proto.WorkReportRequest value) {
    java.util.Objects.requireNonNull(value);
    workReportRequest_ = value;
    bitField0_ |= 0x00000002;
  }
  /**
   * <pre>
   * work report request (if message_type is "WorkReport")
   * </pre>
   *
   * <code>.agentassistproto.WorkReportRequest work_report_request = 3;</code>
   */
  @java.lang.SuppressWarnings("ReferenceEquality")
  private void mergeWorkReportRequest(code.agentassistant.flutter.flutterclient.proto.WorkReportRequest value) {
    java.util.Objects.requireNonNull(value);
    if (workReportRequest_ != null &&
        workReportRequest_ != code.agentassistant.flutter.flutterclient.proto.WorkReportRequest.getDefaultInstance()) {
      workReportRequest_ =
        code.agentassistant.flutter.flutterclient.proto.WorkReportRequest.newBuilder(workReportRequest_).mergeFrom(value).buildPartial();
    } else {
      workReportRequest_ = value;
    }
    bitField0_ |= 0x00000002;
  }
  /**
   * <pre>
   * work report request (if message_type is "WorkReport")
   * </pre>
   *
   * <code>.agentassistproto.WorkReportRequest work_report_request = 3;</code>
   */
  private void clearWorkReportRequest() {
    workReportRequest_ = null;
    bitField0_ = (bitField0_ & ~0x00000002);
  }

  public static final int CREATED_AT_FIELD_NUMBER = 4;
  private long createdAt_;
  /**
   * <pre>
   * timestamp when the message was created
   * </pre>
   *
   * <code>int64 created_at = 4;</code>
   * @return The createdAt.
   */
  @java.lang.Override
  public long getCreatedAt() {
    return createdAt_;
  }
  /**
   * <pre>
   * timestamp when the message was created
   * </pre>
   *
   * <code>int64 created_at = 4;</code>
   * @param value The createdAt to set.
   */
  private void setCreatedAt(long value) {
    
    createdAt_ = value;
  }
  /**
   * <pre>
   * timestamp when the message was created
   * </pre>
   *
   * <code>int64 created_at = 4;</code>
   */
  private void clearCreatedAt() {

    createdAt_ = 0L;
  }

  public static final int TIMEOUT_FIELD_NUMBER = 5;
  private int timeout_;
  /**
   * <pre>
   * timeout in seconds
   * </pre>
   *
   * <code>int32 timeout = 5;</code>
   * @return The timeout.
   */
  @java.lang.Override
  public int getTimeout() {
    return timeout_;
  }
  /**
   * <pre>
   * timeout in seconds
   * </pre>
   *
   * <code>int32 timeout = 5;</code>
   * @param value The timeout to set.
   */
  private void setTimeout(int value) {
    
    timeout_ = value;
  }
  /**
   * <pre>
   * timeout in seconds
   * </pre>
   *
   * <code>int32 timeout = 5;</code>
   */
  private void clearTimeout() {

    timeout_ = 0;
  }

  public static code.agentassistant.flutter.flutterclient.proto.PendingMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static code.agentassistant.flutter.flutterclient.proto.PendingMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static code.agentassistant.flutter.flutterclient.proto.PendingMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static code.agentassistant.flutter.flutterclient.proto.PendingMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static code.agentassistant.flutter.flutterclient.proto.PendingMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static code.agentassistant.flutter.flutterclient.proto.PendingMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static code.agentassistant.flutter.flutterclient.proto.PendingMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static code.agentassistant.flutter.flutterclient.proto.PendingMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static code.agentassistant.flutter.flutterclient.proto.PendingMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static code.agentassistant.flutter.flutterclient.proto.PendingMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static code.agentassistant.flutter.flutterclient.proto.PendingMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static code.agentassistant.flutter.flutterclient.proto.PendingMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(code.agentassistant.flutter.flutterclient.proto.PendingMessage prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * PendingMessage represents a single pending message
   * </pre>
   *
   * Protobuf type {@code agentassistproto.PendingMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        code.agentassistant.flutter.flutterclient.proto.PendingMessage, Builder> implements
      // @@protoc_insertion_point(builder_implements:agentassistproto.PendingMessage)
      code.agentassistant.flutter.flutterclient.proto.PendingMessageOrBuilder {
    // Construct using code.agentassistant.flutter.flutterclient.proto.PendingMessage.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * message type: "AskQuestion" or "WorkReport"
     * </pre>
     *
     * <code>string message_type = 1;</code>
     * @return The messageType.
     */
    @java.lang.Override
    public java.lang.String getMessageType() {
      return instance.getMessageType();
    }
    /**
     * <pre>
     * message type: "AskQuestion" or "WorkReport"
     * </pre>
     *
     * <code>string message_type = 1;</code>
     * @return The bytes for messageType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageTypeBytes() {
      return instance.getMessageTypeBytes();
    }
    /**
     * <pre>
     * message type: "AskQuestion" or "WorkReport"
     * </pre>
     *
     * <code>string message_type = 1;</code>
     * @param value The messageType to set.
     * @return This builder for chaining.
     */
    public Builder setMessageType(
        java.lang.String value) {
      copyOnWrite();
      instance.setMessageType(value);
      return this;
    }
    /**
     * <pre>
     * message type: "AskQuestion" or "WorkReport"
     * </pre>
     *
     * <code>string message_type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessageType() {
      copyOnWrite();
      instance.clearMessageType();
      return this;
    }
    /**
     * <pre>
     * message type: "AskQuestion" or "WorkReport"
     * </pre>
     *
     * <code>string message_type = 1;</code>
     * @param value The bytes for messageType to set.
     * @return This builder for chaining.
     */
    public Builder setMessageTypeBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setMessageTypeBytes(value);
      return this;
    }

    /**
     * <pre>
     * ask question request (if message_type is "AskQuestion")
     * </pre>
     *
     * <code>.agentassistproto.AskQuestionRequest ask_question_request = 2;</code>
     */
    @java.lang.Override
    public boolean hasAskQuestionRequest() {
      return instance.hasAskQuestionRequest();
    }
    /**
     * <pre>
     * ask question request (if message_type is "AskQuestion")
     * </pre>
     *
     * <code>.agentassistproto.AskQuestionRequest ask_question_request = 2;</code>
     */
    @java.lang.Override
    public code.agentassistant.flutter.flutterclient.proto.AskQuestionRequest getAskQuestionRequest() {
      return instance.getAskQuestionRequest();
    }
    /**
     * <pre>
     * ask question request (if message_type is "AskQuestion")
     * </pre>
     *
     * <code>.agentassistproto.AskQuestionRequest ask_question_request = 2;</code>
     */
    public Builder setAskQuestionRequest(code.agentassistant.flutter.flutterclient.proto.AskQuestionRequest value) {
      copyOnWrite();
      instance.setAskQuestionRequest(value);
      return this;
      }
    /**
     * <pre>
     * ask question request (if message_type is "AskQuestion")
     * </pre>
     *
     * <code>.agentassistproto.AskQuestionRequest ask_question_request = 2;</code>
     */
    public Builder setAskQuestionRequest(
        code.agentassistant.flutter.flutterclient.proto.AskQuestionRequest.Builder builderForValue) {
      copyOnWrite();
      instance.setAskQuestionRequest(builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * ask question request (if message_type is "AskQuestion")
     * </pre>
     *
     * <code>.agentassistproto.AskQuestionRequest ask_question_request = 2;</code>
     */
    public Builder mergeAskQuestionRequest(code.agentassistant.flutter.flutterclient.proto.AskQuestionRequest value) {
      copyOnWrite();
      instance.mergeAskQuestionRequest(value);
      return this;
    }
    /**
     * <pre>
     * ask question request (if message_type is "AskQuestion")
     * </pre>
     *
     * <code>.agentassistproto.AskQuestionRequest ask_question_request = 2;</code>
     */
    public Builder clearAskQuestionRequest() {  copyOnWrite();
      instance.clearAskQuestionRequest();
      return this;
    }

    /**
     * <pre>
     * work report request (if message_type is "WorkReport")
     * </pre>
     *
     * <code>.agentassistproto.WorkReportRequest work_report_request = 3;</code>
     */
    @java.lang.Override
    public boolean hasWorkReportRequest() {
      return instance.hasWorkReportRequest();
    }
    /**
     * <pre>
     * work report request (if message_type is "WorkReport")
     * </pre>
     *
     * <code>.agentassistproto.WorkReportRequest work_report_request = 3;</code>
     */
    @java.lang.Override
    public code.agentassistant.flutter.flutterclient.proto.WorkReportRequest getWorkReportRequest() {
      return instance.getWorkReportRequest();
    }
    /**
     * <pre>
     * work report request (if message_type is "WorkReport")
     * </pre>
     *
     * <code>.agentassistproto.WorkReportRequest work_report_request = 3;</code>
     */
    public Builder setWorkReportRequest(code.agentassistant.flutter.flutterclient.proto.WorkReportRequest value) {
      copyOnWrite();
      instance.setWorkReportRequest(value);
      return this;
      }
    /**
     * <pre>
     * work report request (if message_type is "WorkReport")
     * </pre>
     *
     * <code>.agentassistproto.WorkReportRequest work_report_request = 3;</code>
     */
    public Builder setWorkReportRequest(
        code.agentassistant.flutter.flutterclient.proto.WorkReportRequest.Builder builderForValue) {
      copyOnWrite();
      instance.setWorkReportRequest(builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * work report request (if message_type is "WorkReport")
     * </pre>
     *
     * <code>.agentassistproto.WorkReportRequest work_report_request = 3;</code>
     */
    public Builder mergeWorkReportRequest(code.agentassistant.flutter.flutterclient.proto.WorkReportRequest value) {
      copyOnWrite();
      instance.mergeWorkReportRequest(value);
      return this;
    }
    /**
     * <pre>
     * work report request (if message_type is "WorkReport")
     * </pre>
     *
     * <code>.agentassistproto.WorkReportRequest work_report_request = 3;</code>
     */
    public Builder clearWorkReportRequest() {  copyOnWrite();
      instance.clearWorkReportRequest();
      return this;
    }

    /**
     * <pre>
     * timestamp when the message was created
     * </pre>
     *
     * <code>int64 created_at = 4;</code>
     * @return The createdAt.
     */
    @java.lang.Override
    public long getCreatedAt() {
      return instance.getCreatedAt();
    }
    /**
     * <pre>
     * timestamp when the message was created
     * </pre>
     *
     * <code>int64 created_at = 4;</code>
     * @param value The createdAt to set.
     * @return This builder for chaining.
     */
    public Builder setCreatedAt(long value) {
      copyOnWrite();
      instance.setCreatedAt(value);
      return this;
    }
    /**
     * <pre>
     * timestamp when the message was created
     * </pre>
     *
     * <code>int64 created_at = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearCreatedAt() {
      copyOnWrite();
      instance.clearCreatedAt();
      return this;
    }

    /**
     * <pre>
     * timeout in seconds
     * </pre>
     *
     * <code>int32 timeout = 5;</code>
     * @return The timeout.
     */
    @java.lang.Override
    public int getTimeout() {
      return instance.getTimeout();
    }
    /**
     * <pre>
     * timeout in seconds
     * </pre>
     *
     * <code>int32 timeout = 5;</code>
     * @param value The timeout to set.
     * @return This builder for chaining.
     */
    public Builder setTimeout(int value) {
      copyOnWrite();
      instance.setTimeout(value);
      return this;
    }
    /**
     * <pre>
     * timeout in seconds
     * </pre>
     *
     * <code>int32 timeout = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimeout() {
      copyOnWrite();
      instance.clearTimeout();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:agentassistproto.PendingMessage)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new code.agentassistant.flutter.flutterclient.proto.PendingMessage();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "messageType_",
            "askQuestionRequest_",
            "workReportRequest_",
            "createdAt_",
            "timeout_",
          };
          java.lang.String info =
              "\u0000\u0005\u0000\u0001\u0001\u0005\u0005\u0000\u0000\u0000\u0001\u0208\u0002\u1009" +
              "\u0000\u0003\u1009\u0001\u0004\u0002\u0005\u0004";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<code.agentassistant.flutter.flutterclient.proto.PendingMessage> parser = PARSER;
        if (parser == null) {
          synchronized (code.agentassistant.flutter.flutterclient.proto.PendingMessage.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<code.agentassistant.flutter.flutterclient.proto.PendingMessage>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:agentassistproto.PendingMessage)
  private static final code.agentassistant.flutter.flutterclient.proto.PendingMessage DEFAULT_INSTANCE;
  static {
    PendingMessage defaultInstance = new PendingMessage();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      PendingMessage.class, defaultInstance);
  }

  public static code.agentassistant.flutter.flutterclient.proto.PendingMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<PendingMessage> PARSER;

  public static com.google.protobuf.Parser<PendingMessage> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

