// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agentassist.proto
// Protobuf Java Version: 4.36.0

package code.agentassistant.flutter.flutterclient.proto;

@com.google.protobuf.Generated
public interface PendingMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:agentassistproto.PendingMessage)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * message type: "AskQuestion" or "WorkReport"
   * </pre>
   *
   * <code>string message_type = 1;</code>
   * @return The messageType.
   */
  java.lang.String getMessageType();
  /**
   * <pre>
   * message type: "AskQuestion" or "WorkReport"
   * </pre>
   *
   * <code>string message_type = 1;</code>
   * @return The bytes for messageType.
   */
  com.google.protobuf.ByteString
      getMessageTypeBytes();

  /**
   * <pre>
   * ask question request (if message_type is "AskQuestion")
   * </pre>
   *
   * <code>.agentassistproto.AskQuestionRequest ask_question_request = 2;</code>
   * @return Whether the askQuestionRequest field is set.
   */
  boolean hasAskQuestionRequest();
  /**
   * <pre>
   * ask question request (if message_type is "AskQuestion")
   * </pre>
   *
   * <code>.agentassistproto.AskQuestionRequest ask_question_request = 2;</code>
   * @return The askQuestionRequest.
   */
  code.agentassistant.flutter.flutterclient.proto.AskQuestionRequest getAskQuestionRequest();

  /**
   * <pre>
   * work report request (if message_type is "WorkReport")
   * </pre>
   *
   * <code>.agentassistproto.WorkReportRequest work_report_request = 3;</code>
   * @return Whether the workReportRequest field is set.
   */
  boolean hasWorkReportRequest();
  /**
   * <pre>
   * work report request (if message_type is "WorkReport")
   * </pre>
   *
   * <code>.agentassistproto.WorkReportRequest work_report_request = 3;</code>
   * @return The workReportRequest.
   */
  code.agentassistant.flutter.flutterclient.proto.WorkReportRequest getWorkReportRequest();

  /**
   * <pre>
   * timestamp when the message was created
   * </pre>
   *
   * <code>int64 created_at = 4;</code>
   * @return The createdAt.
   */
  long getCreatedAt();

  /**
   * <pre>
   * timeout in seconds
   * </pre>
   *
   * <code>int32 timeout = 5;</code>
   * @return The timeout.
   */
  int getTimeout();
}
