// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agentassist.proto
// Protobuf Java Version: 4.36.0

package code.agentassistant.flutter.flutterclient.proto;

@com.google.protobuf.Generated
public interface QuestionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:agentassistproto.Question)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * Complete question
   * </pre>
   *
   * <code>string question = 1;</code>
   * @return The question.
   */
  java.lang.String getQuestion();
  /**
   * <pre>
   * Complete question
   * </pre>
   *
   * <code>string question = 1;</code>
   * @return The bytes for question.
   */
  com.google.protobuf.ByteString
      getQuestionBytes();

  /**
   * <pre>
   * Very short label
   * </pre>
   *
   * <code>string header = 2;</code>
   * @return The header.
   */
  java.lang.String getHeader();
  /**
   * <pre>
   * Very short label
   * </pre>
   *
   * <code>string header = 2;</code>
   * @return The bytes for header.
   */
  com.google.protobuf.ByteString
      getHeaderBytes();

  /**
   * <pre>
   * Available choices
   * </pre>
   *
   * <code>repeated .agentassistproto.Option options = 3;</code>
   */
  java.util.List<code.agentassistant.flutter.flutterclient.proto.Option> 
      getOptionsList();
  /**
   * <pre>
   * Available choices
   * </pre>
   *
   * <code>repeated .agentassistproto.Option options = 3;</code>
   */
  code.agentassistant.flutter.flutterclient.proto.Option getOptions(int index);
  /**
   * <pre>
   * Available choices
   * </pre>
   *
   * <code>repeated .agentassistproto.Option options = 3;</code>
   */
  int getOptionsCount();

  /**
   * <pre>
   * Allow selecting multiple choices
   * </pre>
   *
   * <code>bool multiple = 4;</code>
   * @return The multiple.
   */
  boolean getMultiple();

  /**
   * <pre>
   * Allow typing a custom answer
   * </pre>
   *
   * <code>bool custom = 5;</code>
   * @return The custom.
   */
  boolean getCustom();
}
