// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agentassist.proto
// Protobuf Java Version: 4.36.0

package code.agentassistant.flutter.flutterclient.proto;

/**
 * <pre>
 * RequestCancelledNotification represents a notification that a request has
 * been cancelled
 * </pre>
 *
 * Protobuf type {@code agentassistproto.RequestCancelledNotification}
 */
@com.google.protobuf.Generated
public  final class RequestCancelledNotification extends
    com.google.protobuf.GeneratedMessageLite<
        RequestCancelledNotification, RequestCancelledNotification.Builder> implements
    // @@protoc_insertion_point(message_implements:agentassistproto.RequestCancelledNotification)
    RequestCancelledNotificationOrBuilder {
  private RequestCancelledNotification() {
    requestId_ = "";
    reason_ = "";
    messageType_ = "";
  }
  public static final int REQUEST_ID_FIELD_NUMBER = 1;
  private java.lang.String requestId_;
  /**
   * <pre>
   * request id that was cancelled
   * </pre>
   *
   * <code>string request_id = 1;</code>
   * @return The requestId.
   */
  @java.lang.Override
  public java.lang.String getRequestId() {
    return requestId_;
  }
  /**
   * <pre>
   * request id that was cancelled
   * </pre>
   *
   * <code>string request_id = 1;</code>
   * @return The bytes for requestId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRequestIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(requestId_);
  }
  /**
   * <pre>
   * request id that was cancelled
   * </pre>
   *
   * <code>string request_id = 1;</code>
   * @param value The requestId to set.
   */
  private void setRequestId(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    requestId_ = value;
  }
  /**
   * <pre>
   * request id that was cancelled
   * </pre>
   *
   * <code>string request_id = 1;</code>
   */
  private void clearRequestId() {

    requestId_ = getDefaultInstance().getRequestId();
  }
  /**
   * <pre>
   * request id that was cancelled
   * </pre>
   *
   * <code>string request_id = 1;</code>
   * @param value The bytes for requestId to set.
   */
  private void setRequestIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    requestId_ = value.toStringUtf8();

  }

  public static final int REASON_FIELD_NUMBER = 2;
  private java.lang.String reason_;
  /**
   * <pre>
   * reason for cancellation
   * </pre>
   *
   * <code>string reason = 2;</code>
   * @return The reason.
   */
  @java.lang.Override
  public java.lang.String getReason() {
    return reason_;
  }
  /**
   * <pre>
   * reason for cancellation
   * </pre>
   *
   * <code>string reason = 2;</code>
   * @return The bytes for reason.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getReasonBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(reason_);
  }
  /**
   * <pre>
   * reason for cancellation
   * </pre>
   *
   * <code>string reason = 2;</code>
   * @param value The reason to set.
   */
  private void setReason(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    reason_ = value;
  }
  /**
   * <pre>
   * reason for cancellation
   * </pre>
   *
   * <code>string reason = 2;</code>
   */
  private void clearReason() {

    reason_ = getDefaultInstance().getReason();
  }
  /**
   * <pre>
   * reason for cancellation
   * </pre>
   *
   * <code>string reason = 2;</code>
   * @param value The bytes for reason to set.
   */
  private void setReasonBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    reason_ = value.toStringUtf8();

  }

  public static final int MESSAGE_TYPE_FIELD_NUMBER = 3;
  private java.lang.String messageType_;
  /**
   * <pre>
   * message type: "AskQuestion" or "WorkReport"
   * </pre>
   *
   * <code>string message_type = 3;</code>
   * @return The messageType.
   */
  @java.lang.Override
  public java.lang.String getMessageType() {
    return messageType_;
  }
  /**
   * <pre>
   * message type: "AskQuestion" or "WorkReport"
   * </pre>
   *
   * <code>string message_type = 3;</code>
   * @return The bytes for messageType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMessageTypeBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(messageType_);
  }
  /**
   * <pre>
   * message type: "AskQuestion" or "WorkReport"
   * </pre>
   *
   * <code>string message_type = 3;</code>
   * @param value The messageType to set.
   */
  private void setMessageType(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    messageType_ = value;
  }
  /**
   * <pre>
   * message type: "AskQuestion" or "WorkReport"
   * </pre>
   *
   * <code>string message_type = 3;</code>
   */
  private void clearMessageType() {

    messageType_ = getDefaultInstance().getMessageType();
  }
  /**
   * <pre>
   * message type: "AskQuestion" or "WorkReport"
   * </pre>
   *
   * <code>string message_type = 3;</code>
   * @param value The bytes for messageType to set.
   */
  private void setMessageTypeBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    messageType_ = value.toStringUtf8();

  }

  public static code.agentassistant.flutter.flutterclient.proto.RequestCancelledNotification parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static code.agentassistant.flutter.flutterclient.proto.RequestCancelledNotification parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static code.agentassistant.flutter.flutterclient.proto.RequestCancelledNotification parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static code.agentassistant.flutter.flutterclient.proto.RequestCancelledNotification parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static code.agentassistant.flutter.flutterclient.proto.RequestCancelledNotification parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static code.agentassistant.flutter.flutterclient.proto.RequestCancelledNotification parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static code.agentassistant.flutter.flutterclient.proto.RequestCancelledNotification parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static code.agentassistant.flutter.flutterclient.proto.RequestCancelledNotification parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static code.agentassistant.flutter.flutterclient.proto.RequestCancelledNotification parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static code.agentassistant.flutter.flutterclient.proto.RequestCancelledNotification parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static code.agentassistant.flutter.flutterclient.proto.RequestCancelledNotification parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static code.agentassistant.flutter.flutterclient.proto.RequestCancelledNotification parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(code.agentassistant.flutter.flutterclient.proto.RequestCancelledNotification prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * RequestCancelledNotification represents a notification that a request has
   * been cancelled
   * </pre>
   *
   * Protobuf type {@code agentassistproto.RequestCancelledNotification}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        code.agentassistant.flutter.flutterclient.proto.RequestCancelledNotification, Builder> implements
      // @@protoc_insertion_point(builder_implements:agentassistproto.RequestCancelledNotification)
      code.agentassistant.flutter.flutterclient.proto.RequestCancelledNotificationOrBuilder {
    // Construct using code.agentassistant.flutter.flutterclient.proto.RequestCancelledNotification.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * request id that was cancelled
     * </pre>
     *
     * <code>string request_id = 1;</code>
     * @return The requestId.
     */
    @java.lang.Override
    public java.lang.String getRequestId() {
      return instance.getRequestId();
    }
    /**
     * <pre>
     * request id that was cancelled
     * </pre>
     *
     * <code>string request_id = 1;</code>
     * @return The bytes for requestId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRequestIdBytes() {
      return instance.getRequestIdBytes();
    }
    /**
     * <pre>
     * request id that was cancelled
     * </pre>
     *
     * <code>string request_id = 1;</code>
     * @param value The requestId to set.
     * @return This builder for chaining.
     */
    public Builder setRequestId(
        java.lang.String value) {
      copyOnWrite();
      instance.setRequestId(value);
      return this;
    }
    /**
     * <pre>
     * request id that was cancelled
     * </pre>
     *
     * <code>string request_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRequestId() {
      copyOnWrite();
      instance.clearRequestId();
      return this;
    }
    /**
     * <pre>
     * request id that was cancelled
     * </pre>
     *
     * <code>string request_id = 1;</code>
     * @param value The bytes for requestId to set.
     * @return This builder for chaining.
     */
    public Builder setRequestIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setRequestIdBytes(value);
      return this;
    }

    /**
     * <pre>
     * reason for cancellation
     * </pre>
     *
     * <code>string reason = 2;</code>
     * @return The reason.
     */
    @java.lang.Override
    public java.lang.String getReason() {
      return instance.getReason();
    }
    /**
     * <pre>
     * reason for cancellation
     * </pre>
     *
     * <code>string reason = 2;</code>
     * @return The bytes for reason.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getReasonBytes() {
      return instance.getReasonBytes();
    }
    /**
     * <pre>
     * reason for cancellation
     * </pre>
     *
     * <code>string reason = 2;</code>
     * @param value The reason to set.
     * @return This builder for chaining.
     */
    public Builder setReason(
        java.lang.String value) {
      copyOnWrite();
      instance.setReason(value);
      return this;
    }
    /**
     * <pre>
     * reason for cancellation
     * </pre>
     *
     * <code>string reason = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearReason() {
      copyOnWrite();
      instance.clearReason();
      return this;
    }
    /**
     * <pre>
     * reason for cancellation
     * </pre>
     *
     * <code>string reason = 2;</code>
     * @param value The bytes for reason to set.
     * @return This builder for chaining.
     */
    public Builder setReasonBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setReasonBytes(value);
      return this;
    }

    /**
     * <pre>
     * message type: "AskQuestion" or "WorkReport"
     * </pre>
     *
     * <code>string message_type = 3;</code>
     * @return The messageType.
     */
    @java.lang.Override
    public java.lang.String getMessageType() {
      return instance.getMessageType();
    }
    /**
     * <pre>
     * message type: "AskQuestion" or "WorkReport"
     * </pre>
     *
     * <code>string message_type = 3;</code>
     * @return The bytes for messageType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageTypeBytes() {
      return instance.getMessageTypeBytes();
    }
    /**
     * <pre>
     * message type: "AskQuestion" or "WorkReport"
     * </pre>
     *
     * <code>string message_type = 3;</code>
     * @param value The messageType to set.
     * @return This builder for chaining.
     */
    public Builder setMessageType(
        java.lang.String value) {
      copyOnWrite();
      instance.setMessageType(value);
      return this;
    }
    /**
     * <pre>
     * message type: "AskQuestion" or "WorkReport"
     * </pre>
     *
     * <code>string message_type = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessageType() {
      copyOnWrite();
      instance.clearMessageType();
      return this;
    }
    /**
     * <pre>
     * message type: "AskQuestion" or "WorkReport"
     * </pre>
     *
     * <code>string message_type = 3;</code>
     * @param value The bytes for messageType to set.
     * @return This builder for chaining.
     */
    public Builder setMessageTypeBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setMessageTypeBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:agentassistproto.RequestCancelledNotification)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new code.agentassistant.flutter.flutterclient.proto.RequestCancelledNotification();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "requestId_",
            "reason_",
            "messageType_",
          };
          java.lang.String info =
              "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
              "\u0003\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<code.agentassistant.flutter.flutterclient.proto.RequestCancelledNotification> parser = PARSER;
        if (parser == null) {
          synchronized (code.agentassistant.flutter.flutterclient.proto.RequestCancelledNotification.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<code.agentassistant.flutter.flutterclient.proto.RequestCancelledNotification>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:agentassistproto.RequestCancelledNotification)
  private static final code.agentassistant.flutter.flutterclient.proto.RequestCancelledNotification DEFAULT_INSTANCE;
  static {
    RequestCancelledNotification defaultInstance = new RequestCancelledNotification();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      RequestCancelledNotification.class, defaultInstance);
  }

  public static code.agentassistant.flutter.flutterclient.proto.RequestCancelledNotification getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<RequestCancelledNotification> PARSER;

  public static com.google.protobuf.Parser<RequestCancelledNotification> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

