// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agentassist.proto
// Protobuf Java Version: 4.36.0

package code.agentassistant.flutter.flutterclient.proto;

@com.google.protobuf.Generated
public interface SendChatMessageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:agentassistproto.SendChatMessageRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * receiver client id
   * </pre>
   *
   * <code>string receiver_client_id = 1;</code>
   * @return The receiverClientId.
   */
  java.lang.String getReceiverClientId();
  /**
   * <pre>
   * receiver client id
   * </pre>
   *
   * <code>string receiver_client_id = 1;</code>
   * @return The bytes for receiverClientId.
   */
  com.google.protobuf.ByteString
      getReceiverClientIdBytes();

  /**
   * <pre>
   * message content
   * </pre>
   *
   * <code>string content = 2;</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <pre>
   * message content
   * </pre>
   *
   * <code>string content = 2;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <pre>
   * optional forward target to be used by receiver
   * </pre>
   *
   * <code>.agentassistproto.ForwardTarget forward_target = 3;</code>
   * @return Whether the forwardTarget field is set.
   */
  boolean hasForwardTarget();
  /**
   * <pre>
   * optional forward target to be used by receiver
   * </pre>
   *
   * <code>.agentassistproto.ForwardTarget forward_target = 3;</code>
   * @return The forwardTarget.
   */
  code.agentassistant.flutter.flutterclient.proto.ForwardTarget getForwardTarget();
}
