// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agentassist.proto
// Protobuf Java Version: 4.36.0

package code.agentassistant.flutter.flutterclient.proto;

@com.google.protobuf.Generated
public interface UserConnectionStatusNotificationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:agentassistproto.UserConnectionStatusNotification)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * the user who connected/disconnected
   * </pre>
   *
   * <code>.agentassistproto.OnlineUser user = 1;</code>
   * @return Whether the user field is set.
   */
  boolean hasUser();
  /**
   * <pre>
   * the user who connected/disconnected
   * </pre>
   *
   * <code>.agentassistproto.OnlineUser user = 1;</code>
   * @return The user.
   */
  code.agentassistant.flutter.flutterclient.proto.OnlineUser getUser();

  /**
   * <pre>
   * connection status: "connected" or "disconnected"
   * </pre>
   *
   * <code>string status = 2;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <pre>
   * connection status: "connected" or "disconnected"
   * </pre>
   *
   * <code>string status = 2;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <pre>
   * timestamp of the status change
   * </pre>
   *
   * <code>int64 timestamp = 3;</code>
   * @return The timestamp.
   */
  long getTimestamp();
}
