// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agentassist.proto
// Protobuf Java Version: 4.36.0

package code.agentassistant.flutter.flutterclient.proto;

/**
 * <pre>
 * UserLoginResponse represents the response to a user login
 * </pre>
 *
 * Protobuf type {@code agentassistproto.UserLoginResponse}
 */
@com.google.protobuf.Generated
public  final class UserLoginResponse extends
    com.google.protobuf.GeneratedMessageLite<
        UserLoginResponse, UserLoginResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:agentassistproto.UserLoginResponse)
    UserLoginResponseOrBuilder {
  private UserLoginResponse() {
    clientId_ = "";
    errorMessage_ = "";
  }
  public static final int CLIENT_ID_FIELD_NUMBER = 1;
  private java.lang.String clientId_;
  /**
   * <pre>
   * client id assigned by server
   * </pre>
   *
   * <code>string client_id = 1;</code>
   * @return The clientId.
   */
  @java.lang.Override
  public java.lang.String getClientId() {
    return clientId_;
  }
  /**
   * <pre>
   * client id assigned by server
   * </pre>
   *
   * <code>string client_id = 1;</code>
   * @return The bytes for clientId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getClientIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(clientId_);
  }
  /**
   * <pre>
   * client id assigned by server
   * </pre>
   *
   * <code>string client_id = 1;</code>
   * @param value The clientId to set.
   */
  private void setClientId(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    clientId_ = value;
  }
  /**
   * <pre>
   * client id assigned by server
   * </pre>
   *
   * <code>string client_id = 1;</code>
   */
  private void clearClientId() {

    clientId_ = getDefaultInstance().getClientId();
  }
  /**
   * <pre>
   * client id assigned by server
   * </pre>
   *
   * <code>string client_id = 1;</code>
   * @param value The bytes for clientId to set.
   */
  private void setClientIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    clientId_ = value.toStringUtf8();

  }

  public static final int SUCCESS_FIELD_NUMBER = 2;
  private boolean success_;
  /**
   * <pre>
   * success status
   * </pre>
   *
   * <code>bool success = 2;</code>
   * @return The success.
   */
  @java.lang.Override
  public boolean getSuccess() {
    return success_;
  }
  /**
   * <pre>
   * success status
   * </pre>
   *
   * <code>bool success = 2;</code>
   * @param value The success to set.
   */
  private void setSuccess(boolean value) {
    
    success_ = value;
  }
  /**
   * <pre>
   * success status
   * </pre>
   *
   * <code>bool success = 2;</code>
   */
  private void clearSuccess() {

    success_ = false;
  }

  public static final int ERROR_MESSAGE_FIELD_NUMBER = 3;
  private java.lang.String errorMessage_;
  /**
   * <pre>
   * error message if login failed
   * </pre>
   *
   * <code>string error_message = 3;</code>
   * @return The errorMessage.
   */
  @java.lang.Override
  public java.lang.String getErrorMessage() {
    return errorMessage_;
  }
  /**
   * <pre>
   * error message if login failed
   * </pre>
   *
   * <code>string error_message = 3;</code>
   * @return The bytes for errorMessage.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getErrorMessageBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(errorMessage_);
  }
  /**
   * <pre>
   * error message if login failed
   * </pre>
   *
   * <code>string error_message = 3;</code>
   * @param value The errorMessage to set.
   */
  private void setErrorMessage(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    errorMessage_ = value;
  }
  /**
   * <pre>
   * error message if login failed
   * </pre>
   *
   * <code>string error_message = 3;</code>
   */
  private void clearErrorMessage() {

    errorMessage_ = getDefaultInstance().getErrorMessage();
  }
  /**
   * <pre>
   * error message if login failed
   * </pre>
   *
   * <code>string error_message = 3;</code>
   * @param value The bytes for errorMessage to set.
   */
  private void setErrorMessageBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    errorMessage_ = value.toStringUtf8();

  }

  public static code.agentassistant.flutter.flutterclient.proto.UserLoginResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static code.agentassistant.flutter.flutterclient.proto.UserLoginResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static code.agentassistant.flutter.flutterclient.proto.UserLoginResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static code.agentassistant.flutter.flutterclient.proto.UserLoginResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static code.agentassistant.flutter.flutterclient.proto.UserLoginResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static code.agentassistant.flutter.flutterclient.proto.UserLoginResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static code.agentassistant.flutter.flutterclient.proto.UserLoginResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static code.agentassistant.flutter.flutterclient.proto.UserLoginResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static code.agentassistant.flutter.flutterclient.proto.UserLoginResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static code.agentassistant.flutter.flutterclient.proto.UserLoginResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static code.agentassistant.flutter.flutterclient.proto.UserLoginResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static code.agentassistant.flutter.flutterclient.proto.UserLoginResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(code.agentassistant.flutter.flutterclient.proto.UserLoginResponse prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * UserLoginResponse represents the response to a user login
   * </pre>
   *
   * Protobuf type {@code agentassistproto.UserLoginResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        code.agentassistant.flutter.flutterclient.proto.UserLoginResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:agentassistproto.UserLoginResponse)
      code.agentassistant.flutter.flutterclient.proto.UserLoginResponseOrBuilder {
    // Construct using code.agentassistant.flutter.flutterclient.proto.UserLoginResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * client id assigned by server
     * </pre>
     *
     * <code>string client_id = 1;</code>
     * @return The clientId.
     */
    @java.lang.Override
    public java.lang.String getClientId() {
      return instance.getClientId();
    }
    /**
     * <pre>
     * client id assigned by server
     * </pre>
     *
     * <code>string client_id = 1;</code>
     * @return The bytes for clientId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getClientIdBytes() {
      return instance.getClientIdBytes();
    }
    /**
     * <pre>
     * client id assigned by server
     * </pre>
     *
     * <code>string client_id = 1;</code>
     * @param value The clientId to set.
     * @return This builder for chaining.
     */
    public Builder setClientId(
        java.lang.String value) {
      copyOnWrite();
      instance.setClientId(value);
      return this;
    }
    /**
     * <pre>
     * client id assigned by server
     * </pre>
     *
     * <code>string client_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearClientId() {
      copyOnWrite();
      instance.clearClientId();
      return this;
    }
    /**
     * <pre>
     * client id assigned by server
     * </pre>
     *
     * <code>string client_id = 1;</code>
     * @param value The bytes for clientId to set.
     * @return This builder for chaining.
     */
    public Builder setClientIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setClientIdBytes(value);
      return this;
    }

    /**
     * <pre>
     * success status
     * </pre>
     *
     * <code>bool success = 2;</code>
     * @return The success.
     */
    @java.lang.Override
    public boolean getSuccess() {
      return instance.getSuccess();
    }
    /**
     * <pre>
     * success status
     * </pre>
     *
     * <code>bool success = 2;</code>
     * @param value The success to set.
     * @return This builder for chaining.
     */
    public Builder setSuccess(boolean value) {
      copyOnWrite();
      instance.setSuccess(value);
      return this;
    }
    /**
     * <pre>
     * success status
     * </pre>
     *
     * <code>bool success = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSuccess() {
      copyOnWrite();
      instance.clearSuccess();
      return this;
    }

    /**
     * <pre>
     * error message if login failed
     * </pre>
     *
     * <code>string error_message = 3;</code>
     * @return The errorMessage.
     */
    @java.lang.Override
    public java.lang.String getErrorMessage() {
      return instance.getErrorMessage();
    }
    /**
     * <pre>
     * error message if login failed
     * </pre>
     *
     * <code>string error_message = 3;</code>
     * @return The bytes for errorMessage.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getErrorMessageBytes() {
      return instance.getErrorMessageBytes();
    }
    /**
     * <pre>
     * error message if login failed
     * </pre>
     *
     * <code>string error_message = 3;</code>
     * @param value The errorMessage to set.
     * @return This builder for chaining.
     */
    public Builder setErrorMessage(
        java.lang.String value) {
      copyOnWrite();
      instance.setErrorMessage(value);
      return this;
    }
    /**
     * <pre>
     * error message if login failed
     * </pre>
     *
     * <code>string error_message = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearErrorMessage() {
      copyOnWrite();
      instance.clearErrorMessage();
      return this;
    }
    /**
     * <pre>
     * error message if login failed
     * </pre>
     *
     * <code>string error_message = 3;</code>
     * @param value The bytes for errorMessage to set.
     * @return This builder for chaining.
     */
    public Builder setErrorMessageBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setErrorMessageBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:agentassistproto.UserLoginResponse)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new code.agentassistant.flutter.flutterclient.proto.UserLoginResponse();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "clientId_",
            "success_",
            "errorMessage_",
          };
          java.lang.String info =
              "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u0208\u0002\u0007" +
              "\u0003\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<code.agentassistant.flutter.flutterclient.proto.UserLoginResponse> parser = PARSER;
        if (parser == null) {
          synchronized (code.agentassistant.flutter.flutterclient.proto.UserLoginResponse.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<code.agentassistant.flutter.flutterclient.proto.UserLoginResponse>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:agentassistproto.UserLoginResponse)
  private static final code.agentassistant.flutter.flutterclient.proto.UserLoginResponse DEFAULT_INSTANCE;
  static {
    UserLoginResponse defaultInstance = new UserLoginResponse();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      UserLoginResponse.class, defaultInstance);
  }

  public static code.agentassistant.flutter.flutterclient.proto.UserLoginResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<UserLoginResponse> PARSER;

  public static com.google.protobuf.Parser<UserLoginResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

