// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agentassist.proto
// Protobuf Java Version: 4.36.0

package code.agentassistant.flutter.flutterclient.proto;

/**
 * Protobuf type {@code agentassistproto.WorkReportResponse}
 */
@com.google.protobuf.Generated
public  final class WorkReportResponse extends
    com.google.protobuf.GeneratedMessageLite<
        WorkReportResponse, WorkReportResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:agentassistproto.WorkReportResponse)
    WorkReportResponseOrBuilder {
  private WorkReportResponse() {
    iD_ = "";
    contents_ = emptyProtobufList();
  }
  public static final int ID_FIELD_NUMBER = 1;
  private java.lang.String iD_;
  /**
   * <pre>
   * request id
   * </pre>
   *
   * <code>string ID = 1;</code>
   * @return The iD.
   */
  @java.lang.Override
  public java.lang.String getID() {
    return iD_;
  }
  /**
   * <pre>
   * request id
   * </pre>
   *
   * <code>string ID = 1;</code>
   * @return The bytes for iD.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIDBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(iD_);
  }
  /**
   * <pre>
   * request id
   * </pre>
   *
   * <code>string ID = 1;</code>
   * @param value The iD to set.
   */
  private void setID(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    iD_ = value;
  }
  /**
   * <pre>
   * request id
   * </pre>
   *
   * <code>string ID = 1;</code>
   */
  private void clearID() {

    iD_ = getDefaultInstance().getID();
  }
  /**
   * <pre>
   * request id
   * </pre>
   *
   * <code>string ID = 1;</code>
   * @param value The bytes for iD to set.
   */
  private void setIDBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    iD_ = value.toStringUtf8();

  }

  public static final int ISERROR_FIELD_NUMBER = 2;
  private boolean isError_;
  /**
   * <code>bool IsError = 2;</code>
   * @return The isError.
   */
  @java.lang.Override
  public boolean getIsError() {
    return isError_;
  }
  /**
   * <code>bool IsError = 2;</code>
   * @param value The isError to set.
   */
  private void setIsError(boolean value) {
    
    isError_ = value;
  }
  /**
   * <code>bool IsError = 2;</code>
   */
  private void clearIsError() {

    isError_ = false;
  }

  public static final int META_FIELD_NUMBER = 3;
  private static final class MetaDefaultEntryHolder {
    static final com.google.protobuf.MapEntryLite<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntryLite
            .<java.lang.String, java.lang.String>newDefaultInstance(
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapFieldLite<
      java.lang.String, java.lang.String> meta_ =
          com.google.protobuf.MapFieldLite.emptyMapField();
  private com.google.protobuf.MapFieldLite<java.lang.String, java.lang.String>
  internalGetMeta() {
    return meta_;
  }
  private com.google.protobuf.MapFieldLite<java.lang.String, java.lang.String>
  internalGetMutableMeta() {
    if (!meta_.isMutable()) {
      meta_ = meta_.mutableCopy();
    }
    return meta_;
  }
  @java.lang.Override

  public int getMetaCount() {
    return internalGetMeta().size();
  }
  /**
   * <code>map&lt;string, string&gt; Meta = 3;</code>
   */
  @java.lang.Override

  public boolean containsMeta(
      java.lang.String key) {
    java.util.Objects.requireNonNull(key);
    return internalGetMeta().containsKey(key);
  }
  /**
   * Use {@link #getMetaMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getMeta() {
    return getMetaMap();
  }
  /**
   * <code>map&lt;string, string&gt; Meta = 3;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.String, java.lang.String> getMetaMap() {
    return java.util.Collections.unmodifiableMap(
        internalGetMeta());
  }
  /**
   * <code>map&lt;string, string&gt; Meta = 3;</code>
   */
  @java.lang.Override

  public /* nullable */
java.lang.String getMetaOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue) {
    java.util.Objects.requireNonNull(key);
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetMeta();
    java.lang.String v = map.get(key);
    return v != null ? v : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; Meta = 3;</code>
   */
  @java.lang.Override

  public java.lang.String getMetaOrThrow(
      java.lang.String key) {
    java.util.Objects.requireNonNull(key);
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetMeta();
    java.lang.String v = map.get(key);
    if (v == null) {
      throw new java.lang.IllegalArgumentException();
    }
    return v;
  }
  /**
   * <code>map&lt;string, string&gt; Meta = 3;</code>
   */
  private java.util.Map<java.lang.String, java.lang.String>
  getMutableMetaMap() {
    return internalGetMutableMeta();
  }

  public static final int CONTENTS_FIELD_NUMBER = 4;
  private com.google.protobuf.Internal.ProtobufList<code.agentassistant.flutter.flutterclient.proto.McpResultContent> contents_;
  /**
   * <code>repeated .agentassistproto.McpResultContent contents = 4;</code>
   */
  @java.lang.Override
  public java.util.List<code.agentassistant.flutter.flutterclient.proto.McpResultContent> getContentsList() {
    return contents_;
  }
  /**
   * <code>repeated .agentassistproto.McpResultContent contents = 4;</code>
   */
  public java.util.List<? extends code.agentassistant.flutter.flutterclient.proto.McpResultContentOrBuilder> 
      getContentsOrBuilderList() {
    return contents_;
  }
  /**
   * <code>repeated .agentassistproto.McpResultContent contents = 4;</code>
   */
  @java.lang.Override
  public int getContentsCount() {
    return contents_.size();
  }
  /**
   * <code>repeated .agentassistproto.McpResultContent contents = 4;</code>
   */
  @java.lang.Override
  public code.agentassistant.flutter.flutterclient.proto.McpResultContent getContents(int index) {
    return contents_.get(index);
  }
  /**
   * <code>repeated .agentassistproto.McpResultContent contents = 4;</code>
   */
  public code.agentassistant.flutter.flutterclient.proto.McpResultContentOrBuilder getContentsOrBuilder(
      int index) {
    return contents_.get(index);
  }
  private void ensureContentsIsMutable() {
    com.google.protobuf.Internal.ProtobufList<code.agentassistant.flutter.flutterclient.proto.McpResultContent> tmp = contents_;
    if (!tmp.isModifiable()) {
      contents_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .agentassistproto.McpResultContent contents = 4;</code>
   */
  private void setContents(
      int index, code.agentassistant.flutter.flutterclient.proto.McpResultContent value) {
    java.util.Objects.requireNonNull(value);
    ensureContentsIsMutable();
    contents_.set(index, value);
  }
  /**
   * <code>repeated .agentassistproto.McpResultContent contents = 4;</code>
   */
  private void addContents(code.agentassistant.flutter.flutterclient.proto.McpResultContent value) {
    java.util.Objects.requireNonNull(value);
    ensureContentsIsMutable();
    contents_.add(value);
  }
  /**
   * <code>repeated .agentassistproto.McpResultContent contents = 4;</code>
   */
  private void addContents(
      int index, code.agentassistant.flutter.flutterclient.proto.McpResultContent value) {
    java.util.Objects.requireNonNull(value);
    ensureContentsIsMutable();
    contents_.add(index, value);
  }
  /**
   * <code>repeated .agentassistproto.McpResultContent contents = 4;</code>
   */
  private void addAllContents(
      java.lang.Iterable<? extends code.agentassistant.flutter.flutterclient.proto.McpResultContent> values) {
    ensureContentsIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, contents_);
  }
  /**
   * <code>repeated .agentassistproto.McpResultContent contents = 4;</code>
   */
  private void clearContents() {
    contents_ = emptyProtobufList();
  }
  /**
   * <code>repeated .agentassistproto.McpResultContent contents = 4;</code>
   */
  private void removeContents(int index) {
    ensureContentsIsMutable();
    contents_.remove(index);
  }

  public static code.agentassistant.flutter.flutterclient.proto.WorkReportResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static code.agentassistant.flutter.flutterclient.proto.WorkReportResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static code.agentassistant.flutter.flutterclient.proto.WorkReportResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static code.agentassistant.flutter.flutterclient.proto.WorkReportResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static code.agentassistant.flutter.flutterclient.proto.WorkReportResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static code.agentassistant.flutter.flutterclient.proto.WorkReportResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static code.agentassistant.flutter.flutterclient.proto.WorkReportResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static code.agentassistant.flutter.flutterclient.proto.WorkReportResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static code.agentassistant.flutter.flutterclient.proto.WorkReportResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static code.agentassistant.flutter.flutterclient.proto.WorkReportResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static code.agentassistant.flutter.flutterclient.proto.WorkReportResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static code.agentassistant.flutter.flutterclient.proto.WorkReportResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(code.agentassistant.flutter.flutterclient.proto.WorkReportResponse prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code agentassistproto.WorkReportResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        code.agentassistant.flutter.flutterclient.proto.WorkReportResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:agentassistproto.WorkReportResponse)
      code.agentassistant.flutter.flutterclient.proto.WorkReportResponseOrBuilder {
    // Construct using code.agentassistant.flutter.flutterclient.proto.WorkReportResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * request id
     * </pre>
     *
     * <code>string ID = 1;</code>
     * @return The iD.
     */
    @java.lang.Override
    public java.lang.String getID() {
      return instance.getID();
    }
    /**
     * <pre>
     * request id
     * </pre>
     *
     * <code>string ID = 1;</code>
     * @return The bytes for iD.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIDBytes() {
      return instance.getIDBytes();
    }
    /**
     * <pre>
     * request id
     * </pre>
     *
     * <code>string ID = 1;</code>
     * @param value The iD to set.
     * @return This builder for chaining.
     */
    public Builder setID(
        java.lang.String value) {
      copyOnWrite();
      instance.setID(value);
      return this;
    }
    /**
     * <pre>
     * request id
     * </pre>
     *
     * <code>string ID = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearID() {
      copyOnWrite();
      instance.clearID();
      return this;
    }
    /**
     * <pre>
     * request id
     * </pre>
     *
     * <code>string ID = 1;</code>
     * @param value The bytes for iD to set.
     * @return This builder for chaining.
     */
    public Builder setIDBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setIDBytes(value);
      return this;
    }

    /**
     * <code>bool IsError = 2;</code>
     * @return The isError.
     */
    @java.lang.Override
    public boolean getIsError() {
      return instance.getIsError();
    }
    /**
     * <code>bool IsError = 2;</code>
     * @param value The isError to set.
     * @return This builder for chaining.
     */
    public Builder setIsError(boolean value) {
      copyOnWrite();
      instance.setIsError(value);
      return this;
    }
    /**
     * <code>bool IsError = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsError() {
      copyOnWrite();
      instance.clearIsError();
      return this;
    }

    @java.lang.Override

    public int getMetaCount() {
      return instance.getMetaMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; Meta = 3;</code>
     */
    @java.lang.Override

    public boolean containsMeta(
        java.lang.String key) {
      java.util.Objects.requireNonNull(key);
      return instance.getMetaMap().containsKey(key);
    }

    public Builder clearMeta() {
      copyOnWrite();
      instance.getMutableMetaMap().clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; Meta = 3;</code>
     */

    public Builder removeMeta(
        java.lang.String key) {
      java.util.Objects.requireNonNull(key);
      copyOnWrite();
      instance.getMutableMetaMap().remove(key);
      return this;
    }
    /**
     * Use {@link #getMetaMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getMeta() {
      return getMetaMap();
    }
    /**
     * <code>map&lt;string, string&gt; Meta = 3;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.String> getMetaMap() {
      return java.util.Collections.unmodifiableMap(
          instance.getMetaMap());
    }
    /**
     * <code>map&lt;string, string&gt; Meta = 3;</code>
     */
    @java.lang.Override

    public /* nullable */
java.lang.String getMetaOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue) {
      java.util.Objects.requireNonNull(key);
      java.util.Map<java.lang.String, java.lang.String> map =
          instance.getMetaMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; Meta = 3;</code>
     */
    @java.lang.Override

    public java.lang.String getMetaOrThrow(
        java.lang.String key) {
      java.util.Objects.requireNonNull(key);
      java.util.Map<java.lang.String, java.lang.String> map =
          instance.getMetaMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    /**
     * <code>map&lt;string, string&gt; Meta = 3;</code>
     */
    public Builder putMeta(
        java.lang.String key,
        java.lang.String value) {
      java.util.Objects.requireNonNull(key);
      java.util.Objects.requireNonNull(value);
      copyOnWrite();
      instance.getMutableMetaMap().put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; Meta = 3;</code>
     */
    public Builder putAllMeta(
        java.util.Map<java.lang.String, java.lang.String> values) {
      copyOnWrite();
      instance.getMutableMetaMap().putAll(values);
      return this;
    }

    /**
     * <code>repeated .agentassistproto.McpResultContent contents = 4;</code>
     */
    @java.lang.Override
    public java.util.List<code.agentassistant.flutter.flutterclient.proto.McpResultContent> getContentsList() {
      return java.util.Collections.unmodifiableList(
          instance.getContentsList());
    }
    /**
     * <code>repeated .agentassistproto.McpResultContent contents = 4;</code>
     */
    @java.lang.Override
    public int getContentsCount() {
      return instance.getContentsCount();
    }/**
     * <code>repeated .agentassistproto.McpResultContent contents = 4;</code>
     */
    @java.lang.Override
    public code.agentassistant.flutter.flutterclient.proto.McpResultContent getContents(int index) {
      return instance.getContents(index);
    }
    /**
     * <code>repeated .agentassistproto.McpResultContent contents = 4;</code>
     */
    public Builder setContents(
        int index, code.agentassistant.flutter.flutterclient.proto.McpResultContent value) {
      copyOnWrite();
      instance.setContents(index, value);
      return this;
    }
    /**
     * <code>repeated .agentassistproto.McpResultContent contents = 4;</code>
     */
    public Builder setContents(
        int index, code.agentassistant.flutter.flutterclient.proto.McpResultContent.Builder builderForValue) {
      copyOnWrite();
      instance.setContents(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .agentassistproto.McpResultContent contents = 4;</code>
     */
    public Builder addContents(code.agentassistant.flutter.flutterclient.proto.McpResultContent value) {
      copyOnWrite();
      instance.addContents(value);
      return this;
    }
    /**
     * <code>repeated .agentassistproto.McpResultContent contents = 4;</code>
     */
    public Builder addContents(
        int index, code.agentassistant.flutter.flutterclient.proto.McpResultContent value) {
      copyOnWrite();
      instance.addContents(index, value);
      return this;
    }
    /**
     * <code>repeated .agentassistproto.McpResultContent contents = 4;</code>
     */
    public Builder addContents(
        code.agentassistant.flutter.flutterclient.proto.McpResultContent.Builder builderForValue) {
      copyOnWrite();
      instance.addContents(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .agentassistproto.McpResultContent contents = 4;</code>
     */
    public Builder addContents(
        int index, code.agentassistant.flutter.flutterclient.proto.McpResultContent.Builder builderForValue) {
      copyOnWrite();
      instance.addContents(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .agentassistproto.McpResultContent contents = 4;</code>
     */
    public Builder addAllContents(
        java.lang.Iterable<? extends code.agentassistant.flutter.flutterclient.proto.McpResultContent> values) {
      copyOnWrite();
      instance.addAllContents(values);
      return this;
    }
    /**
     * <code>repeated .agentassistproto.McpResultContent contents = 4;</code>
     */
    public Builder clearContents() {
      copyOnWrite();
      instance.clearContents();
      return this;
    }
    /**
     * <code>repeated .agentassistproto.McpResultContent contents = 4;</code>
     */
    public Builder removeContents(int index) {
      copyOnWrite();
      instance.removeContents(index);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:agentassistproto.WorkReportResponse)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new code.agentassistant.flutter.flutterclient.proto.WorkReportResponse();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "iD_",
            "isError_",
            "meta_",
            MetaDefaultEntryHolder.defaultEntry,
            "contents_",
            code.agentassistant.flutter.flutterclient.proto.McpResultContent.class,
          };
          java.lang.String info =
              "\u0000\u0004\u0000\u0000\u0001\u0004\u0004\u0001\u0001\u0000\u0001\u0208\u0002\u0007" +
              "\u00032\u0004\u001b";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<code.agentassistant.flutter.flutterclient.proto.WorkReportResponse> parser = PARSER;
        if (parser == null) {
          synchronized (code.agentassistant.flutter.flutterclient.proto.WorkReportResponse.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<code.agentassistant.flutter.flutterclient.proto.WorkReportResponse>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:agentassistproto.WorkReportResponse)
  private static final code.agentassistant.flutter.flutterclient.proto.WorkReportResponse DEFAULT_INSTANCE;
  static {
    WorkReportResponse defaultInstance = new WorkReportResponse();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      WorkReportResponse.class, defaultInstance);
  }

  public static code.agentassistant.flutter.flutterclient.proto.WorkReportResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<WorkReportResponse> PARSER;

  public static com.google.protobuf.Parser<WorkReportResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

